(*
   AllocationTests.mli - Verify allocation, operand preservation, and root ownership emission.
   Sleep is target-native on every supported ARM64 OS. Milliseconds are first
   converted to integral nanoseconds, then split into a normalized timespec;
   EINTR resumes from the kernel-provided remainder.
   Host discovery and signalling have target-specific kernel ABIs. Exercise
   the complete native lowering for each supported ARM64 target so a Linux
   syscall number or error convention cannot accidentally leak into macOS.
   The shared list-retain helper's instruction shape is not observable in an
   executable E2E test, so inspect the symbolic code generated by one retain.
   The shared dictionary-retain helper's instruction shape is not observable in
   an executable E2E test, so inspect the symbolic code generated by one retain.
   The shared dictionary-release helper's instruction shape is not observable
   in an executable E2E test, so inspect its symbolic code directly.
   Structural-child tag clearing inside the shared dictionary-release helper is
   not observable in an executable E2E test, so inspect its symbolic code directly.
   Dictionary-helper bitmap popcount shape is not observable in an executable
   E2E test, so ensure both shared helpers avoid a data-dependent counting loop.
   The shared list-release helper's traversal instruction shape is not
   observable in an executable E2E test, so inspect its symbolic code directly.
   Structural-child tag clearing inside the shared list-release helper is not
   observable in an executable E2E test, so inspect its symbolic code directly.
   Conditional block layout is not observable in an executable E2E test, so
   inspect the symbolic branch sequence directly.
   The multiply-by-constant selector creates this shared-source shape before
   final block layout. A following branch must not hide the shift temporary's
   established single-use contract from the target peephole.
   RawAlloc should branch to a shared overflow label, rather than inlining
   the full overflow trap sequence at each allocation site.
*)
val testGeneratedCodeEliminatesSelfMoves : unit -> (unit,string) result
val testSleepUsesNormalizedInterruptSafeNanosleep : unit -> (unit,string) result
val testCliHostOperationsUseTargetKernelABIs : unit -> (unit,string) result
val testListRetainHelperClearsTagWithImmediateMask : unit -> (unit,string) result
val testDictRetainHelperClearsTagWithImmediateMask : unit -> (unit,string) result
val testDictReleaseHelperClearsTagWithImmediateMask : unit -> (unit,string) result
val testDictReleaseHelperClearsChildTagWithImmediateMask : unit -> (unit,string) result
val testDictHelpersUseConstantTimeBitmapPopcount : unit -> (unit,string) result
val testListReleaseHelperClearsTagWithImmediateMask : unit -> (unit,string) result
val testListReleaseHelperClearsChildTagWithImmediateMask : unit -> (unit,string) result
val testPeepholeFusesBitClearSequence : unit -> (unit,string) result
val testPeepholeFallsThroughToTrueTarget : unit -> (unit,string) result
val testPeepholeCombinesOperandsAndMemoryPairs : unit -> (unit,string) result
val testPeepholeCombinesEveryExtensionAndFloatStorePairs : unit -> (unit,string) result
val testPeepholeCombinesShiftedSubtraction : unit -> (unit,string) result
val testPeepholePreservesSharedSourceShiftFusionAcrossBranch : unit -> (unit,string) result
val testArm64FLoadEncodableConstantsUseImmediate : unit -> (unit,string) result
val testRawAllocUsesSharedHeapOverflowPath : unit -> (unit,string) result
val testRuntimePrintStringLengthUsesFullImmediate : unit -> (unit,string) result
val testRawSlotInitPureEnumDoesNotEmitGenericRetain : unit -> (unit,string) result
val testListTuple3BytesListDictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testListTuple3StringListDictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testListTuple3ClosureListDictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testListTuple4StringBytesListDictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testListTuple4ClosureStringListDictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testListTuple4ClosureBytesListDictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testListDictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testListDictStringPayloadUsesPlannedDictHelper : unit -> (unit,string) result
val testListNestedTupleDictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testListTuple2NestedTupleDictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testListTuple4NestedTupleDynamicDictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testListTuple4NestedRecordMiddleDictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testListTuple4NestedTupleClosureDictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testListSumTuple3DictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testListSumTuple4DictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testListSumTuple3ClosureDictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testListSumTuple4ClosureDictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testListSumTuple4ClosureStringDictListValueUsesTypedDictHelper : unit -> (unit,string) result
val testDictDictListValueUsesPlannedDictHelper : unit -> (unit,string) result
val testDictStringKeyUsesPlannedDictHelper : unit -> (unit,string) result
val testDictStringValueUsesPlannedDictHelper : unit -> (unit,string) result
val testDictStringKeyListValueUsesPlannedDictHelper : unit -> (unit,string) result
val testDictStringKeyTupleValueUsesPlannedDictHelper : unit -> (unit,string) result
val testDictStringKeyValuePlannedHelperReleasesCollisionPayloads : unit -> (unit,string) result
