(*
   AllocationTests.fs - Verify allocation, operand preservation, and root ownership emission.
   Sleep is target-native on every supported ARM64 OS. Milliseconds are first
   converted to integral nanoseconds, then split into a normalized timespec;
   EINTR resumes from the kernel-provided remainder.
   Host discovery and signalling have target-specific kernel ABIs. Exercise
   the complete native lowering for each supported ARM64 target so a Linux
   syscall number or error convention cannot accidentally leak into macOS.
   The shared list-retain helper's instruction shape is not observable in an
   executable E2E test, so inspect the symbolic code generated by one retain.
   The shared dictionary-retain helper's instruction shape is not observable in
   an executable E2E test, so inspect the symbolic code generated by one retain.
   The shared dictionary-release helper's instruction shape is not observable
   in an executable E2E test, so inspect its symbolic code directly.
   Structural-child tag clearing inside the shared dictionary-release helper is
   not observable in an executable E2E test, so inspect its symbolic code directly.
   Dictionary-helper bitmap popcount shape is not observable in an executable
   E2E test, so ensure both shared helpers avoid a data-dependent counting loop.
   The shared list-release helper's traversal instruction shape is not
   observable in an executable E2E test, so inspect its symbolic code directly.
   Structural-child tag clearing inside the shared list-release helper is not
   observable in an executable E2E test, so inspect its symbolic code directly.
   Conditional block layout is not observable in an executable E2E test, so
   inspect the symbolic branch sequence directly.
   The multiply-by-constant selector creates this shared-source shape before
   final block layout. A following branch must not hide the shift temporary's
   established single-use contract from the target peephole.
   RawAlloc should branch to a shared overflow label, rather than inlining
   the full overflow trap sequence at each allocation site.
*)
[@@@warning "-4-42"]
open Dark_compiler
open Fixtures
module L=LIR
module S=Symbolic
module M=StringOrder.Map
let (let*)=Result.bind
let require condition error=if condition then Ok () else Error error
let generate instructions=makeSimpleProgramWithVariants instructions M.empty |> generatePreparedARM64 target
let release kind typ=L.RefCountDec (L.Physical L.X0,0,kind,Some (rcMetadata typ))
let convertRawAlloc dest numBytes=
 let ctx:ARM64CodeGenTypes.codeGenContext={ARM64CodeGenTypes.target;options=ARM64CodeGenTypes.defaultOptions;sumShapeRegistry=M.empty;recordRegistry=M.empty;rawSlotInitRetainTargets=None;closurePayloadSizes=M.empty;closureCaptureTypes=M.empty;functionNames=FunctionIdMap.empty;functionName="test";instructionSite="test_0";stackSize=0;usedCalleeSaved=[];usedCalleeSavedF=[];heapOverflowLabel="__heap_oom_test";recordLirOpExpansion=None} in
 ARM64Instructions.convertInstr ctx (L.RawAlloc (L.Physical dest,L.Physical numBytes))
let testGeneratedCodeEliminatesSelfMoves ()=
 let* instrs=generate [L.Mov (L.Physical L.X1,L.Reg (L.Physical L.X1));L.FMov (L.FPhysical L.D1,L.FPhysical L.D1)] in
 require (not (List.exists (function S.MOV_reg (d,s) when d=s->true|S.FMOV_reg (d,s) when d=s->true|_->false) instrs)) "Generated ARM64 code contains a redundant self-move"
let windows n xs=
 let rec loop xs=if List.length xs<n then [] else List.take n xs::loop (List.tl xs) in loop xs
let containsSyscall register number immediate instrs=windows 2 instrs |> List.exists (function [S.MOVZ (reg,value,0);S.SVC imm] when reg=register && value=number && imm=immediate->true|_->false)
let bothTargets instructions description operation=
 let program=makeSimpleProgramWithVariants instructions M.empty in
 let gen name os=generatePreparedARM64 (ARM64.targetConfigFor os) program |> Result.map_error (fun error->name^" "^description^" lowering failed: "^error) in
 match gen "Linux ARM64" Platform.LinuxARM64,gen "macOS ARM64" Platform.MacOSARM64 with Error error,_|_,Error error->Error error|Ok linux,Ok mac->operation linux mac
let testSleepUsesNormalizedInterruptSafeNanosleep ()=bothTargets [L.Sleep (41,L.FPhysical L.D0)] "sleep" (fun linux mac->
 let normalization=List.for_all (fun instr->List.mem instr linux) [S.FMUL (S.D16,S.D0,S.D16);S.FCVTZS (S.X9,S.D16);S.SDIV (S.X10,S.X9,S.X12);S.MSUB (S.X11,S.X10,S.X12,S.X9)] in
 let linuxSyscall=containsSyscall S.X8 Platform.linuxARM64SyscallNumbers.Platform.nanosleep 0 linux and macSyscall=containsSyscall S.X16 Platform.macOSARM64SyscallNumbers.Platform.nanosleep 128 mac in
 let retry=List.mem (S.LDP (S.X10,S.X11,S.SP,16)) linux && List.exists (function S.B_cond_label (ARM64.LO,_)->true|_->false) mac && List.mem (S.CMP_imm (S.X0,4)) mac in
 require (normalization && linuxSyscall && macSyscall && retry) "ARM64 sleep did not emit normalized interrupt-safe nanosleep lowering for both targets")
let testCliHostOperationsUseTargetKernelABIs ()=bothTargets [L.CliNative (L.Physical L.X0,L.HostArchitecture,[]);L.CliNative (L.Physical L.X0,L.Hostname,[]);L.CliNative (L.Physical L.X0,L.CpuCount,[]);L.CliNative (L.Physical L.X0,L.Kill,[L.Imm 1L;L.Imm 0L])] "CLI host" (fun linux mac->
 let linuxContract=List.mem (S.MOVZ (S.X0,2,0)) linux && List.for_all (fun number->containsSyscall S.X8 number 0 linux) [160;123;129] && List.exists (function S.B_cond_label (ARM64.LT,_)->true|_->false) linux in
 let macContract=List.mem (S.MOVZ (S.X0,3,0)) mac && List.for_all (fun number->containsSyscall S.X16 number 128 mac) [164;202;37] && List.exists (function S.B_cond_label (ARM64.HS,_)->true|_->false) mac in
 require (linuxContract && macContract) "ARM64 CLI host operations did not preserve the Linux and macOS kernel ABIs")
let clearTag instruction dest source error=let* instrs=generate [instruction] in require (List.mem (S.AND_imm (dest,source,-8L)) instrs) error
let testListRetainHelperClearsTagWithImmediateMask ()=clearTag (L.RefCountInc (L.Physical L.X1,8,L.TaggedList,None)) S.X2 S.X0 "ARM64 list retain helper did not clear tag bits with one immediate mask"
let testDictRetainHelperClearsTagWithImmediateMask ()=clearTag (L.RefCountInc (L.Physical L.X1,8,L.DictHeap,None)) S.X2 S.X0 "ARM64 dictionary retain helper did not clear tag bits with one immediate mask"
let testDictReleaseHelperClearsTagWithImmediateMask ()=clearTag (release L.DictHeap (AST.TDict (AST.TInt64,AST.TInt64))) S.X3 S.X0 "ARM64 dictionary release helper did not clear tag bits with one immediate mask"
let testDictReleaseHelperClearsChildTagWithImmediateMask ()=clearTag (release L.DictHeap (AST.TDict (AST.TInt64,AST.TInt64))) S.X10 S.X8 "ARM64 dictionary release helper did not clear structural-child tag bits with one immediate mask"
let testDictHelpersUseConstantTimeBitmapPopcount ()=
 let* instrs=generate [L.RefCountInc (L.Physical L.X0,0,L.DictHeap,None);release L.DictHeap (AST.TDict (AST.TInt64,AST.TInt64))] in
 let* ()=require (not (List.exists (function S.Label label when Text.contains label "_popcount_loop"->true|_->false) instrs)) "ARM64 dictionary helpers count bitmap bits with a data-dependent loop" in
 let pop source result=List.mem [S.FMOV_from_gp (S.D16,source);S.CNT_8B (S.D16,S.D16);S.ADDV_8B (S.D16,S.D16);S.UMOV_byte (result,S.D16)] (windows 4 instrs) in
 let* ()=require (pop S.X4 S.X3) "ARM64 dictionary retain helper omitted constant-time bitmap popcount" in
 require (pop S.X6 S.X5) "ARM64 dictionary release helper omitted constant-time bitmap popcount"
let testListReleaseHelperClearsTagWithImmediateMask ()=clearTag (release L.TaggedList (AST.TList AST.TInt64)) S.X3 S.X0 "ARM64 list release helper did not clear tag bits with one immediate mask"
let testListReleaseHelperClearsChildTagWithImmediateMask ()=clearTag (release L.TaggedList (AST.TList AST.TInt64)) S.X10 S.X8 "ARM64 list release helper did not clear structural-child tag bits with one immediate mask"
let render instructions=List.map PassTestRunner.prettyPrintARM64Instr instructions |> String.concat "; "
let testPeepholeFusesBitClearSequence ()=
 let before=[S.MOVN (S.X9,0,0);S.EOR_reg (S.X10,S.X2,S.X9);S.AND_reg (S.X10,S.X1,S.X10)] in
 let liveTemporary=[S.MOVN (S.X9,0,0);S.EOR_reg (S.X10,S.X2,S.X9);S.AND_reg (S.X3,S.X1,S.X10)] in
 let liveMask=before@[S.ADD_reg (S.X0,S.X9,S.X4)] and expected=[S.BIC_reg (S.X10,S.X1,S.X2)] in
 let overwritten=before@[S.MOV_reg (S.X9,S.X4)] and expectedOverwrite=expected@[S.MOV_reg (S.X9,S.X4)] in
 let actual=Peephole.peepholeOptimize before in
 if actual<>expected then Error ("Expected BIC_reg(X10, X1, X2), got "^render actual)
 else if Peephole.peepholeOptimize liveTemporary<>liveTemporary then Error "Bit-clear peephole fused a sequence whose inverted temporary remains live"
 else if Peephole.peepholeOptimize liveMask<>liveMask then Error "Bit-clear peephole fused a sequence whose all-ones mask remains live"
 else if Peephole.peepholeOptimize overwritten<>expectedOverwrite then Error "Bit-clear peephole did not fuse a sequence whose all-ones mask is overwritten" else Ok ()
let peephole before expected error=let actual=Peephole.peepholeOptimize before in if actual=expected then Ok () else Error (error^", got "^render actual)
let testPeepholeFallsThroughToTrueTarget ()=peephole [S.B_cond_label (ARM64.LE,"true_target");S.B_label "false_target";S.Label "true_target"] [S.B_cond_label (ARM64.GT,"false_target");S.Label "true_target"] "Expected inverted branch with true-target fallthrough"
let testPeepholeCombinesOperandsAndMemoryPairs ()=peephole [S.LSL_imm (S.X9,S.X2,3);S.ADD_reg (S.X0,S.X1,S.X9);S.SXTW (S.X10,S.X3);S.ADD_reg (S.X4,S.X5,S.X10);S.STR (S.X11,S.SP,16);S.STR (S.X13,S.SP,24)] [S.ADD_shifted (S.X0,S.X1,S.X2,3);S.ADD_extended (S.X4,S.X5,S.X3,ARM64.ExtendSXTW);S.STP (S.X11,S.X13,S.SP,16)] "Expected shifted/extended operands and paired memory operations"
let testPeepholeCombinesEveryExtensionAndFloatStorePairs ()=
 let cases=[S.UXTB (S.X10,S.X3),ARM64.ExtendUXTB;S.UXTH (S.X10,S.X3),ARM64.ExtendUXTH;S.UXTW (S.X10,S.X3),ARM64.ExtendUXTW;S.SXTB (S.X10,S.X3),ARM64.ExtendSXTB;S.SXTH (S.X10,S.X3),ARM64.ExtendSXTH;S.SXTW (S.X10,S.X3),ARM64.ExtendSXTW] in
 let failure=List.find_map (fun (extension,kind)->let actual=Peephole.peepholeOptimize [extension;S.ADD_reg (S.X10,S.X5,S.X10)] in if actual=[S.ADD_extended (S.X10,S.X5,S.X3,kind)] then None else Some (render actual)) cases in
 match failure with Some failure->Error ("Expected every extension kind to fold into ADD_extended; failed "^failure)|None->peephole [S.STR_fp (S.D2,S.SP,32);S.STR_fp (S.D3,S.SP,40)] [S.STP_fp (S.D2,S.D3,S.SP,32)] "Expected aligned Float stack stores to form STP_fp"
let testPeepholeCombinesShiftedSubtraction ()=peephole [S.LSL_imm (S.X9,S.X2,3);S.SUB_reg (S.X9,S.X1,S.X9)] [S.SUB_shifted (S.X9,S.X1,S.X2,3)] "Expected shifted subtraction to form SUB_shifted"
let testPeepholePreservesSharedSourceShiftFusionAcrossBranch ()=peephole [S.LSL_imm (S.X4,S.X1,1);S.ADD_reg (S.X1,S.X1,S.X4);S.B_label "loop"] [S.ADD_shifted (S.X1,S.X1,S.X1,1);S.B_label "loop"] "Expected shared-source shifted ADD before control flow"
let testArm64FLoadEncodableConstantsUseImmediate ()=
 let* instrs=generate [L.FLoad (L.FPhysical L.D2,1.);L.FLoad (L.FPhysical L.D3,4.);L.FLoad (L.FPhysical L.D4,0.)] in
 let hasLiteral=List.exists (function S.ADRP (_,S.DataLabel (S.FloatLiteral (1.|4.)))|S.ADD_label (_,_,S.DataLabel (S.FloatLiteral (1.|4.)))|S.LDR_fp ((S.D2|S.D3),S.X9,0)->true|_->false) instrs in
 let hasZeroLiteral=List.exists (function S.ADRP (_,S.DataLabel (S.FloatLiteral 0.))|S.ADD_label (_,_,S.DataLabel (S.FloatLiteral 0.))|S.LDR_fp (S.D4,S.X9,0)->true|_->false) instrs in
 let* ()=require (List.mem (S.FMOV_imm (S.D2,1.)) instrs) "FLoad 1.0 did not emit a floating-point immediate" in
 let* ()=require (List.mem (S.FMOV_imm (S.D3,4.)) instrs) "FLoad 4.0 did not emit a floating-point immediate" in
 let* ()=require (not hasLiteral) "Encodable FLoad used a literal-pool load instead of an immediate" in
 let* ()=require (not hasZeroLiteral) "Positive-zero FLoad used a literal-pool load" in require (List.mem (S.FMOV_zero S.D4) instrs) "Positive-zero FLoad did not use FMOV_zero"
let testRawAllocUsesSharedHeapOverflowPath ()=
 let* instrs=convertRawAlloc L.X0 L.X1 |> Result.map_error (fun e->"Failed to convert RawAlloc: "^e) in
 let* ()=require (List.mem (S.CMP_reg (S.X14,S.X11)) instrs) "Expected RawAlloc bounds check to compare next pointer against computed heap end in X11" in
 let* ()=require (List.mem (S.MOVZ (S.X11,0x2000,16)) instrs) "Expected RawAlloc bounds check to compute heap end in X11" in
 let* ()=require (List.exists (function S.B_cond_label (ARM64.GT,_)->true|_->false) instrs) "Expected RawAlloc bounds check to branch to shared overflow label (B_cond_label GT)" in
 require (not (List.exists (function S.SVC _->true|_->false) instrs)) "RawAlloc still inlines overflow trap path (found SVC in fast path conversion)"
let testRuntimePrintStringLengthUsesFullImmediate ()=
 let instrs=PrintAndExit.generatePrintString target 65537 in
 let lower=List.mem (ARM64.MOVZ (ARM64.X2,1,0)) instrs and upper=List.mem (ARM64.MOVK (ARM64.X2,1,16)) instrs in
 let truncates=not (List.exists (function ARM64.MOVK (ARM64.X2,_,_)->true|_->false) instrs) && List.exists (function ARM64.MOVZ (ARM64.X2,(0|1),0)->true|_->false) instrs in
 if lower && upper then Ok () else if truncates then Error "Runtime print string length truncated 65537 bytes to a 16-bit low chunk" else Error "Runtime print string length did not emit both length chunks"
let testRawSlotInitPureEnumDoesNotEmitGenericRetain ()=
 let variants=M.singleton "RawSlotInitPureEnum" {L.typeParams=["a"];variants=[{L.name="RawSlotInitPureA";tag=0;payload=None;fieldCount=0};{L.name="RawSlotInitPureB";tag=1;payload=None;fieldCount=0}]} in
 let program=makeSimpleProgramWithVariants [L.RawSlotInit (L.Physical L.X0,L.Physical L.X1,L.Physical L.X3,AST.TSum ("RawSlotInitPureEnum",[AST.TString]))] variants in
 let* instrs=generatePreparedARM64 target program in require (not (List.exists (function S.LDR ((S.X15|S.X14),S.X3,16)->true|_->false) instrs)) "RawSlotInit of a generic pure enum emitted a generic heap retain"

let callsTypedHelper instrs=List.mem (S.BL "__dark_dict_refcount_dec_list_value_helper") instrs
let assertListElementUsesTypedDictListHelper typ caseName=
 let* instrs=generate [release L.TaggedList (AST.TList typ)] in require (callsTypedHelper instrs) (caseName^" did not emit typed dict-list value release helper")
let listInt=AST.TList AST.TInt64
let dictList=AST.TDict (AST.TInt64,listInt)
let closureType=AST.TFunction ([AST.TInt64],AST.TInt64)
let testListTuple3BytesListDictListValueUsesTypedDictHelper ()=assertListElementUsesTypedDictListHelper (AST.TTuple [AST.TBlob;listInt;dictList]) "List of tuple(bytes, list, dict<int, list<int>>)"
let testListTuple3StringListDictListValueUsesTypedDictHelper ()=assertListElementUsesTypedDictListHelper (AST.TTuple [AST.TString;listInt;dictList]) "List of tuple(string, list, dict<int, list<int>>)"
let testListTuple3ClosureListDictListValueUsesTypedDictHelper ()=assertListElementUsesTypedDictListHelper (AST.TTuple [closureType;listInt;dictList]) "List of tuple(closure, list, dict<int, list<int>>)"
let testListTuple4StringBytesListDictListValueUsesTypedDictHelper ()=assertListElementUsesTypedDictListHelper (AST.TTuple [AST.TString;AST.TBlob;listInt;dictList]) "List of tuple(string, bytes, list, dict<int, list<int>>)"
let testListTuple4ClosureStringListDictListValueUsesTypedDictHelper ()=assertListElementUsesTypedDictListHelper (AST.TTuple [closureType;AST.TString;listInt;dictList]) "List of tuple(closure, string, list, dict<int, list<int>>)"
let testListTuple4ClosureBytesListDictListValueUsesTypedDictHelper ()=assertListElementUsesTypedDictListHelper (AST.TTuple [closureType;AST.TBlob;listInt;dictList]) "List of tuple(closure, bytes, list, dict<int, list<int>>)"
let testListDictListValueUsesTypedDictHelper ()=assertListElementUsesTypedDictListHelper dictList "List of dict<int, list<int>>"
let callsPlannedDictHelper instrs=List.exists (function S.BL label when Text.startsWith label "__dark_dict_refcount_dec_plan_"->true|_->false) instrs
let testListDictStringPayloadUsesPlannedDictHelper ()=
 let* instrs=generate [release L.TaggedList (AST.TList (AST.TDict (AST.TString,AST.TString)))] in
 let* ()=require (ReleasePlanningTests.emitsPlannedListHelperLabel instrs) "List<Dict<String, String>> did not emit a planned list release helper" in
 require (callsPlannedDictHelper instrs) "List<Dict<String, String>> did not call a planned dictionary release helper"
let testListNestedTupleDictListValueUsesTypedDictHelper ()=assertListElementUsesTypedDictListHelper (AST.TTuple [AST.TString;AST.TBlob;AST.TTuple [dictList;AST.TString];listInt]) "List of tuple(string, bytes, tuple(dict<int, list<int>>, string), list<int>)"
let testListTuple2NestedTupleDictListValueUsesTypedDictHelper ()=assertListElementUsesTypedDictListHelper (AST.TTuple [AST.TInt64;AST.TTuple [AST.TString;AST.TBlob;listInt;dictList]]) "List of tuple(int, tuple(string, bytes, list<int>, dict<int, list<int>>))"
let testListTuple4NestedTupleDynamicDictListValueUsesTypedDictHelper ()=assertListElementUsesTypedDictListHelper (AST.TTuple [AST.TInt64;AST.TInt64;AST.TInt64;AST.TTuple [AST.TString;listInt;dictList]]) "List of tuple(int, int, int, tuple(string, list<int>, dict<int, list<int>>))"
let testListTuple4NestedRecordMiddleDictListValueUsesTypedDictHelper ()=
 let name="ARM64ListRcNestedRecordMiddleStringListDictList" in let records=M.singleton name ["name",AST.TString;"items",listInt;"lookup",dictList] in
 let typ=AST.TList (AST.TTuple [AST.TInt64;AST.TInt64;AST.TRecord (name,[]);AST.TInt64]) in
 let program=makeSimpleProgramWithRecords [L.RefCountDec (L.Physical L.X0,0,L.TaggedList,Some (rcMetadataWithRecords records typ))] records in
 let* instrs=generatePreparedARM64 target program in require (callsTypedHelper instrs) "List of tuple(int, int, record(string, list, dict<int, list<int>>), int) did not emit typed dict-list value release helper"
let testListTuple4NestedTupleClosureDictListValueUsesTypedDictHelper ()=assertListElementUsesTypedDictListHelper (AST.TTuple [AST.TInt64;AST.TInt64;AST.TInt64;AST.TTuple [closureType;AST.TString;listInt;dictList]]) "List of tuple(int, int, int, tuple(closure, string, list<int>, dict<int, list<int>>))"
let assertListSumPayloadUsesTypedDictListHelper payload caseName=
 let sanitized=String.to_seq caseName |> Seq.filter (fun c->not (List.mem c [' ';',';'(';')';'<';'>';'-'])) |> String.of_seq in
 let name="ARM64"^sanitized in let typ=AST.TSum (name,[]) in
 let variants=M.singleton name {L.typeParams=[];variants=[{L.name=name^"Case";tag=0;payload=Some payload;fieldCount=1}]} in
 let sums=M.singleton name {MemoryModel.typeParams=[];payloads=[0,Some payload];unaryPayloadTags=MemoryModel.IntSet.singleton 0} in
 let program=makeSimpleProgramWithVariants [L.RefCountDec (L.Physical L.X0,0,L.TaggedList,Some (rcMetadataWithSumShapes sums (AST.TList typ)))] variants in
 let* instrs=generatePreparedARM64 target program in require (callsTypedHelper instrs) (caseName^" sum payload did not emit typed dict-list value release helper")
let testListSumTuple3DictListValueUsesTypedDictHelper ()=assertListSumPayloadUsesTypedDictListHelper (AST.TTuple [AST.TString;listInt;dictList]) "sum tuple3 string list dict-list"
let testListSumTuple4DictListValueUsesTypedDictHelper ()=assertListSumPayloadUsesTypedDictListHelper (AST.TTuple [AST.TString;AST.TBlob;listInt;dictList]) "sum tuple4 string bytes list dict-list"
let testListSumTuple3ClosureDictListValueUsesTypedDictHelper ()=assertListSumPayloadUsesTypedDictListHelper (AST.TTuple [closureType;listInt;dictList]) "sum tuple3 closure list dict-list"
let testListSumTuple4ClosureDictListValueUsesTypedDictHelper ()=assertListSumPayloadUsesTypedDictListHelper (AST.TTuple [closureType;AST.TBlob;listInt;dictList]) "sum tuple4 closure bytes list dict-list"
let testListSumTuple4ClosureStringDictListValueUsesTypedDictHelper ()=assertListSumPayloadUsesTypedDictListHelper (AST.TTuple [closureType;AST.TString;listInt;dictList]) "sum tuple4 closure string list dict-list"
let testDictDictListValueUsesPlannedDictHelper ()=
 let* instrs=generate [release L.DictHeap (AST.TDict (AST.TInt64,dictList))] in
 let* ()=require (callsPlannedDictHelper instrs) "Dict<int, dict<int, list<int>>> did not emit a planned dict release helper" in
 require (not (List.mem (S.BL "__dark_dict_refcount_dec_dict_list_value_helper") instrs)) "Dict<int, dict<int, list<int>>> still emitted the typed nested dict-list helper"
let assertDictRefCountDecUsesPlannedDictHelper typ caseName=let* instrs=generate [release L.DictHeap typ] in require (callsPlannedDictHelper instrs) (caseName^" did not emit a planned dict release helper")
let testDictStringKeyUsesPlannedDictHelper ()=assertDictRefCountDecUsesPlannedDictHelper (AST.TDict (AST.TString,AST.TInt64)) "Dict<string, int>"
let testDictStringValueUsesPlannedDictHelper ()=assertDictRefCountDecUsesPlannedDictHelper (AST.TDict (AST.TInt64,AST.TString)) "Dict<int, string>"
let testDictStringKeyListValueUsesPlannedDictHelper ()=assertDictRefCountDecUsesPlannedDictHelper (AST.TDict (AST.TString,listInt)) "Dict<string, list<int>>"
let testDictStringKeyTupleValueUsesPlannedDictHelper ()=assertDictRefCountDecUsesPlannedDictHelper (AST.TDict (AST.TString,AST.TTuple [AST.TString;listInt])) "Dict<string, tuple<string, list<int>>>"
let testDictStringKeyValuePlannedHelperReleasesCollisionPayloads ()=
 let* instrs=generate [release L.DictHeap (AST.TDict (AST.TString,AST.TString))] in require (List.exists (function S.Label label when Text.contains label "collision_payload_loop"->true|_->false) instrs) "Dict<string, string> planned helper did not emit a collision payload release loop"
