// ARM64CodeGenTests.fs - Register ARM64 lowering and runtime contract tests.

module ARM64CodeGenTests

open ARM64CodeGenFixtures
open ARM64ReleasePlanningTests
open ARM64ControlFlowTests
open ARM64AllocationTests
open ARM64DestructionTests
open ARM64PlanningBoundaryTests

let tests : (string * (unit -> TestResult)) list = [
    ("LIR ARM64 codegen reports missing entry block", testReportsMissingEntryBlock)
    ("Generated ARM64 code eliminates self-moves", testGeneratedCodeEliminatesSelfMoves)
    ("ARM64 compact record fields start at offset zero", testCompactRecordFieldsStartAtOffsetZero)
    ("Generated ARM64 entry uses allocator transfers only", testGeneratedEntryUsesAllocatorTransfersOnly)
    ("ARM64 Sleep normalizes timeout and retries nanosleep", testSleepUsesNormalizedInterruptSafeNanosleep)
    ("ARM64 CLI host operations use target kernel ABIs", testCliHostOperationsUseTargetKernelABIs)

    ("ARM64 list retain helper clears tag with immediate mask", testListRetainHelperClearsTagWithImmediateMask)
    ("ARM64 dictionary retain helper clears tag with immediate mask", testDictRetainHelperClearsTagWithImmediateMask)
    ("ARM64 dictionary release helper clears tag with immediate mask", testDictReleaseHelperClearsTagWithImmediateMask)
    ("ARM64 dictionary release helper clears child tag with immediate mask", testDictReleaseHelperClearsChildTagWithImmediateMask)
    ("ARM64 dictionary helpers use constant-time bitmap popcount", testDictHelpersUseConstantTimeBitmapPopcount)
    ("ARM64 list release helper clears tag with immediate mask", testListReleaseHelperClearsTagWithImmediateMask)
    ("ARM64 list release helper clears child tag with immediate mask", testListReleaseHelperClearsChildTagWithImmediateMask)
    ("ARM64 peephole fuses bit-clear sequence", testPeepholeFusesBitClearSequence)
    ("ARM64 peephole falls through to true branch target", testPeepholeFallsThroughToTrueTarget)
    ("ARM64 peephole combines operands and memory pairs", testPeepholeCombinesOperandsAndMemoryPairs)
    ("ARM64 UInt64 runtime zero branches target digit handlers", testPrintUInt64RuntimeZeroBranches)
    ("ARM64 UInt64 runtime preserves trailing newline", testPrintUInt64RuntimePreservesNewline)
    ("ARM64 branch false edge falls through", testBranchFalseEdgeFallsThrough)
    ("ARM64 common-return transfer cost", testSharedReturnTransferCost)
    ("ARM64 dynamic buffer RC instruction cost", testDynamicBufferRcInstructionCost)
    ("ARM64 primitive list payload preservation cost", testPrimitiveListPayloadPreservationCost)
    ("ARM64 FLoad encodable constants use immediate", testArm64FLoadEncodableConstantsUseImmediate)
    ("RawAlloc uses shared heap overflow path", testRawAllocUsesSharedHeapOverflowPath)
    ("Runtime print string length uses full immediate", testRuntimePrintStringLengthUsesFullImmediate)
    ("RawSlotInit pure enum skips generic retain", testRawSlotInitPureEnumDoesNotEmitGenericRetain)
    ("Small generic release plan remains inline", testSmallGenericReleasePlanRemainsInline)
    ("Expensive generic release is prepared as a call", testExpensiveGenericReleaseIsPreparedAsCall)
    ("Generic release helper preserves cached instructions", testGenericReleaseHelperPreservesCachedInstructions)
    ("Outlined generic release uses allocator liveness", testOutlinedGenericReleaseUsesAllocatorLiveness)
    ("Generic release helpers preserve ownership policy", testGenericReleaseHelpersPreserveOwnershipPolicy)
    ("List tuple3 bytes/list/dict-list uses typed dict helper", testListTuple3BytesListDictListValueUsesTypedDictHelper)
    ("List tuple3 string/list/dict-list uses typed dict helper", testListTuple3StringListDictListValueUsesTypedDictHelper)
    ("List tuple3 closure/list/dict-list uses typed dict helper", testListTuple3ClosureListDictListValueUsesTypedDictHelper)
    ("List tuple4 string/bytes/list/dict-list uses typed dict helper", testListTuple4StringBytesListDictListValueUsesTypedDictHelper)
    ("List tuple4 closure/string/list/dict-list uses typed dict helper", testListTuple4ClosureStringListDictListValueUsesTypedDictHelper)
    ("List tuple4 closure/bytes/list/dict-list uses typed dict helper", testListTuple4ClosureBytesListDictListValueUsesTypedDictHelper)
    ("List dict-list uses typed dict helper", testListDictListValueUsesTypedDictHelper)
    ("List dict-string payload uses planned dict helper", testListDictStringPayloadUsesPlannedDictHelper)
    ("List nested tuple dict-list uses typed dict helper", testListNestedTupleDictListValueUsesTypedDictHelper)
    ("List tuple2 nested tuple dict-list uses typed dict helper", testListTuple2NestedTupleDictListValueUsesTypedDictHelper)
    ("List tuple4 nested tuple dynamic dict-list uses typed dict helper", testListTuple4NestedTupleDynamicDictListValueUsesTypedDictHelper)
    ("List tuple4 nested record middle dict-list uses typed dict helper", testListTuple4NestedRecordMiddleDictListValueUsesTypedDictHelper)
    ("List tuple4 nested tuple closure dict-list uses typed dict helper", testListTuple4NestedTupleClosureDictListValueUsesTypedDictHelper)
    ("List sum tuple3 dict-list uses typed dict helper", testListSumTuple3DictListValueUsesTypedDictHelper)
    ("List sum tuple4 dict-list uses typed dict helper", testListSumTuple4DictListValueUsesTypedDictHelper)
    ("List sum tuple3 closure dict-list uses typed dict helper", testListSumTuple3ClosureDictListValueUsesTypedDictHelper)
    ("List sum tuple4 closure dict-list uses typed dict helper", testListSumTuple4ClosureDictListValueUsesTypedDictHelper)
    ("List sum tuple4 closure string dict-list uses typed dict helper", testListSumTuple4ClosureStringDictListValueUsesTypedDictHelper)
    ("Dict dict-list uses planned dict helper", testDictDictListValueUsesPlannedDictHelper)
    ("Dict string key uses planned dict helper", testDictStringKeyUsesPlannedDictHelper)
    ("Dict string value uses planned dict helper", testDictStringValueUsesPlannedDictHelper)
    ("Dict string key list value uses planned dict helper", testDictStringKeyListValueUsesPlannedDictHelper)
    ("Dict string key tuple value uses planned dict helper", testDictStringKeyTupleValueUsesPlannedDictHelper)
    ("Dict string key/value planned helper releases collision payloads", testDictStringKeyValuePlannedHelperReleasesCollisionPayloads)
    ("Dict list value planned helper releases collision payloads", testDictListValuePlannedHelperReleasesCollisionPayloads)
    ("Dict tuple value planned helper releases collision payloads", testDictTupleValuePlannedHelperReleasesCollisionPayloads)
    ("Dict string key tuple value planned helper releases collision payloads", testDictStringKeyTupleValuePlannedHelperReleasesCollisionPayloads)
    ("Generic fixed-block nested bytes field uses release plan", testGenericFixedBlockNestedBytesFieldUsesReleasePlan)
    ("Planned list generic leaf release reloads block pointer", testPlannedListGenericLeafReleaseReloadsBlockPointer)
    ("Planned list nested generic release preserves block pointer", testPlannedListNestedGenericReleasePreservesBlockPointer)
    ("Planned list tuple payload uses planned helper", testPlannedListTuplePayloadUsesPlannedHelper)
    ("Planned list record payload uses planned helper", testPlannedListRecordPayloadUsesPlannedHelper)
    ("Planned list record nested string-dict uses planned list helper", testPlannedListRecordNestedStringDictUsesPlannedListHelper)
    ("Planned list tuple5 payload uses planned helper", testPlannedListTuple5PayloadUsesPlannedHelper)
    ("Planned list record5 payload uses planned helper", testPlannedListRecord5PayloadUsesPlannedHelper)
    ("Generic fixed-block nested immediate field releases child root", testGenericFixedBlockNestedImmediateFieldReleasesChildRoot)
    ("Generic fixed-block nested mixed boxed-sum bytes payload uses variant dispatch", testGenericFixedBlockNestedMixedBoxedSumBytesPayloadUsesVariantDispatch)
    ("Generic mixed boxed-sum payload dispatch skips remaining cases", testGenericMixedBoxedSumPayloadDispatchSkipsRemainingCases)
    ("Recursive-sum release skips variants without managed fields", testRecursiveSumReleaseSkipsVariantWithoutManagedFields)
    ("Closure capture nested fixed-block bytes field uses release plan", testClosureCaptureNestedFixedBlockBytesFieldUsesReleasePlan)
    ("Closure capture boxed-sum bytes payload uses release plan", testClosureCaptureBoxedSumBytesPayloadUsesReleasePlan)
    ("ARM64 codegen rejects unprepared facts", testRejectsUnpreparedCodegenFacts)
    ("ARM64 codegen attributes LIR opcode expansion", testLirOpExpansionRecorderAttributesGeneratedInstructions)
]
