(* Full encoding fixture parsers, outcomes and mismatch diagnostics. *)
[@@@warning "-42"]
open Dark_compiler
module J=Semantic_observation.SemanticJson
module ISA=Semantic_observation.MachineISAObservation
let tuple=J.tuple
let list f xs=`List (List.map f xs)
let result encode=function Ok value->J.union "FSharpResult" "Ok" [encode value]|Error error->J.union "FSharpResult" "Error" [J.string error]
let uint32 value=`Assoc ["kind",`String "uint32";"value",`String (Printf.sprintf "%lu" value)]
let bytes=Semantic_observation.X64EncodingObservation.bytes
let outcome (value:TestOutcome.t)=J.record "PassTestResult" ["Success",`Bool value.TestOutcome.success;"Message",J.string value.TestOutcome.message;"Expected",J.option J.string value.TestOutcome.expected;"Actual",J.option J.string value.TestOutcome.actual]
let x64Expectation=function X86_64EncodingFormat.ResolvesTo (values,fixups)->J.union "X64EncodingExpectation" "ResolvesTo" [J.option bytes values;list J.string fixups]|X86_64EncodingFormat.ResolutionErrorContaining value->J.union "X64EncodingExpectation" "ResolutionErrorContaining" [J.string value]
let x64Test (value:X86_64EncodingFormat.x64EncodingTest)=J.record "X64EncodingTest" ["Name",J.string value.X86_64EncodingFormat.name;"Instructions",list ISA.x64Instr value.X86_64EncodingFormat.instructions;"Expectation",x64Expectation value.X86_64EncodingFormat.expectation;"SourceFile",J.string value.X86_64EncodingFormat.sourceFile]
let armExpectation=function ARM64EncodingFormat.EncodesTo values->J.union "ARM64EncodingExpectation" "EncodesTo" [list uint32 values]|ARM64EncodingFormat.EncodingErrorContaining value->J.union "ARM64EncodingExpectation" "EncodingErrorContaining" [J.string value]
let armTest (value:ARM64EncodingFormat.arm64EncodingTest)=J.record "ARM64EncodingTest" ["Name",J.string value.ARM64EncodingFormat.name;"Instructions",list ISA.armInstr value.ARM64EncodingFormat.instructions;"Expectation",armExpectation value.ARM64EncodingFormat.expectation;"AssertDifferent",`Bool value.ARM64EncodingFormat.assertDifferent]
let x64Runs value=list (fun value->tuple [x64Test value;outcome (X86_64EncodingTestRunner.runX64EncodingTest value)]) [value;{value with X86_64EncodingFormat.expectation=X86_64EncodingFormat.ResolvesTo (Some (Bytes.of_string "mismatch"),["wrong";"a";"b";"c";"d"])};{value with X86_64EncodingFormat.expectation=X86_64EncodingFormat.ResolvesTo (None,["wrong";"a";"b";"c";"d"])};{value with X86_64EncodingFormat.expectation=X86_64EncodingFormat.ResolutionErrorContaining "mismatch"}]
let armRuns value=let wrong=match value.ARM64EncodingFormat.expectation with ARM64EncodingFormat.EncodesTo values->ARM64EncodingFormat.EncodesTo (List.map (fun value->Int32.logxor value 1l) values)|ARM64EncodingFormat.EncodingErrorContaining _->ARM64EncodingFormat.EncodingErrorContaining "mismatch" in list (fun value->tuple [armTest value;outcome (ARM64EncodingTestRunner.runARM64EncodingTest value)]) [value;{value with ARM64EncodingFormat.expectation=wrong};{value with ARM64EncodingFormat.expectation=ARM64EncodingFormat.EncodingErrorContaining "mismatch"}]
let parsed path content=result (list (fun value->tuple [x64Test value;x64Runs value])) (X86_64EncodingFormat.parseX64EncodingFileContent path content)
let tests values=list (fun (name,run)->let actual=run () in tuple [J.string name;result (fun ()->`Null) actual]) values
let observe source=
 let open Yojson.Basic.Util in let fixtures=Yojson.Basic.from_file "scripts/ocaml/encoding_fixtures.json" in
 let file="src/Tests/passes/x64enc/encoding.x64enc" in let paths=["missing.x64enc";"src/Tests/passes/x64enc";file] in
 let armFiles=Sys.readdir "src/Tests/passes/arm64enc" |> Array.to_list |> List.filter (fun file->Filename.check_suffix file ".arm64enc") |> List.sort StringOrder.compare |> List.map (Filename.concat "src/Tests/passes/arm64enc") in
 let mismatches=[0,ARM64.RET,0l,-1l;1,ARM64.MOVZ (ARM64.X0,1,0),Int32.min_int,Int32.max_int] in
 let display=result (fun values->tuple [list (fun count->J.string (EncodingDSLTests.displayCases (List.filteri (fun index _->index<count) values))) [0;1;2;3;4;5;32];list (fun value->J.string (EncodingDSLTests.displayCases [value])) values]) (X86_64EncodingTestRunner.loadX64EncodingTests file) in
 tuple [result (list ISA.x64Instr) (X86_64Parser.parseX64 source);list (fun value->result (list ISA.x64Instr) (X86_64Parser.parseX64 (to_string value))) (fixtures |> member "parser" |> to_list);parsed source source;list (fun value->parsed source (to_string value)) (fixtures |> member "format" |> to_list);parsed file (HostFile.readText file);list (fun path->result (list x64Test) (X86_64EncodingTestRunner.loadX64EncodingTests path)) paths;tests (X86_64EncodingTestRunner.tests (Array.of_list (List.rev paths)));tests EncodingDSLTests.tests;list (fun path->result (fun value->tuple [armTest value;armRuns value]) (ARM64EncodingTestRunner.loadARM64EncodingTest path)) (armFiles@["missing.arm64enc";"src/Tests/passes/arm64enc"]);J.string (ARM64EncodingTestRunner.formatMismatches mismatches);J.string (ARM64EncodingTestRunner.formatMismatches []);list (fun values->`Bool (ARM64EncodingTestRunner.hasAllDifferent values)) [[];[0l];[0l;1l];[0l;1l;0l];[Int32.min_int;Int32.max_int;-1l]];display]
