(*
   ARM64CodeGenTests.ml - Register ARM64 lowering and runtime contract tests.
*)
let tests=[
 "LIR ARM64 codegen reports missing entry block",ControlFlowTests.testReportsMissingEntryBlock;
 "Generated ARM64 code eliminates self-moves",AllocationTests.testGeneratedCodeEliminatesSelfMoves;
 "ARM64 compact record fields start at offset zero",ReleasePlanningTests.testCompactRecordFieldsStartAtOffsetZero;
 "Generated ARM64 entry uses allocator transfers only",ControlFlowTests.testGeneratedEntryUsesAllocatorTransfersOnly;
 "ARM64 Sleep normalizes timeout and retries nanosleep",AllocationTests.testSleepUsesNormalizedInterruptSafeNanosleep;
 "ARM64 CLI host operations use target kernel ABIs",AllocationTests.testCliHostOperationsUseTargetKernelABIs;
 "ARM64 list retain helper clears tag with immediate mask",AllocationTests.testListRetainHelperClearsTagWithImmediateMask;
 "ARM64 dictionary retain helper clears tag with immediate mask",AllocationTests.testDictRetainHelperClearsTagWithImmediateMask;
 "ARM64 dictionary release helper clears tag with immediate mask",AllocationTests.testDictReleaseHelperClearsTagWithImmediateMask;
 "ARM64 dictionary release helper clears child tag with immediate mask",AllocationTests.testDictReleaseHelperClearsChildTagWithImmediateMask;
 "ARM64 dictionary helpers use constant-time bitmap popcount",AllocationTests.testDictHelpersUseConstantTimeBitmapPopcount;
 "ARM64 list release helper clears tag with immediate mask",AllocationTests.testListReleaseHelperClearsTagWithImmediateMask;
 "ARM64 list release helper clears child tag with immediate mask",AllocationTests.testListReleaseHelperClearsChildTagWithImmediateMask;
 "ARM64 peephole fuses bit-clear sequence",AllocationTests.testPeepholeFusesBitClearSequence;
 "ARM64 peephole falls through to true branch target",AllocationTests.testPeepholeFallsThroughToTrueTarget;
 "ARM64 peephole combines operands and memory pairs",AllocationTests.testPeepholeCombinesOperandsAndMemoryPairs;
 "ARM64 peephole combines every extension and Float store pairs",AllocationTests.testPeepholeCombinesEveryExtensionAndFloatStorePairs;
 "ARM64 peephole combines shifted subtraction",AllocationTests.testPeepholeCombinesShiftedSubtraction;
 "ARM64 peephole preserves shared-source shift fusion across branch",AllocationTests.testPeepholePreservesSharedSourceShiftFusionAcrossBranch;
 "ARM64 UInt64 runtime zero branches target digit handlers",ControlFlowTests.testPrintUInt64RuntimeZeroBranches;
 "ARM64 UInt64 runtime preserves trailing newline",ControlFlowTests.testPrintUInt64RuntimePreservesNewline;
 "ARM64 branch false edge falls through",ControlFlowTests.testBranchFalseEdgeFallsThrough;
 "ARM64 common-return transfer cost",ControlFlowTests.testSharedReturnTransferCost;
 "ARM64 dynamic buffer RC instruction cost",ControlFlowTests.testDynamicBufferRcInstructionCost;
 "ARM64 primitive list payload preservation cost",ControlFlowTests.testPrimitiveListPayloadPreservationCost;
 "ARM64 FLoad encodable constants use immediate",AllocationTests.testArm64FLoadEncodableConstantsUseImmediate;
 "RawAlloc uses shared heap overflow path",AllocationTests.testRawAllocUsesSharedHeapOverflowPath;
 "Runtime print string length uses full immediate",AllocationTests.testRuntimePrintStringLengthUsesFullImmediate;
 "RawSlotInit pure enum skips generic retain",AllocationTests.testRawSlotInitPureEnumDoesNotEmitGenericRetain;
 "Small generic release plan remains inline",ReleasePlanningTests.testSmallGenericReleasePlanRemainsInline;
 "Expensive generic release is prepared as a call",ReleasePlanningTests.testExpensiveGenericReleaseIsPreparedAsCall;
 "Generic release helper preserves cached instructions",ReleasePlanningTests.testGenericReleaseHelperPreservesCachedInstructions;
 "Outlined generic release uses allocator liveness",ReleasePlanningTests.testOutlinedGenericReleaseUsesAllocatorLiveness;
 "Generic release helpers preserve ownership policy",ReleasePlanningTests.testGenericReleaseHelpersPreserveOwnershipPolicy;
 "List tuple3 bytes/list/dict-list uses typed dict helper",AllocationTests.testListTuple3BytesListDictListValueUsesTypedDictHelper;
 "List tuple3 string/list/dict-list uses typed dict helper",AllocationTests.testListTuple3StringListDictListValueUsesTypedDictHelper;
 "List tuple3 closure/list/dict-list uses typed dict helper",AllocationTests.testListTuple3ClosureListDictListValueUsesTypedDictHelper;
 "List tuple4 string/bytes/list/dict-list uses typed dict helper",AllocationTests.testListTuple4StringBytesListDictListValueUsesTypedDictHelper;
 "List tuple4 closure/string/list/dict-list uses typed dict helper",AllocationTests.testListTuple4ClosureStringListDictListValueUsesTypedDictHelper;
 "List tuple4 closure/bytes/list/dict-list uses typed dict helper",AllocationTests.testListTuple4ClosureBytesListDictListValueUsesTypedDictHelper;
 "List dict-list uses typed dict helper",AllocationTests.testListDictListValueUsesTypedDictHelper;
 "List dict-string payload uses planned dict helper",AllocationTests.testListDictStringPayloadUsesPlannedDictHelper;
 "List nested tuple dict-list uses typed dict helper",AllocationTests.testListNestedTupleDictListValueUsesTypedDictHelper;
 "List tuple2 nested tuple dict-list uses typed dict helper",AllocationTests.testListTuple2NestedTupleDictListValueUsesTypedDictHelper;
 "List tuple4 nested tuple dynamic dict-list uses typed dict helper",AllocationTests.testListTuple4NestedTupleDynamicDictListValueUsesTypedDictHelper;
 "List tuple4 nested record middle dict-list uses typed dict helper",AllocationTests.testListTuple4NestedRecordMiddleDictListValueUsesTypedDictHelper;
 "List tuple4 nested tuple closure dict-list uses typed dict helper",AllocationTests.testListTuple4NestedTupleClosureDictListValueUsesTypedDictHelper;
 "List sum tuple3 dict-list uses typed dict helper",AllocationTests.testListSumTuple3DictListValueUsesTypedDictHelper;
 "List sum tuple4 dict-list uses typed dict helper",AllocationTests.testListSumTuple4DictListValueUsesTypedDictHelper;
 "List sum tuple3 closure dict-list uses typed dict helper",AllocationTests.testListSumTuple3ClosureDictListValueUsesTypedDictHelper;
 "List sum tuple4 closure dict-list uses typed dict helper",AllocationTests.testListSumTuple4ClosureDictListValueUsesTypedDictHelper;
 "List sum tuple4 closure string dict-list uses typed dict helper",AllocationTests.testListSumTuple4ClosureStringDictListValueUsesTypedDictHelper;
 "Dict dict-list uses planned dict helper",AllocationTests.testDictDictListValueUsesPlannedDictHelper;
 "Dict string key uses planned dict helper",AllocationTests.testDictStringKeyUsesPlannedDictHelper;
 "Dict string value uses planned dict helper",AllocationTests.testDictStringValueUsesPlannedDictHelper;
 "Dict string key list value uses planned dict helper",AllocationTests.testDictStringKeyListValueUsesPlannedDictHelper;
 "Dict string key tuple value uses planned dict helper",AllocationTests.testDictStringKeyTupleValueUsesPlannedDictHelper;
 "Dict string key/value planned helper releases collision payloads",AllocationTests.testDictStringKeyValuePlannedHelperReleasesCollisionPayloads;
 "Dict list value planned helper releases collision payloads",DestructionTests.testDictListValuePlannedHelperReleasesCollisionPayloads;
 "Dict tuple value planned helper releases collision payloads",DestructionTests.testDictTupleValuePlannedHelperReleasesCollisionPayloads;
 "Dict string key tuple value planned helper releases collision payloads",DestructionTests.testDictStringKeyTupleValuePlannedHelperReleasesCollisionPayloads;
 "Generic fixed-block nested bytes field uses release plan",DestructionTests.testGenericFixedBlockNestedBytesFieldUsesReleasePlan;
 "Planned list generic leaf release reloads block pointer",DestructionTests.testPlannedListGenericLeafReleaseReloadsBlockPointer;
 "Planned list nested generic release preserves block pointer",DestructionTests.testPlannedListNestedGenericReleasePreservesBlockPointer;
 "Planned list tuple payload uses planned helper",DestructionTests.testPlannedListTuplePayloadUsesPlannedHelper;
 "Planned list record payload uses planned helper",DestructionTests.testPlannedListRecordPayloadUsesPlannedHelper;
 "Planned list record nested string-dict uses planned list helper",DestructionTests.testPlannedListRecordNestedStringDictUsesPlannedListHelper;
 "Planned list tuple5 payload uses planned helper",DestructionTests.testPlannedListTuple5PayloadUsesPlannedHelper;
 "Planned list record5 payload uses planned helper",DestructionTests.testPlannedListRecord5PayloadUsesPlannedHelper;
 "Generic fixed-block nested immediate field releases child root",DestructionTests.testGenericFixedBlockNestedImmediateFieldReleasesChildRoot;
 "Generic fixed-block nested mixed boxed-sum bytes payload uses variant dispatch",DestructionTests.testGenericFixedBlockNestedMixedBoxedSumBytesPayloadUsesVariantDispatch;
 "Generic mixed boxed-sum payload dispatch skips remaining cases",DestructionTests.testGenericMixedBoxedSumPayloadDispatchSkipsRemainingCases;
 "Recursive-sum release skips variants without managed fields",DestructionTests.testRecursiveSumReleaseSkipsVariantWithoutManagedFields;
 "Closure capture nested fixed-block bytes field uses release plan",DestructionTests.testClosureCaptureNestedFixedBlockBytesFieldUsesReleasePlan;
 "Closure capture boxed-sum bytes payload uses release plan",DestructionTests.testClosureCaptureBoxedSumBytesPayloadUsesReleasePlan;
 "ARM64 codegen rejects unprepared facts",PlanningBoundaryTests.testRejectsUnpreparedCodegenFacts;
 "ARM64 codegen attributes LIR opcode expansion",PlanningBoundaryTests.testLirOpExpansionRecorderAttributesGeneratedInstructions;
]
