(* All LIR instructions with independently varied direct register roles. *)
open Dark_compiler
let instructions source regs fregs operand typ =
 let freg=fregs.(0) in
 [LIR.Mov ((regs.(0)), (operand));
LIR.Phi ((regs.(0)), [((operand), (LIR.Label source)); ((operand), (LIR.Label source))], (Some ((typ))));
LIR.Store ((3), (regs.(0)));
LIR.Add ((regs.(0)), (regs.(1)), (operand));
LIR.Sub ((regs.(0)), (regs.(1)), (operand));
LIR.Mul ((regs.(0)), (regs.(1)), (regs.(2)));
LIR.Sdiv ((regs.(0)), (regs.(1)), (regs.(2)));
LIR.Udiv ((regs.(0)), (regs.(1)), (regs.(2)));
LIR.Msub ((regs.(0)), (regs.(1)), (regs.(2)), (regs.(3)));
LIR.Madd ((regs.(0)), (regs.(1)), (regs.(2)), (regs.(3)));
LIR.Cmp ((regs.(0)), (operand));
LIR.Cset ((regs.(0)), LIR.EQ);
LIR.Select ((regs.(0)), (regs.(1)), (regs.(2)), LIR.EQ);
LIR.And ((regs.(0)), (regs.(1)), (regs.(2)));
LIR.And_imm ((regs.(0)), (regs.(1)), (-3L));
LIR.Orr ((regs.(0)), (regs.(1)), (regs.(2)));
LIR.Eor ((regs.(0)), (regs.(1)), (regs.(2)));
LIR.Lsl ((regs.(0)), (regs.(1)), (regs.(2)));
LIR.Lsr ((regs.(0)), (regs.(1)), (regs.(2)));
LIR.Asr ((regs.(0)), (regs.(1)), (regs.(2)));
LIR.Lsl_imm ((regs.(0)), (regs.(1)), (3));
LIR.Lsr_imm ((regs.(0)), (regs.(1)), (3));
LIR.Asr_imm ((regs.(0)), (regs.(1)), (3));
LIR.Neg ((regs.(0)), (regs.(1)));
LIR.Mvn ((regs.(0)), (regs.(1)));
LIR.Sxtb ((regs.(0)), (regs.(1)));
LIR.Sxth ((regs.(0)), (regs.(1)));
LIR.Sxtw ((regs.(0)), (regs.(1)));
LIR.Uxtb ((regs.(0)), (regs.(1)));
LIR.Uxth ((regs.(0)), (regs.(1)));
LIR.Uxtw ((regs.(0)), (regs.(1)));
LIR.Call ((regs.(0)), (AST.functionId (-1L)), [(operand); (operand)]);
LIR.TailCall ((AST.functionId (-1L)), [(operand); (operand)]);
LIR.IndirectCall ((regs.(0)), (regs.(1)), [(operand); (operand)]);
LIR.IndirectTailCall ((regs.(0)), [(operand); (operand)]);
LIR.ClosureAlloc ((regs.(0)), (AST.functionId (-1L)), [(operand); (operand)]);
LIR.ClosureCall ((regs.(0)), (regs.(1)), [(operand); (operand)]);
LIR.ClosureTailCall ((regs.(0)), [(operand); (operand)]);
LIR.SaveRegs ([LIR.X0; LIR.X0], [LIR.D0; LIR.D0]);
LIR.RestoreRegs ([LIR.X0; LIR.X0], [LIR.D0; LIR.D0]);
LIR.ArgMoves ([(LIR.X0, (operand)); (LIR.X0, (operand))]);
LIR.TailArgMoves ([(LIR.X0, (operand)); (LIR.X0, (operand))]);
LIR.FArgMoves ([(LIR.D0, (freg)); (LIR.D0, (freg))]);
LIR.PrintInt64 ((regs.(0)));
LIR.PrintUInt64 ((regs.(0)));
LIR.PrintBool ((regs.(0)));
LIR.PrintInt64NoNewline ((regs.(0)));
LIR.PrintUInt64NoNewline ((regs.(0)));
LIR.PrintBoolNoNewline ((regs.(0)));
LIR.PrintFloat ((fregs.(0)));
LIR.PrintFloatNoNewline ((fregs.(0)));
LIR.PrintString ((source));
LIR.StdoutWrite ((3), (operand), (true));
LIR.StdinReadLine ((3), (regs.(0)));
LIR.RuntimeError ((source));
LIR.RuntimeErrorString ((regs.(0)));
LIR.PrintHeapStringNoNewline ((regs.(0)));
LIR.PrintChars ([0;127;255]);
LIR.PrintBlob ((regs.(0)));
LIR.PrintList ((regs.(0)), (typ));
LIR.PrintSum ((regs.(0)), [((source), (3), (Some ((typ)))); ((source), (3), (Some ((typ))))], (true));
LIR.PrintRecord ((regs.(0)), (source), [((source), (typ)); ((source), (typ))]);
LIR.Exit;
LIR.FPhi ((fregs.(0)), [((freg), (LIR.Label source)); ((freg), (LIR.Label source))]);
LIR.FMov ((fregs.(0)), (fregs.(1)));
LIR.FLoad ((fregs.(0)), (-0.0));
LIR.FSpillLoad ((fregs.(0)), (3));
LIR.FSpillStore ((3), (fregs.(0)));
LIR.FAdd ((fregs.(0)), (fregs.(1)), (fregs.(2)));
LIR.FSub ((fregs.(0)), (fregs.(1)), (fregs.(2)));
LIR.FMul ((fregs.(0)), (fregs.(1)), (fregs.(2)));
LIR.FMadd ((fregs.(0)), (fregs.(1)), (fregs.(2)), (fregs.(3)));
LIR.FDiv ((fregs.(0)), (fregs.(1)), (fregs.(2)));
LIR.FNeg ((fregs.(0)), (fregs.(1)));
LIR.FAbs ((fregs.(0)), (fregs.(1)));
LIR.FSqrt ((fregs.(0)), (fregs.(1)));
LIR.FCmp ((fregs.(0)), (fregs.(1)));
LIR.Int64ToFloat ((fregs.(0)), (regs.(0)));
LIR.FloatToInt64 ((regs.(0)), (fregs.(0)));
LIR.FloatToBits ((regs.(0)), (fregs.(0)));
LIR.GpToFp ((fregs.(0)), (regs.(0)));
LIR.FpToGp ((regs.(0)), (fregs.(0)));
LIR.HeapAlloc ((regs.(0)), (3));
LIR.HeapStore ((regs.(0)), (3), (operand), (Some ((typ))));
LIR.HeapLoad ((regs.(0)), (regs.(1)), (3));
LIR.RefCountInc ((regs.(0)), (3), LIR.GenericHeap, (Some (({MemoryModel.releasePlanCacheKey=Some source;releasePlan=Some (MemoryModel.RecursiveRelease (AST.TList AST.TString));sourceType=Some AST.TString}))));
LIR.RefCountDec ((regs.(0)), (3), LIR.GenericHeap, (Some (({MemoryModel.releasePlanCacheKey=Some source;releasePlan=Some (MemoryModel.RecursiveRelease (AST.TList AST.TString));sourceType=Some AST.TString}))));
LIR.StringConcat ((regs.(0)), (operand), (operand), [(operand); (operand)]);
LIR.CanonicalBufferEq ((regs.(0)), (MemoryModel.NullableGraphemeCluster), (operand), (operand));
LIR.PrintHeapString ((regs.(0)));
LIR.LoadFuncAddr ((regs.(0)), (AST.functionId (-1L)));
LIR.FileReadBlob ((regs.(0)), (operand));
LIR.FileExists ((regs.(0)), (operand));
LIR.FileWriteBlob ((regs.(0)), (operand), (operand));
LIR.FileAppendText ((regs.(0)), (operand), (operand));
LIR.FileDelete ((regs.(0)), (operand));
LIR.FileCreateDirectory ((regs.(0)), (operand));
LIR.FileSetExecutable ((regs.(0)), (operand));
LIR.FileWriteFromPtr ((regs.(0)), (operand), (regs.(1)), (regs.(2)));
LIR.RawAlloc ((regs.(0)), (regs.(1)));
LIR.MappedAlloc ((regs.(0)), (regs.(1)));
LIR.RawFree ((regs.(0)));
LIR.MappedFree ((regs.(0)));
LIR.RawGet ((regs.(0)), (regs.(1)), (regs.(2)));
LIR.RawGetByte ((regs.(0)), (regs.(1)), (regs.(2)));
LIR.RawWriteWord ((regs.(0)), (regs.(1)), (regs.(2)));
LIR.RawWriteByte ((regs.(0)), (regs.(1)), (regs.(2)));
LIR.RawSlotInit ((regs.(0)), (regs.(1)), (regs.(2)), (typ));
LIR.RefCountIncString ((operand));
LIR.RefCountDecString ((operand));
LIR.RefCountIncBlob ((operand));
LIR.RefCountDecBlob ((operand));
LIR.RefCountIncInt ((operand));
LIR.RefCountDecInt ((operand));
LIR.RandomInt64 ((regs.(0)));
LIR.DateTimeNow ((regs.(0)));
LIR.Sleep ((3), (fregs.(0)));
LIR.CliNative ((regs.(0)), LIR.Execute, [(operand); (operand)]);
LIR.FloatToString ((regs.(0)), (fregs.(0)));
LIR.CoverageHit ((3))]
