(* All source ANF operation constructors, parameterized by their atom and type. *)
open Dark_compiler
let operations source atom typ : ANF.cExpr list = [(ANF.Atom ((atom)));
(ANF.TypedAtom ((atom), (typ)));
(ANF.Prim ((ANF.Add), (atom), (atom)));
(ANF.UnaryPrim ((ANF.Neg), (atom)));
(ANF.IfValue ((atom), (atom), (atom)));
(ANF.Call ((AST.functionId 7L), [(atom); (atom)]));
(ANF.BorrowedCall ((AST.functionId 7L), [(atom); (atom)]));
(ANF.TailCall ((AST.functionId 7L), [(atom); (atom)]));
(ANF.IndirectCall ((atom), [(atom); (atom)]));
(ANF.IndirectTailCall ((atom), [(atom); (atom)]));
(ANF.ClosureAlloc ((AST.functionId 7L), [(atom); (atom)]));
(ANF.ClosureCall ((atom), [(atom); (atom)]));
(ANF.ClosureTailCall ((atom), [(atom); (atom)]));
(ANF.TupleAlloc ([(atom); (atom)]));
(ANF.TupleGet ((atom), (3)));
(ANF.RecordAlloc (({ANF.sourceTypeName = (source); ANF.runtimeTypeName = (source); ANF.typeArgs = [(typ); (typ)]; ANF.fields = [((source), (typ)); ((source), (typ))]; ANF.valueType = (typ)} : ANF.recordDescriptor), [(atom); (atom)]));
(ANF.RecordGet (({ANF.sourceTypeName = (source); ANF.runtimeTypeName = (source); ANF.typeArgs = [(typ); (typ)]; ANF.fields = [((source), (typ)); ((source), (typ))]; ANF.valueType = (typ)} : ANF.recordDescriptor), (atom), (3)));
(ANF.RecordClone (({ANF.sourceTypeName = (source); ANF.runtimeTypeName = (source); ANF.typeArgs = [(typ); (typ)]; ANF.fields = [((source), (typ)); ((source), (typ))]; ANF.valueType = (typ)} : ANF.recordDescriptor), (atom), [(atom); (atom)]));
(ANF.RecordReuse (({ANF.sourceTypeName = (source); ANF.runtimeTypeName = (source); ANF.typeArgs = [(typ); (typ)]; ANF.fields = [((source), (typ)); ((source), (typ))]; ANF.valueType = (typ)} : ANF.recordDescriptor), ({ANF.sourceTypeName = (source); ANF.runtimeTypeName = (source); ANF.typeArgs = [(typ); (typ)]; ANF.fields = [((source), (typ)); ((source), (typ))]; ANF.valueType = (typ)} : ANF.recordDescriptor), (atom), [(atom); (atom)]));
(ANF.StringConcat ((atom), (atom), [(atom); (atom)]));
(ANF.CanonicalBufferEq ((MemoryModel.Utf8String), (atom), (atom)));
(ANF.RefCountInc ((atom), (3), (MemoryModel.GenericHeap), (Some (({MemoryModel.releasePlanCacheKey = (Some ((source))); MemoryModel.releasePlan = (Some ((MemoryModel.NoReleasePlan))); MemoryModel.sourceType = (Some ((typ)))} : MemoryModel.rcMetadata)))));
(ANF.RefCountDec ((atom), (3), (MemoryModel.GenericHeap), (Some (({MemoryModel.releasePlanCacheKey = (Some ((source))); MemoryModel.releasePlan = (Some ((MemoryModel.NoReleasePlan))); MemoryModel.sourceType = (Some ((typ)))} : MemoryModel.rcMetadata)))));
(ANF.Print ((atom), (typ)));
(ANF.StdoutWrite ((atom), (true)));
(ANF.StdinReadLine);
(ANF.RuntimeError ((source)));
(ANF.RuntimeErrorString ((atom)));
(ANF.FileReadBlob ((atom)));
(ANF.FileExists ((atom)));
(ANF.FileWriteBlob ((atom), (atom)));
(ANF.FileAppendText ((atom), (atom)));
(ANF.FileDelete ((atom)));
(ANF.FileCreateDirectory ((atom)));
(ANF.FileSetExecutable ((atom)));
(ANF.FileWriteFromPtr ((atom), (atom), (atom)));
(ANF.FloatSqrt ((atom)));
(ANF.FloatAbs ((atom)));
(ANF.FloatNeg ((atom)));
(ANF.Int64ToFloat ((atom)));
(ANF.FloatToInt64 ((atom)));
(ANF.FloatToBits ((atom)));
(ANF.RawAlloc ((atom)));
(ANF.MappedAlloc ((atom)));
(ANF.RawFree ((atom)));
(ANF.MappedFree ((atom)));
(ANF.RawGet ((atom), (atom), (Some ((typ)))));
(ANF.RawTake ((atom), (atom), (Some ((typ)))));
(ANF.RawGetByte ((atom), (atom)));
(ANF.RawWriteWord ((atom), (atom), (atom)));
(ANF.RawWriteByte ((atom), (atom), (atom)));
(ANF.RawSlotInit ((atom), (atom), (atom), (typ)));
(ANF.StringToRawPtr ((atom)));
(ANF.RawPtrToString ((atom)));
(ANF.BlobToRawPtr ((atom)));
(ANF.RawPtrToBlob ((atom)));
(ANF.RawPtrToInt128 ((atom)));
(ANF.RawPtrToUInt128 ((atom)));
(ANF.DictToRawPtr ((atom)));
(ANF.RawPtrToDict ((atom), (atom), (typ)));
(ANF.ListToRawPtr ((atom)));
(ANF.FixedBlockToRawPtr ((atom)));
(ANF.RawPtrToList ((atom), (atom), (typ)));
(ANF.RefCountIncString ((atom)));
(ANF.RefCountDecString ((atom)));
(ANF.RefCountIncBlob ((atom)));
(ANF.RefCountDecBlob ((atom)));
(ANF.RefCountIncInt ((atom)));
(ANF.RefCountDecInt ((atom)));
(ANF.RandomInt64);
(ANF.DateTimeNow);
(ANF.Sleep ((atom)));
(ANF.CliNative ((ANF.Execute), [(atom); (atom)]));
(ANF.FloatToString ((atom)))]
