(* Complete allocation, raw access, stack/heap stores and ownership selections. *)
open Dark_compiler
module E=ARM64EmitMemory
module C=ARM64CodeGenTypes
module J=MachineISAObservation
let tuple xs=`Assoc ["tuple",`List xs]
let list f xs=`List (List.map f xs)
let call f=try tuple [`Bool false; (match f () with Ok xs -> SemanticJson.union "FSharpResult" "Ok" [`List (List.map J.symInstr xs)] | Error error -> SemanticJson.union "FSharpResult" "Error" [SemanticJson.string error])] with Failure _ | Invalid_argument _ -> tuple [`Bool true]
let physical=[LIR.X0;LIR.X1;LIR.X2;LIR.X3;LIR.X4;LIR.X5;LIR.X6;LIR.X7;LIR.X8;LIR.X9;LIR.X10;LIR.X11;LIR.X12;LIR.X13;LIR.X14;LIR.X15;LIR.X16;LIR.X17;LIR.X19;LIR.X20;LIR.X21;LIR.X22;LIR.X23;LIR.X24;LIR.X25;LIR.X26;LIR.X27;LIR.X29;LIR.X30;LIR.SP]
let observe source=
 let target=ARM64.targetConfigFor Platform.LinuxARM64 in
 let ctx={ (ARMPrintingObservation.context source target false) with C.functionNames=FunctionIdMap.ofList [AST.functionId 0L,source;AST.functionId (-1L),"largest"];C.recordRegistry=StringOrder.Map.of_list ["R",["a",AST.TInt64;"b",AST.TString];"Rec",["next",AST.TRecord ("Rec",[])]];C.sumShapeRegistry=StringOrder.Map.of_list ["S",{MemoryModel.typeParams=[];MemoryModel.payloads=[0,None;1,Some AST.TString];MemoryModel.unaryPayloadTags=MemoryModel.IntSet.singleton 1}] } in
 let gps=List.map (fun p -> LIR.Physical p) physical@List.map (fun n -> LIR.Virtual n) [-1;0;2147483647] in
 let selected=List.map (fun p -> LIR.Physical p) [LIR.X0;LIR.X9;LIR.X12;LIR.X13;LIR.X14;LIR.X15;LIR.X19;LIR.SP]@[LIR.Virtual (-1)] in
 let sizes=[-2147483648;-65536;-32769;-32768;-4096;-1;0;1;7;8;9;16;248;255;256;4095;4096;32767;32768;65535;65536;2147483647] in
 let operands=List.map (fun reg -> LIR.Reg reg) gps@List.map (fun n -> LIR.StackSlot n) sizes@List.map (fun value -> LIR.Imm value) [Int64.min_int;-1L;0L;4096L;Int64.max_int]@[LIR.FloatImm 0.;LIR.FloatImm (-0.);LIR.FloatSymbol (Int64.float_of_bits 0xfff8000000000000L);LIR.FloatSymbol (Int64.float_of_bits 0x7ff8000000000001L);LIR.FloatSymbol (Int64.float_of_bits 0x7ff0000000000001L);LIR.FloatSymbol 0.1;LIR.StringSymbol source;LIR.StringSymbol "hé😀";LIR.StringSymbol (HostText.ofScalars [|0xfffd;0x61;0xfffd|]);LIR.FuncAddr (AST.functionId 0L);LIR.FuncAddr (AST.functionId 1L);LIR.FuncAddr (AST.functionId (-1L))] in
 let types=[AST.TInt8;AST.TInt16;AST.TInt32;AST.TInt64;AST.TInt128;AST.TInt;AST.TUInt8;AST.TUInt16;AST.TUInt32;AST.TUInt64;AST.TUInt128;AST.TBool;AST.TFloat64;AST.TString;AST.TBlob;AST.TChar;AST.TDateTime;AST.TUnit;AST.TNever;AST.TInternalRawPtr;AST.TVar source;AST.TInferenceVar (source,source);AST.TList AST.TString;AST.TStream AST.TString;AST.TDict (AST.TString,AST.TInt64);AST.TFunction ([AST.TInt64],AST.TBool);AST.TRecord ("R",[]);AST.TRecord ("missing",[]);AST.TRecord ("Rec",[]);AST.TSum ("S",[]);AST.TSum ("missing",[]);AST.TTuple [];AST.TTuple [AST.TInt64;AST.TString;AST.TList AST.TString]] in
 let allocations=list (fun enabled -> list (fun disabled -> let ctx={ctx with C.options={C.defaultOptions with C.enableLeakCheck=enabled;C.disableFreeList=disabled}} in tuple [list (fun dest -> list (fun size -> call (fun () -> E.emitHeapAlloc ctx dest size)) sizes) gps;list (fun dest -> list (fun size -> call (fun () -> E.emitRawAlloc ctx dest size)) [dest;LIR.Physical LIR.X14;LIR.Physical LIR.X15;LIR.Physical LIR.X19;LIR.Virtual (-1)]) gps;list (fun reg -> call (fun () -> E.emitRawFree ctx reg)) gps]) [false;true]) [false;true] in
 let mapped=list (fun target -> let ctx={ctx with C.target=target} in tuple [list (fun dest -> list (fun size -> call (fun () -> E.emitMappedAlloc ctx dest size)) gps) gps;list (fun reg -> call (fun () -> E.emitMappedFree ctx reg)) gps]) [target;ARM64.targetConfigFor Platform.MacOSARM64] in
 let heap=list (fun addr -> tuple [list (fun operand -> list (fun valueType -> call (fun () -> E.emitHeapStore ctx addr 0 operand valueType)) [None;Some AST.TFloat64;Some AST.TString]) operands;list (fun offset -> tuple [list (fun operand -> list (fun valueType -> call (fun () -> E.emitHeapStore ctx addr offset operand valueType)) [None;Some AST.TFloat64]) [LIR.Reg addr;LIR.Reg (LIR.Physical LIR.X9);LIR.Reg (LIR.Virtual (-1000));LIR.Imm Int64.min_int;LIR.StringSymbol source;LIR.FloatSymbol (Int64.float_of_bits 0xfff8000000000000L);LIR.FloatSymbol (Int64.float_of_bits 0x7ff8000000000001L);LIR.FloatSymbol (Int64.float_of_bits 0x7ff0000000000001L);LIR.StackSlot 0];list (fun dest -> call (fun () -> E.emitHeapLoad ctx dest addr offset)) gps]) sizes]) selected in
 let raw=list (fun a -> list (fun b -> list (fun c -> tuple [call (fun () -> E.emitRawGet ctx a b c);call (fun () -> E.emitRawGetByte ctx a b c);call (fun () -> E.emitRawWriteWord ctx a b c);call (fun () -> E.emitRawWriteByte ctx a b c)]) [a;b;LIR.Physical LIR.X14;LIR.Physical LIR.X15;LIR.Virtual (-1)]) gps) gps in
 let cold=list (fun value -> list (fun typ -> call (fun () -> E.emitRawSlotInit ctx (LIR.Physical LIR.X19) (LIR.Physical LIR.X20) value typ)) types) gps in
 let targets=[None;Some LIR.SlotInitListRootRetain;Some LIR.SlotInitDictRootRetain;Some LIR.SlotInitDynamicBufferRetain;Some LIR.SlotInitClosureRootRetain]@List.map (fun size -> Some (LIR.SlotInitGenericRootRetain size)) [-2147483648;-32769;-32768;-1;0;16;32767;32768;65535;2147483647] in
 let cached=list (fun retained -> let map=List.fold_left (fun map typ -> LIR.SemanticTypeMap.add typ retained map) LIR.SemanticTypeMap.empty types in let ctx={ctx with C.rawSlotInitRetainTargets=Some map} in list (fun value -> list (fun ptr -> list (fun offset -> list (fun typ -> call (fun () -> E.emitRawSlotInit ctx ptr offset value typ)) [AST.TInt;AST.TString;AST.TUnit]) [value;ptr;LIR.Physical LIR.X15]) [value;LIR.Physical LIR.X14;LIR.Physical LIR.X15]) selected) targets in
 let missing=let ctx={ctx with C.rawSlotInitRetainTargets=Some LIR.SemanticTypeMap.empty} in list (fun typ -> call (fun () -> E.emitRawSlotInit ctx (LIR.Physical LIR.X19) (LIR.Physical LIR.X20) (LIR.Physical LIR.X21) typ)) types in
 tuple [allocations;mapped;heap;raw;cold;cached;missing]
