(* Entire ARM64 operand, frame, checked allocation and codegen planning observations. *)
[@@@warning "-4"]
open Dark_compiler
module O=ARM64Operands
module F=ARM64Frames
module H=HeapAllocation
module C=ARM64CodeGenTypes
module J=MachineISAObservation
let tuple values=`Assoc ["tuple",`List values]
let list f xs=`List (List.map f xs)
let str=SemanticJson.string
let boolean b=`Bool b
let result f=function Ok value -> SemanticJson.union "FSharpResult" "Ok" [f value] | Error msg -> SemanticJson.union "FSharpResult" "Error" [str msg]
let internalCall f action=try tuple [boolean false;f (action ())] with Failure _ | Invalid_argument _ -> tuple [boolean true]
let symbolic=list J.symInstr
let observe source =
 let physical=[LIR.X0;LIR.X1;LIR.X2;LIR.X3;LIR.X4;LIR.X5;LIR.X6;LIR.X7;LIR.X8;LIR.X9;LIR.X10;LIR.X11;LIR.X12;LIR.X13;LIR.X14;LIR.X15;LIR.X16;LIR.X17;LIR.X19;LIR.X20;LIR.X21;LIR.X22;LIR.X23;LIR.X24;LIR.X25;LIR.X26;LIR.X27;LIR.X29;LIR.X30;LIR.SP] in
 let fps=[LIR.D0;LIR.D1;LIR.D2;LIR.D3;LIR.D4;LIR.D5;LIR.D6;LIR.D7;LIR.D8;LIR.D9;LIR.D10;LIR.D11;LIR.D12;LIR.D13;LIR.D14;LIR.D15] in
 let regs=[ARM64.X0;ARM64.X1;ARM64.X2;ARM64.X3;ARM64.X4;ARM64.X5;ARM64.X6;ARM64.X7;ARM64.X8;ARM64.X9;ARM64.X10;ARM64.X11;ARM64.X12;ARM64.X13;ARM64.X14;ARM64.X15;ARM64.X16;ARM64.X17;ARM64.X18;ARM64.X19;ARM64.X20;ARM64.X21;ARM64.X22;ARM64.X23;ARM64.X24;ARM64.X25;ARM64.X26;ARM64.X27;ARM64.X28;ARM64.X29;ARM64.X30;ARM64.SP] in
 let ids=[-2147483648;-2001;-2000;-1003;-1002;-1001;-1000;-14;-9;-8;-2;-1;0;1;7;8;9;20;9999;10000;10001;12001;Int32.to_int Int32.max_int] in
 let mappings=tuple [list (fun phys -> tuple [J.armReg (O.lirPhysRegToARM64Reg phys);result J.armReg (O.lirRegToARM64Reg (LIR.Physical phys));ProductionLIR.fReg (O.virtualToFVirtual (LIR.Physical phys))]) physical;list (fun fp -> J.armFReg (O.lirPhysFPRegToARM64FReg fp)) fps;list (fun id -> tuple [internalCall (result J.armFReg) (fun () -> O.lirFRegToARM64FReg (LIR.FVirtual id));result J.armReg (O.lirRegToARM64Reg (LIR.Virtual id));ProductionLIR.fReg (O.virtualToFVirtual (LIR.Virtual id))]) ids] in
 let words=[0;1;0x7fff;0x8000;0xfffe;0xffff] in
 let values=List.concat_map (fun a -> List.concat_map (fun b -> List.concat_map (fun c -> List.map (fun d -> Int64.logor (Int64.logor (Int64.shift_left (Int64.of_int a) 48) (Int64.shift_left (Int64.of_int b) 32)) (Int64.logor (Int64.shift_left (Int64.of_int c) 16) (Int64.of_int d))) words) words) words) words in
 let immediates=list (fun reg -> list (fun value -> symbolic (O.loadImmediate reg value)) values) regs in
 let offsets=List.init 8195 (fun n -> n-4097)@[-2147483648;2147483647;-65536;65535] in
 let stacks=list (fun reg -> list (fun offset -> tuple [result symbolic (O.loadStackSlot reg offset);result symbolic (O.storeStackSlot reg offset)]) offsets) regs in
 let operands=[LIR.Imm Int64.min_int;LIR.Imm 0L;LIR.Imm Int64.max_int;LIR.StringSymbol source;LIR.FloatImm (-0.);LIR.FloatSymbol nan;LIR.FuncAddr (AST.functionId (-1L))]@List.map (fun p -> LIR.Reg (LIR.Physical p)) physical@List.map (fun id -> LIR.Reg (LIR.Virtual id)) ids@List.map (fun offset -> LIR.StackSlot offset) [-4096;-4095;-257;-256;255;256;4095;4096;-2147483648] in
 let cli=list (fun reg -> list (fun operand -> result symbolic (O.loadCliOperand reg operand)) operands) regs in
 let saved=[]::List.map (fun p -> [p]) physical@[[LIR.X19;LIR.X20;LIR.X21];physical;List.rev physical;List.init 4097 (fun _ -> LIR.X19)] in
 let fsaved=[]::List.map (fun p -> [p]) fps@[[LIR.D8;LIR.D9;LIR.D10];fps;List.rev fps] in
 let saves=list (fun saved -> let instrs,offset=F.generateCalleeSavedSaves saved in tuple [symbolic instrs;SemanticJson.int32 offset;symbolic (F.generateCalleeSavedRestores saved);SemanticJson.int32 (F.calleeSavedStackSpace saved)]) saved in
 let floatSaves=list (fun saved -> tuple [SemanticJson.int32 (F.floatCalleeSavedStackSpace saved);list (fun offset -> tuple [symbolic (F.generateFloatCalleeSavedSaves saved offset);symbolic (F.generateFloatCalleeSavedRestores saved offset)]) [-2147483648;-32769;-32768;-1;0;8;16;32767;32768;65535;2147483647]]) fsaved in
 let frames=list (fun gp -> list (fun fp -> list (fun size -> tuple [symbolic (F.generatePrologue gp fp size);symbolic (F.generateEpilogue gp fp size)]) [-2147483648;-1;0;1;8;16;255;256;4095;4096;65535;65536;2147483647]) (List.filter (fun xs -> List.length xs<=16) fsaved)) (List.filter (fun xs -> List.length xs<=30) saved) in
 let literalValues=[source;"";"é";"😀";HostText.ofScalars [|0xfffd;0x61;0xfffd|]] in
 let labels=list (fun value -> tuple [J.symLabelRef (H.dataLabel value);J.symLabelRef (H.stringDataLabel value);J.symLabelRef (H.floatDataLabel (-0.));J.symLabelRef (H.codeLabel value);SemanticJson.int32 (H.utf8Len value);list (fun dest -> symbolic (H.loadStringLiteralPointer dest value)) regs]) literalValues in
 let allocations=list (fun target -> tuple [symbolic (H.generateRuntimeErrorHelper target);symbolic (H.preparedHeapOverflowTrapBody target);symbolic (H.generateHeapOverflowTrapBlock (H.preparedHeapOverflowTrapBody target) source);list (fun dest -> list (fun size -> symbolic (H.checkedBumpAllocReg source dest size)) regs) regs;symbolic (H.withHeapBoundsCheck source [Symbolic.Label source] [Symbolic.RET])]) [ARM64.targetConfigFor Platform.MacOSARM64;ARM64.targetConfigFor Platform.LinuxARM64] in
 let names=[source;"";"Darklang.Stdlib.Dict";"Darklang.Stdlib.Dict.x";"Darklang.Stdlib.X.x";"Darklang.Stdlib.";"Darklang.Stdlib\u{ad}.Dict.x";"Darklang.Stdlib.\u{ad}Dict.x";"Darklang.Stdlib.Di\u{ad}ct.x";"Darklang.Stdlib.\u{200d}Dict.x"] in
 let ownership=list (fun name -> boolean (C.callerOwnsSinglePayloadSum name)) names in
 let ctx : C.codeGenContext={C.target=ARM64.targetConfigFor Platform.LinuxARM64;options=C.defaultOptions;sumShapeRegistry=StringOrder.Map.empty;recordRegistry=StringOrder.Map.empty;rawSlotInitRetainTargets=None;closurePayloadSizes=StringOrder.Map.empty;closureCaptureTypes=StringOrder.Map.empty;functionNames=FunctionIdMap.ofList [AST.functionId 0L,source;AST.functionId (-1L),"largest"];functionName=source;instructionSite=source;stackSize=0;usedCalleeSaved=[];usedCalleeSavedF=[];heapOverflowLabel=source;recordLirOpExpansion=None} in
 let functionNames=list (fun id -> internalCall str (fun () -> C.functionName ctx (AST.functionId id))) [0L;1L;Int64.min_int;Int64.max_int;-1L] in
 let options=SemanticJson.record "CodeGenOptions" ["DisableFreeList",boolean C.defaultOptions.C.disableFreeList;"EnableCoverage",boolean C.defaultOptions.C.enableCoverage;"CoverageExprCount",SemanticJson.int32 C.defaultOptions.C.coverageExprCount;"EnableLeakCheck",boolean C.defaultOptions.C.enableLeakCheck] in
 let constants=tuple [str C.leakCounterLabel;str C.heapOutOfMemoryMessage;`Assoc ["kind",`String "int64";"value",`String (Int64.to_string C.heapMmapSizeBytes)];`Assoc ["kind",`String "uint16";"value",`String (string_of_int C.heapMmapSizeMovzImm16)];str C.heapOverflowLabelPrefix;str C.runtimeErrorHelperLabel;str C.listRefCountIncHelperLabel;str C.listRefCountDecHelperLabel;str C.plannedGenericRefCountDecHelperLabelPrefix;str C.listRefCountDecStringHelperLabel;str C.listRefCountDecBlobHelperLabel;str C.listRefCountDecListHelperLabel;str C.listRefCountDecDictHelperLabel;str C.listRefCountDecDictListHelperLabel;str C.listRefCountDecClosureHelperLabel;str C.dictRefCountIncHelperLabel;str C.dictRefCountDecHelperLabel;str C.dictRefCountDecListValueHelperLabel;str C.dictRefCountDecDictValueHelperLabel;str C.dictRefCountDecDictListValueHelperLabel;str C.dictRefCountDecTupleStringListValueHelperLabel;str C.dictRefCountDecTupleStringListDictValueHelperLabel;str C.dictRefCountDecSumStringValueHelperLabel;str C.closureRefCountIncHelperLabel;str C.closureRefCountDecHelperLabel;str C.streamRefCountDecHelperLabel] in
 let labelPlans=list (fun fingerprint -> tuple [str (C.plannedListDecHelperLabelForFingerprint fingerprint);str (C.plannedGenericDecHelperBaseLabelForFingerprint fingerprint);str (C.plannedDictDecHelperLabelForFingerprint fingerprint);list (fun owned -> str (C.specializePlannedGenericDecHelperLabel owned fingerprint)) [false;true]]) [source;"";"0123456789abcdef"] in
 let types=[AST.TInt8;AST.TInt16;AST.TInt32;AST.TInt64;AST.TInt128;AST.TInt;AST.TUInt8;AST.TUInt16;AST.TUInt32;AST.TUInt64;AST.TUInt128;AST.TBool;AST.TFloat64;AST.TString;AST.TBlob;AST.TChar;AST.TDateTime;AST.TUnit;AST.TNever;AST.TInternalRawPtr;AST.TVar source;AST.TInferenceVar (source,source);AST.TList AST.TString;AST.TList AST.TInt64;AST.TStream AST.TString;AST.TDict (AST.TString,AST.TList AST.TInt64);AST.TFunction ([AST.TInt64],AST.TBool);AST.TTuple [AST.TInt64;AST.TString];AST.TRecord ("R",[]);AST.TRecord ("N",[]);AST.TRecord ("G",[AST.TString]);AST.TRecord ("Unknown",[]);AST.TSum ("S",[]);AST.TSum ("Unknown",[])] in
 let records=StringOrder.Map.of_seq (List.to_seq ["R",["value",AST.TInt64;"str",AST.TString];"N",["next",AST.TRecord ("N",[])];"G",["x",AST.TVar "a"]]) in
 let sums=StringOrder.Map.singleton "S" {MemoryModel.typeParams=[];payloads=[0,None;1,Some AST.TString;2,Some (AST.TTuple [AST.TInt64;AST.TString])];unaryPayloadTags=MemoryModel.IntSet.of_list [1]} in
 let retain target=SemanticJson.union "Arm64SlotInitRootRetainTarget" (match target with LIR.SlotInitListRootRetain -> "SlotInitListRootRetain" | LIR.SlotInitDictRootRetain -> "SlotInitDictRootRetain" | LIR.SlotInitDynamicBufferRetain -> "SlotInitDynamicBufferRetain" | LIR.SlotInitClosureRootRetain -> "SlotInitClosureRootRetain" | LIR.SlotInitGenericRootRetain _ -> "SlotInitGenericRootRetain") (match target with LIR.SlotInitGenericRootRetain size -> [SemanticJson.int32 size] | _ -> []) in
 let optional f=function None -> SemanticJson.union "FSharpOption" "None" [] | Some value -> SemanticJson.union "FSharpOption" "Some" [f value] in
 let slotPlans=list (fun recordRegistry -> list (fun sumRegistry -> list (fun typ -> internalCall (optional retain) (fun () -> C.slotInitRootRetainTarget recordRegistry sumRegistry typ)) types) [StringOrder.Map.empty;sums]) [StringOrder.Map.empty;records] in
 let nominalLabels=list (fun typ -> str (C.recursiveNominalRefCountDecHelperLabel typ)) types in
 let releases=[MemoryModel.NoReleasePlan;MemoryModel.DynamicBufferRelease MemoryModel.DynamicStringBuffer;MemoryModel.DynamicBufferRelease MemoryModel.DynamicBlobBuffer;MemoryModel.DynamicBufferRelease MemoryModel.DynamicIntBuffer;MemoryModel.RecursiveRelease (AST.TRecord (source,[]))]@List.concat_map (fun count -> let fields=List.init count (fun n -> MemoryModel.FieldRelease (n*8,MemoryModel.DynamicBufferRelease MemoryModel.DynamicStringBuffer)) in [MemoryModel.RootRelease (count*8,MemoryModel.GenericHeap,MemoryModel.FixedBlockPayloadRelease (count*8,fields));MemoryModel.RootRelease (8,MemoryModel.ClosureHeap,MemoryModel.ClosurePayloadRelease fields);MemoryModel.RootRelease (16,MemoryModel.TaggedList,MemoryModel.TaggedListPayloadRelease (MemoryModel.RootRelease (count*8,MemoryModel.GenericHeap,MemoryModel.FixedBlockPayloadRelease (count*8,fields))));MemoryModel.RootRelease (24,MemoryModel.DictHeap,MemoryModel.DictPayloadRelease (MemoryModel.NoReleasePlan,MemoryModel.RootRelease (count*8,MemoryModel.GenericHeap,MemoryModel.FixedBlockPayloadRelease (count*8,fields))));MemoryModel.RootRelease (count*8,MemoryModel.GenericHeap,MemoryModel.BoxedSumPayloadRelease (count*8,fields,[{MemoryModel.tag=1;fieldReleases=fields}]))]) [0;1;2;4;8;16;17;32] in
 let releasePlans=list (fun plan -> tuple [boolean (C.genericReleasePlanIsExpensive plan);str (C.plannedListDecHelperLabelForReleasePlan plan);str (C.plannedDictDecHelperLabelForReleasePlan plan)]) releases in
 let variants : LIR.typeVariants={LIR.typeParams=[source];variants=[{LIR.name="c";tag=3;payload=Some AST.TInt64;fieldCount=1};{LIR.name="a";tag=1;payload=Some AST.TFloat64;fieldCount=2};{LIR.name="b";tag=1;payload=None;fieldCount=0};{LIR.name="z";tag=(-1);payload=Some AST.TBool;fieldCount=1}]} in
 let encodeSums registry=`Assoc ["map",list (fun (name,(info:MemoryModel.rcSumShapeInfo)) -> tuple [str name;SemanticJson.record "RcSumShapeInfo" ["TypeParams",list str info.MemoryModel.typeParams;"Payloads",list (fun (tag,payload) -> tuple [SemanticJson.int32 tag;optional SemanticAST.semanticType payload]) info.MemoryModel.payloads;"UnaryPayloadTags",`Assoc ["set",list SemanticJson.int32 (MemoryModel.IntSet.elements info.MemoryModel.unaryPayloadTags)]]]) (StringOrder.Map.bindings registry)] in
 let sumRegistries=list (fun registry -> encodeSums (C.rcSumShapeRegistryFromVariantRegistry registry)) [StringOrder.Map.empty;StringOrder.Map.singleton source variants;StringOrder.Map.of_seq (List.to_seq [source,variants;"A",variants])] in
 let planning=tuple [options;constants;functionNames;labelPlans;nominalLabels;slotPlans;releasePlans;sumRegistries] in
 tuple [mappings;immediates;stacks;cli;saves;floatSaves;frames;labels;allocations;ownership;planning]
