(* Observe canonical semantic syntax, precedence and declaration restoration. *)
open Dark_compiler
module A=AST
let tuple xs=`Assoc ["tuple",`List xs]
let list f xs=`List (List.map f xs)
let observe source=
 let ne=NonEmptyList.fromList in
 let print items=SemanticJson.string (ASTPrettyPrinter.formatProgram (A.Program items)) in
 let expr value=print [A.Expression ([],value)] in
 let operations=[A.Add;A.Sub;A.Mul;A.Div;A.Mod;A.Pow;A.Shl;A.Shr;A.BitAnd;A.BitOr;A.BitXor;A.StringConcat;A.Eq;A.Neq;A.Lt;A.Gt;A.Lte;A.Gte;A.And;A.Or] in
 let field={A.sourceFieldName=source;resolvedTypeName=None;resolvedFieldIndex=None} in
 let reference={A.sourceTypeName="M.R";resolvedTypeName="M.R";typeArgs=[A.TString]} in
 let literal=A.StringLiteral source in
 let constructor=A.UnresolvedConstructor (Some "M.Choice") in
 let negative=A.Int64Literal (-1L) in
 let fn=A.Var "Module.function" in
 let patterns=[A.PUnit;A.PWildcard;A.PVar source;A.PConstructor ("M.C",[]);A.PConstructor ("M.C",[A.PVar source]);A.PConstructor ("M.C",[A.PTuple [A.PVar "x";A.PUnit]]);A.PConstructor ("M.C",[A.PUnit;A.PWildcard]);A.PResolvedConstructor ("M.Choice","M.C",1,[]);A.PResolvedConstructor ("M.Choice","M.C",1,[A.PTuple []]);A.PResolvedConstructor ("M.Choice","M.C",1,[A.PUnit;A.PWildcard]);A.POr (ne [A.PWildcard;A.PUnit]);A.PInt64 Int64.min_int;A.PBigInt (Z.shift_left Z.one 128);A.PInt128Literal (Z.neg (Z.shift_left Z.one 127));A.PInt8Literal (-128);A.PInt16Literal (-32768);A.PInt32Literal Int32.min_int;A.PUInt8Literal 255;A.PUInt16Literal 65535;A.PUInt32Literal 4294967295L;A.PUInt64Literal (-1L);A.PUInt128Literal (Z.pred (Z.shift_left Z.one 128));A.PBool true;A.PBool false;A.PString source;A.PChar source;A.PFloat (-0.);A.PFloat 1.5;A.PTuple [A.PUnit;A.PVar source];A.PList [A.PUnit;A.PVar source];A.PListCons ([A.PListCons ([A.PVar "a"],A.PVar "b");A.PConstructor ("M.C",[A.PVar "x"])],A.PVar "tail");A.PListCons ([],A.PVar "tail")] in
 let letPatterns=[A.LPUnit;A.LPWildcard;A.LPVariable source;A.LPTuple (A.LPVariable source,A.LPWildcard,[A.LPUnit;A.LPTuple (A.LPVariable "a",A.LPVariable "b",[])])] in
 let types=[A.TInt8;A.TInt16;A.TInt32;A.TInt64;A.TInt128;A.TInt;A.TUInt8;A.TUInt16;A.TUInt32;A.TUInt64;A.TUInt128;A.TBool;A.TFloat64;A.TString;A.TBlob;A.TChar;A.TDateTime;A.TUnit;A.TNever;A.TInternalRawPtr;A.TVar source;A.TInferenceVar (source,"identity");A.TList A.TString;A.TStream A.TBool;A.TDict (A.TList A.TString,A.TFunction ([A.TInt64],A.TBool));A.TTuple [A.TFunction ([A.TInt64],A.TBool);A.TString];A.TTuple [];A.TRecord (source,[]);A.TRecord ("M.R",[A.TList A.TString]);A.TSum (source,[]);A.TSum ("M.S",[A.TString;A.TInt64]);A.TFunction ([A.TString;A.TFunction ([A.TInt64],A.TBool)],A.TFunction ([A.TUnit],A.TString));A.TFunction ([],A.TString)] in
 let numbers=[A.UnitLiteral;A.Int64Literal Int64.min_int;A.Int64Literal Int64.max_int;A.Int128Literal (Z.neg (Z.shift_left Z.one 127));A.BigIntLiteral (Z.shift_left Z.one 180);A.Int8Literal (-128);A.Int16Literal (-32768);A.Int32Literal Int32.min_int;A.UInt8Literal 255;A.UInt16Literal 65535;A.UInt32Literal 4294967295L;A.UInt64Literal (-1L);A.UInt128Literal (Z.pred (Z.shift_left Z.one 128));A.BoolLiteral true;A.BoolLiteral false;literal;A.CharLiteral source]@List.map (fun f->A.FloatLiteral f) [0.;-0.;1.;1.5;1e-6;1e-7;1e20;1e21;Float.max_float;Float.min_float;Int64.float_of_bits 1L;Int64.float_of_bits 0xfff8000000000000L;Float.infinity;Float.neg_infinity] in
 let parameter pattern annotation inferred={A.pattern;sourceAnnotation=annotation;inferredType=inferred} in
 let recursion={A.sourceName=source;kind=A.NamedLocalFunctionMember} in
 let recur=A.RecursiveBindingCandidate recursion in
 let simpleLambda=A.Lambda (ne [parameter (A.LPVariable "x") (Some A.TString) None],Some A.TString,literal) in
 let wrappers value=[value;A.BoundaryRender ("renderer",value);A.RuntimeError source;A.InterpolatedString [A.StringText source;A.StringExpr value;A.StringText "{}\\\"\n\r\t\000"];A.UnaryOp (A.Neg,value);A.UnaryOp (A.Not,value);A.UnaryOp (A.BitNot,value);A.Let (A.LPVariable source,simpleLambda,value);A.RecursiveLet (recur,simpleLambda,value);A.RecursiveLet (A.RecursiveBindingCandidate {recursion with A.kind=A.DirectLambdaValueMember},value,literal);A.If (value,literal,negative);A.Sequence (value,literal);A.Apply (fn,[],ne [value]);A.Apply (value,[A.TList A.TString],ne [negative;A.UnitLiteral;A.TupleLiteral [literal;negative]]);A.TupleLiteral [value;literal];A.TupleAccess (value,2);A.TupleAccess (A.TupleAccess (value,0),1);A.DictLiteral (A.TString,A.TInt64,[value,negative]);A.RecordLiteral (reference,[field,value]);A.RecordUpdate (value,[field,literal]);A.RecordAccess (value,field);A.Constructor (constructor,source,[]);A.Constructor (constructor,source,[value]);A.Constructor (constructor,source,[value;literal]);A.Constructor (A.UnresolvedConstructor None,source,[value]);A.Match (value,[{A.patterns=ne [A.PWildcard];guard=Some value;body=A.Match (value,[{A.patterns=ne [A.PUnit];guard=None;body=A.Let (A.LPVariable "x",value,literal)}])}]);A.ListLiteral [value;negative];A.Lambda (ne [parameter A.LPUnit None None],None,value);A.Lambda (ne [parameter (A.LPVariable source) None None;parameter A.LPWildcard None None],Some A.TString,value);A.Lambda (ne [parameter (A.LPVariable "$pipe_arg") None (Some A.TBool)],None,A.BinOp (A.And,A.Var "$pipe_arg",value));A.Lambda (ne [parameter (A.LPVariable "$pipe_arg") None (Some A.TBool)],None,A.BinOp (A.Or,A.Var "$pipe_arg",value));A.IndirectApply (A.Constructor (constructor,"Case",[]),ne [value]);A.IndirectApply (value,ne [A.UnitLiteral]);A.IndirectApply (value,ne [value;A.TupleLiteral []]);A.Closure (source,[value;negative])]
 in
 let precedence=list (fun parent->list (fun child->list (fun isLeft->let child=A.BinOp (child,A.Var "a",A.Var "b") in expr (if isLeft then A.BinOp (parent,child,A.Var "c") else A.BinOp (parent,A.Var "c",child))) [false;true]) operations) operations in
 let caseTexts=list (fun pattern->expr (A.Match (literal,[{A.patterns=ne [pattern;A.PWildcard];guard=None;body=literal}]))) patterns in
 let letTexts=list (fun pattern->expr (A.Let (pattern,simpleLambda,literal))) letPatterns in
 let expressionTexts=list (fun value->list expr (wrappers value)) (numbers@[A.Var source;A.Var "Module.function";A.Apply (fn,[],ne [literal]);A.BinOp (A.Add,literal,negative);A.Let (A.LPWildcard,literal,negative);A.TupleLiteral [literal;negative]]) in
 let typeTexts=list (fun typ->print [A.TypeDef (A.RecordDef (source,["a"],[source,typ]));A.TypeDef (A.SumTypeDef (source,["a"],[{A.name=source;fields=[]};{A.name="Case";fields=[typ;A.TString]}]));A.TypeDef (A.TypeAlias (source,["a"],typ));A.FunctionDef {A.name=source;typeParams=["a";"b"];params=ne [source,typ;"x",A.TString];returnType=typ;body=literal;recursion=None}]) types in
 let definition name=A.FunctionDef {A.name;typeParams=[];params=ne ["$unit0",A.TUnit];returnType=A.TString;body=literal;recursion=None} in
 let declarations=list print [ [];[definition "A.f"];[definition "A.f";A.ValueDef (A.UncheckedValueDef ("A.v",literal));A.ValueDef (A.CheckedValueDef ("A.checked",A.TString,literal));A.TypeDef (A.RecordDef ("A.R",[],[]));A.TypeDef (A.SumTypeDef ("A.S",[],[]));A.TypeDef (A.TypeAlias ("A.T",[],A.TUnit))];[definition "A.f";definition "B.g"];[definition "A.f";A.Expression ([],literal)];[definition source];[A.ValueDef (A.CheckedValueDef (source,A.TString,literal))] ] in
 tuple [precedence;caseTexts;letTexts;expressionTexts;typeTexts;declarations]
