(* Full compiler option schema, pass selection, duration and diagnostic output. *)
open Dark_compiler
module O=CompilerOptions
module D=PipelineDiagnostics
let tuple xs=`Assoc ["tuple",`List xs]
let option = function None -> SemanticJson.union "FSharpOption" "None" [] | Some value -> SemanticJson.union "FSharpOption" "Some" [value]
let int64 value = `Assoc ["kind",`String "int64";"value",`String (Int64.to_string value)]
let list f xs=`List (List.map f xs)
let probe=function O.NoNativeLayoutProbe->SemanticJson.union "NativeLayoutProbe" "NoNativeLayoutProbe" []|O.RootWord->SemanticJson.union "NativeLayoutProbe" "RootWord" []|O.TupleWords->SemanticJson.union "NativeLayoutProbe" "TupleWords" []
let options (o:O.compilerOptions)=SemanticJson.record "CompilerOptions" ["DisableFreeList",`Bool o.O.disableFreeList;"DisableANFOpt",`Bool o.O.disableANFOpt;"DisableANFConstFolding",`Bool o.O.disableANFConstFolding;"DisableANFConstProp",`Bool o.O.disableANFConstProp;"DisableANFCopyProp",`Bool o.O.disableANFCopyProp;"DisableANFDCE",`Bool o.O.disableANFDCE;"DisableANFStrengthReduction",`Bool o.O.disableANFStrengthReduction;"DisableInlining",`Bool o.O.disableInlining;"DisableTCO",`Bool o.O.disableTCO;"DisableMIROpt",`Bool o.O.disableMIROpt;"DisableMIRSCCP",`Bool o.O.disableMIRSCCP;"DisableMIRCSE",`Bool o.O.disableMIRCSE;"DisableMIRDCE",`Bool o.O.disableMIRDCE;"DisableMIRLICM",`Bool o.O.disableMIRLICM;"DisableLIROpt",`Bool o.O.disableLIROpt;"DisableLIRPeephole",`Bool o.O.disableLIRPeephole;"DisableFunctionTreeShaking",`Bool o.O.disableFunctionTreeShaking;"EnableCoverage",`Bool o.O.enableCoverage;"EnableLeakCheck",`Bool o.O.enableLeakCheck;"NativeLayoutProbe",probe o.O.nativeLayoutProbe;"Warnings",SemanticJson.union "WarningSettings" "WarningSettings" [];"DumpANF",`Bool o.O.dumpANF;"DumpMIR",`Bool o.O.dumpMIR;"DumpLIR",`Bool o.O.dumpLIR;"DumpFunction",(match o.O.dumpFunction with None->option None|Some s->option (Some (SemanticJson.string s)));"DumpIRSummary",`Bool o.O.dumpIRSummary]
let capture action=
 let path=Filename.temp_file "port-diagnostics-" ".txt" in
 let saved=Unix.dup ~cloexec:true Unix.stdout in
 Fun.protect ~finally:(fun ()->flush stdout;Unix.dup2 saved Unix.stdout;Unix.close saved;Sys.remove path) (fun ()->
  let fd=Unix.openfile path [Unix.O_WRONLY;Unix.O_CLOEXEC;Unix.O_TRUNC] 0 in flush stdout;Unix.dup2 fd Unix.stdout;Unix.close fd;
  action ();flush stdout;let channel=open_in_bin path in let value=In_channel.input_all channel in close_in channel;SemanticJson.string value)
let observe source=
 let defaults=tuple [options O.defaultOptions;`Bool (O.defaultWarningSettings=AST.defaultWarningSettings)] in
 let anf (o:ANFConstants.optimizeOptions)=SemanticJson.record "OptimizeOptions" ["EnableConstFolding",`Bool o.ANFConstants.enableConstFolding;"EnableConstProp",`Bool o.ANFConstants.enableConstProp;"EnableCopyProp",`Bool o.ANFConstants.enableCopyProp;"EnableDCE",`Bool o.ANFConstants.enableDCE;"EnableCSE",`Bool o.ANFConstants.enableCSE;"EnableStrengthReduction",`Bool o.ANFConstants.enableStrengthReduction;"EnableTailRecursionModuloOperation",`Bool o.ANFConstants.enableTailRecursionModuloOperation] in
 let mir (o:MIROptimizationFacts.optimizeOptions)=SemanticJson.record "OptimizeOptions" ["EnableSCCP",`Bool o.MIROptimizationFacts.enableSCCP;"EnableCSE",`Bool o.MIROptimizationFacts.enableCSE;"EnableDCE",`Bool o.MIROptimizationFacts.enableDCE;"EnableLICM",`Bool o.MIROptimizationFacts.enableLICM] in
 let selections=list (fun mask->let bit n=mask land (1 lsl n)<>0 in let o={O.defaultOptions with O.disableANFOpt=bit 0;disableANFConstFolding=bit 1;disableANFConstProp=bit 2;disableANFCopyProp=bit 3;disableANFDCE=bit 4;disableANFStrengthReduction=bit 5;disableTCO=bit 6;disableMIROpt=bit 7;disableMIRSCCP=bit 8;disableMIRCSE=bit 9;disableMIRDCE=bit 10;disableMIRLICM=bit 11} in let a=D.buildANFOptimizeOptions o in let m=D.buildMIROptimizeOptions o in tuple [anf a;`Bool (D.shouldRunANFOptimize a);mir m;`Bool (D.shouldRunMIROptimize m)]) (List.init 4096 Fun.id) in
 let flags=list (fun verbosity->list (fun enabled->`Bool (D.shouldDumpIR verbosity enabled)) [false;true]) [-2147483648;-1;0;1;2;3;4;2147483647] in
 let groups=list (fun label->list (fun flags->SemanticJson.string (D.formatPassGroup label flags)) [[];[source,false];[source,true];["a",true;"b",false;"c",true];["",true;"",true]]) [source;"";"hé😀";"nul\000"] in
 let values=[0.;-0.;0.00001;0.00005;0.00009;0.0001;0.00015;0.00019;-0.00005;-0.00015;0.1;1.5;123.456789;Int64.float_of_bits 0xfff8000000000000L;infinity;neg_infinity;922337203685477.5;922337203685477.6;-922337203685477.6;922337203685478.] in
 let timings=list (fun enabled->list (fun value->let events=ref [] in try D.recordPassTiming (if enabled then Some (fun (p:O.passTiming)->events:=(p.O.pass,HostTimeSpan.ticks p.O.elapsed):: !events) else None) source value;tuple [`Bool false;list (fun (name,ticks)->tuple [SemanticJson.string name;int64 ticks]) (List.rev !events)] with Failure e|Invalid_argument e->tuple [`Bool true;SemanticJson.string e]) values) [false;true] in
 let schemas=tuple [list (fun probeValue->options {O.defaultOptions with O.nativeLayoutProbe=probeValue}) [O.NoNativeLayoutProbe;O.RootWord;O.TupleWords];list (fun name->options {O.defaultOptions with O.dumpFunction=name;dumpIRSummary=true}) [None;Some "";Some source];list (fun mode->SemanticJson.union "CompileMode" (match mode with O.FullProgram->"FullProgram"|O.TestExpression->"TestExpression") []) [O.FullProgram;O.TestExpression];list (function O.Closed->SemanticJson.union "ExecutionInput" "Closed" []|O.Bytes bytes->SemanticJson.union "ExecutionInput" "Bytes" [X64EncodingObservation.bytes bytes]) [O.Closed;O.Bytes Bytes.empty;O.Bytes (Bytes.init 256 Char.chr)]] in
 let printed=list (fun summary->list (fun filter->let o={O.defaultOptions with O.dumpIRSummary=summary;dumpFunction=filter} in list (fun action->capture action) [(fun ()->D.printANFProgram o source (ANF.Program ([],ANF.Return ANF.UnitLiteral)));(fun ()->D.printMIRProgram o source (MIR.Program ([],StringOrder.Map.empty,StringOrder.Map.empty)));(fun ()->D.printLIRProgram o source (LIR.Program ([],StringOrder.Map.empty,StringOrder.Map.empty)))]) [None;Some "";Some source]) [false;true] in
 tuple [defaults;selections;flags;groups;timings;schemas;printed]
