(* Complete symbolic LIR constructors and reflected schema parity. *)
open Dark_compiler
let tuple values = `Assoc ["tuple", `List values]
let list encode values = `List (List.map encode values)
let observe source = let operand = LIR.StringSymbol source in let reg = LIR.Virtual 3 in let freg = LIR.FVirtual (-1) in let typ = AST.TRecord (source,[AST.TInt64;AST.TList AST.TString]) in tuple [tuple [
list ProductionLIR.physReg [LIR.X0;
LIR.X1;
LIR.X2;
LIR.X3;
LIR.X4;
LIR.X5;
LIR.X6;
LIR.X7;
LIR.X8;
LIR.X9;
LIR.X10;
LIR.X11;
LIR.X12;
LIR.X13;
LIR.X14;
LIR.X15;
LIR.X16;
LIR.X17;
LIR.X19;
LIR.X20;
LIR.X21;
LIR.X22;
LIR.X23;
LIR.X24;
LIR.X25;
LIR.X26;
LIR.X27;
LIR.X29;
LIR.X30;
LIR.SP];
list ProductionLIR.physFPReg [LIR.D0;
LIR.D1;
LIR.D2;
LIR.D3;
LIR.D4;
LIR.D5;
LIR.D6;
LIR.D7;
LIR.D8;
LIR.D9;
LIR.D10;
LIR.D11;
LIR.D12;
LIR.D13;
LIR.D14;
LIR.D15];
list ProductionLIR.reg [LIR.Physical (LIR.X0);
LIR.Virtual ((3))];
list ProductionLIR.fReg [LIR.FPhysical (LIR.D0);
LIR.FVirtual ((3))];
list ProductionLIR.operand [LIR.Imm ((-3L));
LIR.FloatImm ((-0.0));
LIR.Reg ((reg));
LIR.StackSlot ((3));
LIR.StringSymbol ((source));
LIR.FloatSymbol ((-0.0));
LIR.FuncAddr ((AST.functionId (-1L)))];
list ProductionLIR.condition [LIR.EQ;
LIR.NE;
LIR.LT;
LIR.GT;
LIR.LE;
LIR.GE;
LIR.ULT;
LIR.UGT;
LIR.ULE;
LIR.UGE];
list ProductionLIR.rcKind [LIR.GenericHeap;
LIR.StreamHeap;
LIR.TaggedList;
LIR.DictHeap;
LIR.ClosureHeap];
list ProductionLIR.cliOperation [LIR.Execute;
LIR.RunProcess;
LIR.HostOS;
LIR.HostArchitecture;
LIR.Hostname;
LIR.GetEnv;
LIR.GetEnvironmentPacked;
LIR.SetEnv;
LIR.UnsetEnv;
LIR.DirectoryCurrent;
LIR.DirectoryListPacked;
LIR.FileIsDirectory;
LIR.FileCreateExclusive;
LIR.GetArgv;
LIR.Kill;
LIR.GetPid;
LIR.GetUid;
LIR.CpuCount;
LIR.SpawnProcess;
LIR.ProcessIO;
LIR.TerminateProcess;
LIR.SocketTcp4;
LIR.SocketTcp6;
LIR.SocketUdp4;
LIR.SocketUdp6;
LIR.SocketConnect4;
LIR.SocketConnect6;
LIR.SocketSend;
LIR.SocketReceive;
LIR.SocketReceiveTimeout;
LIR.SocketSendTimeout;
LIR.SocketClose;
LIR.SecureRandomFill];
list ProductionLIR.label [LIR.Label ((source))];
list ProductionLIR.instr [LIR.Mov ((reg), (operand));
LIR.Phi ((reg), [((operand), (LIR.Label source)); ((operand), (LIR.Label source))], (Some ((typ))));
LIR.Store ((3), (reg));
LIR.Add ((reg), (reg), (operand));
LIR.Sub ((reg), (reg), (operand));
LIR.Mul ((reg), (reg), (reg));
LIR.Sdiv ((reg), (reg), (reg));
LIR.Udiv ((reg), (reg), (reg));
LIR.Msub ((reg), (reg), (reg), (reg));
LIR.Madd ((reg), (reg), (reg), (reg));
LIR.Cmp ((reg), (operand));
LIR.Cset ((reg), LIR.EQ);
LIR.Select ((reg), (reg), (reg), LIR.EQ);
LIR.And ((reg), (reg), (reg));
LIR.And_imm ((reg), (reg), (-3L));
LIR.Orr ((reg), (reg), (reg));
LIR.Eor ((reg), (reg), (reg));
LIR.Lsl ((reg), (reg), (reg));
LIR.Lsr ((reg), (reg), (reg));
LIR.Asr ((reg), (reg), (reg));
LIR.Lsl_imm ((reg), (reg), (3));
LIR.Lsr_imm ((reg), (reg), (3));
LIR.Asr_imm ((reg), (reg), (3));
LIR.Neg ((reg), (reg));
LIR.Mvn ((reg), (reg));
LIR.Sxtb ((reg), (reg));
LIR.Sxth ((reg), (reg));
LIR.Sxtw ((reg), (reg));
LIR.Uxtb ((reg), (reg));
LIR.Uxth ((reg), (reg));
LIR.Uxtw ((reg), (reg));
LIR.Call ((reg), (AST.functionId (-1L)), [(operand); (operand)]);
LIR.TailCall ((AST.functionId (-1L)), [(operand); (operand)]);
LIR.IndirectCall ((reg), (reg), [(operand); (operand)]);
LIR.IndirectTailCall ((reg), [(operand); (operand)]);
LIR.ClosureAlloc ((reg), (AST.functionId (-1L)), [(operand); (operand)]);
LIR.ClosureCall ((reg), (reg), [(operand); (operand)]);
LIR.ClosureTailCall ((reg), [(operand); (operand)]);
LIR.SaveRegs ([LIR.X0; LIR.X0], [LIR.D0; LIR.D0]);
LIR.RestoreRegs ([LIR.X0; LIR.X0], [LIR.D0; LIR.D0]);
LIR.ArgMoves ([(LIR.X0, (operand)); (LIR.X0, (operand))]);
LIR.TailArgMoves ([(LIR.X0, (operand)); (LIR.X0, (operand))]);
LIR.FArgMoves ([(LIR.D0, (freg)); (LIR.D0, (freg))]);
LIR.PrintInt64 ((reg));
LIR.PrintUInt64 ((reg));
LIR.PrintBool ((reg));
LIR.PrintInt64NoNewline ((reg));
LIR.PrintUInt64NoNewline ((reg));
LIR.PrintBoolNoNewline ((reg));
LIR.PrintFloat ((freg));
LIR.PrintFloatNoNewline ((freg));
LIR.PrintString ((source));
LIR.StdoutWrite ((3), (operand), (true));
LIR.StdinReadLine ((3), (reg));
LIR.RuntimeError ((source));
LIR.RuntimeErrorString ((reg));
LIR.PrintHeapStringNoNewline ((reg));
LIR.PrintChars ([0;127;255]);
LIR.PrintBlob ((reg));
LIR.PrintList ((reg), (typ));
LIR.PrintSum ((reg), [((source), (3), (Some ((typ)))); ((source), (3), (Some ((typ))))], (true));
LIR.PrintRecord ((reg), (source), [((source), (typ)); ((source), (typ))]);
LIR.Exit;
LIR.FPhi ((freg), [((freg), (LIR.Label source)); ((freg), (LIR.Label source))]);
LIR.FMov ((freg), (freg));
LIR.FLoad ((freg), (-0.0));
LIR.FSpillLoad ((freg), (3));
LIR.FSpillStore ((3), (freg));
LIR.FAdd ((freg), (freg), (freg));
LIR.FSub ((freg), (freg), (freg));
LIR.FMul ((freg), (freg), (freg));
LIR.FMadd ((freg), (freg), (freg), (freg));
LIR.FDiv ((freg), (freg), (freg));
LIR.FNeg ((freg), (freg));
LIR.FAbs ((freg), (freg));
LIR.FSqrt ((freg), (freg));
LIR.FCmp ((freg), (freg));
LIR.Int64ToFloat ((freg), (reg));
LIR.FloatToInt64 ((reg), (freg));
LIR.FloatToBits ((reg), (freg));
LIR.GpToFp ((freg), (reg));
LIR.FpToGp ((reg), (freg));
LIR.HeapAlloc ((reg), (3));
LIR.HeapStore ((reg), (3), (operand), (Some ((typ))));
LIR.HeapLoad ((reg), (reg), (3));
LIR.RefCountInc ((reg), (3), LIR.GenericHeap, (Some (({MemoryModel.releasePlanCacheKey=Some source;releasePlan=Some (MemoryModel.RecursiveRelease (AST.TList AST.TString));sourceType=Some AST.TString}))));
LIR.RefCountDec ((reg), (3), LIR.GenericHeap, (Some (({MemoryModel.releasePlanCacheKey=Some source;releasePlan=Some (MemoryModel.RecursiveRelease (AST.TList AST.TString));sourceType=Some AST.TString}))));
LIR.StringConcat ((reg), (operand), (operand), [(operand); (operand)]);
LIR.CanonicalBufferEq ((reg), (MemoryModel.NullableGraphemeCluster), (operand), (operand));
LIR.PrintHeapString ((reg));
LIR.LoadFuncAddr ((reg), (AST.functionId (-1L)));
LIR.FileReadBlob ((reg), (operand));
LIR.FileExists ((reg), (operand));
LIR.FileWriteBlob ((reg), (operand), (operand));
LIR.FileAppendText ((reg), (operand), (operand));
LIR.FileDelete ((reg), (operand));
LIR.FileCreateDirectory ((reg), (operand));
LIR.FileSetExecutable ((reg), (operand));
LIR.FileWriteFromPtr ((reg), (operand), (reg), (reg));
LIR.RawAlloc ((reg), (reg));
LIR.MappedAlloc ((reg), (reg));
LIR.RawFree ((reg));
LIR.MappedFree ((reg));
LIR.RawGet ((reg), (reg), (reg));
LIR.RawGetByte ((reg), (reg), (reg));
LIR.RawWriteWord ((reg), (reg), (reg));
LIR.RawWriteByte ((reg), (reg), (reg));
LIR.RawSlotInit ((reg), (reg), (reg), (typ));
LIR.RefCountIncString ((operand));
LIR.RefCountDecString ((operand));
LIR.RefCountIncBlob ((operand));
LIR.RefCountDecBlob ((operand));
LIR.RefCountIncInt ((operand));
LIR.RefCountDecInt ((operand));
LIR.RandomInt64 ((reg));
LIR.DateTimeNow ((reg));
LIR.Sleep ((3), (freg));
LIR.CliNative ((reg), LIR.Execute, [(operand); (operand)]);
LIR.FloatToString ((reg), (freg));
LIR.CoverageHit ((3))];
list ProductionLIR.terminator [LIR.Ret;
LIR.Branch ((reg), (LIR.Label source), (LIR.Label source));
LIR.BranchZero ((reg), (LIR.Label source), (LIR.Label source));
LIR.BranchBitZero ((reg), (3), (LIR.Label source), (LIR.Label source));
LIR.BranchBitNonZero ((reg), (3), (LIR.Label source), (LIR.Label source));
LIR.CondBranch (LIR.EQ, (LIR.Label source), (LIR.Label source));
LIR.Jump ((LIR.Label source))];
list ProductionLIR.rcReleasePlanMemoKey [LIR.FingerprintedReleasePlan ((source));
LIR.StructuralReleasePlan ((Some ((MemoryModel.RootRelease (16,MemoryModel.GenericHeap,MemoryModel.FixedBlockPayloadRelease (16,[MemoryModel.FieldRelease (8,MemoryModel.RecursiveRelease (AST.TRecord (source,[])))]))))))];
list ProductionLIR.arm64SlotInitRootRetainTarget [LIR.SlotInitListRootRetain;
LIR.SlotInitDictRootRetain;
LIR.SlotInitDynamicBufferRetain;
LIR.SlotInitClosureRootRetain;
LIR.SlotInitGenericRootRetain ((3))]];tuple [list (fun (name,fields) -> tuple [SemanticJson.string name; SemanticJson.int32 fields]) [("X0",0); ("X1",0); ("X2",0); ("X3",0); ("X4",0); ("X5",0); ("X6",0); ("X7",0); ("X8",0); ("X9",0); ("X10",0); ("X11",0); ("X12",0); ("X13",0); ("X14",0); ("X15",0); ("X16",0); ("X17",0); ("X19",0); ("X20",0); ("X21",0); ("X22",0); ("X23",0); ("X24",0); ("X25",0); ("X26",0); ("X27",0); ("X29",0); ("X30",0); ("SP",0)];
list (fun (name,fields) -> tuple [SemanticJson.string name; SemanticJson.int32 fields]) [("D0",0); ("D1",0); ("D2",0); ("D3",0); ("D4",0); ("D5",0); ("D6",0); ("D7",0); ("D8",0); ("D9",0); ("D10",0); ("D11",0); ("D12",0); ("D13",0); ("D14",0); ("D15",0)];
list (fun (name,fields) -> tuple [SemanticJson.string name; SemanticJson.int32 fields]) [("Physical",1); ("Virtual",1)];
list (fun (name,fields) -> tuple [SemanticJson.string name; SemanticJson.int32 fields]) [("FPhysical",1); ("FVirtual",1)];
list (fun (name,fields) -> tuple [SemanticJson.string name; SemanticJson.int32 fields]) [("Imm",1); ("FloatImm",1); ("Reg",1); ("StackSlot",1); ("StringSymbol",1); ("FloatSymbol",1); ("FuncAddr",1)];
list (fun (name,fields) -> tuple [SemanticJson.string name; SemanticJson.int32 fields]) [("EQ",0); ("NE",0); ("LT",0); ("GT",0); ("LE",0); ("GE",0); ("ULT",0); ("UGT",0); ("ULE",0); ("UGE",0)];
list (fun (name,fields) -> tuple [SemanticJson.string name; SemanticJson.int32 fields]) [("GenericHeap",0); ("StreamHeap",0); ("TaggedList",0); ("DictHeap",0); ("ClosureHeap",0)];
list (fun (name,fields) -> tuple [SemanticJson.string name; SemanticJson.int32 fields]) [("Execute",0); ("RunProcess",0); ("HostOS",0); ("HostArchitecture",0); ("Hostname",0); ("GetEnv",0); ("GetEnvironmentPacked",0); ("SetEnv",0); ("UnsetEnv",0); ("DirectoryCurrent",0); ("DirectoryListPacked",0); ("FileIsDirectory",0); ("FileCreateExclusive",0); ("GetArgv",0); ("Kill",0); ("GetPid",0); ("GetUid",0); ("CpuCount",0); ("SpawnProcess",0); ("ProcessIO",0); ("TerminateProcess",0); ("SocketTcp4",0); ("SocketTcp6",0); ("SocketUdp4",0); ("SocketUdp6",0); ("SocketConnect4",0); ("SocketConnect6",0); ("SocketSend",0); ("SocketReceive",0); ("SocketReceiveTimeout",0); ("SocketSendTimeout",0); ("SocketClose",0); ("SecureRandomFill",0)];
list (fun (name,fields) -> tuple [SemanticJson.string name; SemanticJson.int32 fields]) [("Label",1)];
list (fun (name,fields) -> tuple [SemanticJson.string name; SemanticJson.int32 fields]) [("Mov",2); ("Phi",3); ("Store",2); ("Add",3); ("Sub",3); ("Mul",3); ("Sdiv",3); ("Udiv",3); ("Msub",4); ("Madd",4); ("Cmp",2); ("Cset",2); ("Select",4); ("And",3); ("And_imm",3); ("Orr",3); ("Eor",3); ("Lsl",3); ("Lsr",3); ("Asr",3); ("Lsl_imm",3); ("Lsr_imm",3); ("Asr_imm",3); ("Neg",2); ("Mvn",2); ("Sxtb",2); ("Sxth",2); ("Sxtw",2); ("Uxtb",2); ("Uxth",2); ("Uxtw",2); ("Call",3); ("TailCall",2); ("IndirectCall",3); ("IndirectTailCall",2); ("ClosureAlloc",3); ("ClosureCall",3); ("ClosureTailCall",2); ("SaveRegs",2); ("RestoreRegs",2); ("ArgMoves",1); ("TailArgMoves",1); ("FArgMoves",1); ("PrintInt64",1); ("PrintUInt64",1); ("PrintBool",1); ("PrintInt64NoNewline",1); ("PrintUInt64NoNewline",1); ("PrintBoolNoNewline",1); ("PrintFloat",1); ("PrintFloatNoNewline",1); ("PrintString",1); ("StdoutWrite",3); ("StdinReadLine",2); ("RuntimeError",1); ("RuntimeErrorString",1); ("PrintHeapStringNoNewline",1); ("PrintChars",1); ("PrintBlob",1); ("PrintList",2); ("PrintSum",3); ("PrintRecord",3); ("Exit",0); ("FPhi",2); ("FMov",2); ("FLoad",2); ("FSpillLoad",2); ("FSpillStore",2); ("FAdd",3); ("FSub",3); ("FMul",3); ("FMadd",4); ("FDiv",3); ("FNeg",2); ("FAbs",2); ("FSqrt",2); ("FCmp",2); ("Int64ToFloat",2); ("FloatToInt64",2); ("FloatToBits",2); ("GpToFp",2); ("FpToGp",2); ("HeapAlloc",2); ("HeapStore",4); ("HeapLoad",3); ("RefCountInc",4); ("RefCountDec",4); ("StringConcat",4); ("CanonicalBufferEq",4); ("PrintHeapString",1); ("LoadFuncAddr",2); ("FileReadBlob",2); ("FileExists",2); ("FileWriteBlob",3); ("FileAppendText",3); ("FileDelete",2); ("FileCreateDirectory",2); ("FileSetExecutable",2); ("FileWriteFromPtr",4); ("RawAlloc",2); ("MappedAlloc",2); ("RawFree",1); ("MappedFree",1); ("RawGet",3); ("RawGetByte",3); ("RawWriteWord",3); ("RawWriteByte",3); ("RawSlotInit",4); ("RefCountIncString",1); ("RefCountDecString",1); ("RefCountIncBlob",1); ("RefCountDecBlob",1); ("RefCountIncInt",1); ("RefCountDecInt",1); ("RandomInt64",1); ("DateTimeNow",1); ("Sleep",2); ("CliNative",3); ("FloatToString",2); ("CoverageHit",1)];
list (fun (name,fields) -> tuple [SemanticJson.string name; SemanticJson.int32 fields]) [("Ret",0); ("Branch",3); ("BranchZero",3); ("BranchBitZero",4); ("BranchBitNonZero",4); ("CondBranch",3); ("Jump",1)];
list (fun (name,fields) -> tuple [SemanticJson.string name; SemanticJson.int32 fields]) [("FingerprintedReleasePlan",1); ("StructuralReleasePlan",1)];
list (fun (name,fields) -> tuple [SemanticJson.string name; SemanticJson.int32 fields]) [("SlotInitListRootRetain",0); ("SlotInitDictRootRetain",0); ("SlotInitDynamicBufferRetain",0); ("SlotInitClosureRootRetain",0); ("SlotInitGenericRootRetain",1)]]]
let instructionsWithRegisters source reg freg operand typ = [LIR.Mov ((reg), (operand));
LIR.Phi ((reg), [((operand), (LIR.Label source)); ((operand), (LIR.Label source))], (Some ((typ))));
LIR.Store ((3), (reg));
LIR.Add ((reg), (reg), (operand));
LIR.Sub ((reg), (reg), (operand));
LIR.Mul ((reg), (reg), (reg));
LIR.Sdiv ((reg), (reg), (reg));
LIR.Udiv ((reg), (reg), (reg));
LIR.Msub ((reg), (reg), (reg), (reg));
LIR.Madd ((reg), (reg), (reg), (reg));
LIR.Cmp ((reg), (operand));
LIR.Cset ((reg), LIR.EQ);
LIR.Select ((reg), (reg), (reg), LIR.EQ);
LIR.And ((reg), (reg), (reg));
LIR.And_imm ((reg), (reg), (-3L));
LIR.Orr ((reg), (reg), (reg));
LIR.Eor ((reg), (reg), (reg));
LIR.Lsl ((reg), (reg), (reg));
LIR.Lsr ((reg), (reg), (reg));
LIR.Asr ((reg), (reg), (reg));
LIR.Lsl_imm ((reg), (reg), (3));
LIR.Lsr_imm ((reg), (reg), (3));
LIR.Asr_imm ((reg), (reg), (3));
LIR.Neg ((reg), (reg));
LIR.Mvn ((reg), (reg));
LIR.Sxtb ((reg), (reg));
LIR.Sxth ((reg), (reg));
LIR.Sxtw ((reg), (reg));
LIR.Uxtb ((reg), (reg));
LIR.Uxth ((reg), (reg));
LIR.Uxtw ((reg), (reg));
LIR.Call ((reg), (AST.functionId (-1L)), [(operand); (operand)]);
LIR.TailCall ((AST.functionId (-1L)), [(operand); (operand)]);
LIR.IndirectCall ((reg), (reg), [(operand); (operand)]);
LIR.IndirectTailCall ((reg), [(operand); (operand)]);
LIR.ClosureAlloc ((reg), (AST.functionId (-1L)), [(operand); (operand)]);
LIR.ClosureCall ((reg), (reg), [(operand); (operand)]);
LIR.ClosureTailCall ((reg), [(operand); (operand)]);
LIR.SaveRegs ([LIR.X0; LIR.X0], [LIR.D0; LIR.D0]);
LIR.RestoreRegs ([LIR.X0; LIR.X0], [LIR.D0; LIR.D0]);
LIR.ArgMoves ([(LIR.X0, (operand)); (LIR.X0, (operand))]);
LIR.TailArgMoves ([(LIR.X0, (operand)); (LIR.X0, (operand))]);
LIR.FArgMoves ([(LIR.D0, (freg)); (LIR.D0, (freg))]);
LIR.PrintInt64 ((reg));
LIR.PrintUInt64 ((reg));
LIR.PrintBool ((reg));
LIR.PrintInt64NoNewline ((reg));
LIR.PrintUInt64NoNewline ((reg));
LIR.PrintBoolNoNewline ((reg));
LIR.PrintFloat ((freg));
LIR.PrintFloatNoNewline ((freg));
LIR.PrintString ((source));
LIR.StdoutWrite ((3), (operand), (true));
LIR.StdinReadLine ((3), (reg));
LIR.RuntimeError ((source));
LIR.RuntimeErrorString ((reg));
LIR.PrintHeapStringNoNewline ((reg));
LIR.PrintChars ([0;127;255]);
LIR.PrintBlob ((reg));
LIR.PrintList ((reg), (typ));
LIR.PrintSum ((reg), [((source), (3), (Some ((typ)))); ((source), (3), (Some ((typ))))], (true));
LIR.PrintRecord ((reg), (source), [((source), (typ)); ((source), (typ))]);
LIR.Exit;
LIR.FPhi ((freg), [((freg), (LIR.Label source)); ((freg), (LIR.Label source))]);
LIR.FMov ((freg), (freg));
LIR.FLoad ((freg), (-0.0));
LIR.FSpillLoad ((freg), (3));
LIR.FSpillStore ((3), (freg));
LIR.FAdd ((freg), (freg), (freg));
LIR.FSub ((freg), (freg), (freg));
LIR.FMul ((freg), (freg), (freg));
LIR.FMadd ((freg), (freg), (freg), (freg));
LIR.FDiv ((freg), (freg), (freg));
LIR.FNeg ((freg), (freg));
LIR.FAbs ((freg), (freg));
LIR.FSqrt ((freg), (freg));
LIR.FCmp ((freg), (freg));
LIR.Int64ToFloat ((freg), (reg));
LIR.FloatToInt64 ((reg), (freg));
LIR.FloatToBits ((reg), (freg));
LIR.GpToFp ((freg), (reg));
LIR.FpToGp ((reg), (freg));
LIR.HeapAlloc ((reg), (3));
LIR.HeapStore ((reg), (3), (operand), (Some ((typ))));
LIR.HeapLoad ((reg), (reg), (3));
LIR.RefCountInc ((reg), (3), LIR.GenericHeap, (Some (({MemoryModel.releasePlanCacheKey=Some source;releasePlan=Some (MemoryModel.RecursiveRelease (AST.TList AST.TString));sourceType=Some AST.TString}))));
LIR.RefCountDec ((reg), (3), LIR.GenericHeap, (Some (({MemoryModel.releasePlanCacheKey=Some source;releasePlan=Some (MemoryModel.RecursiveRelease (AST.TList AST.TString));sourceType=Some AST.TString}))));
LIR.StringConcat ((reg), (operand), (operand), [(operand); (operand)]);
LIR.CanonicalBufferEq ((reg), (MemoryModel.NullableGraphemeCluster), (operand), (operand));
LIR.PrintHeapString ((reg));
LIR.LoadFuncAddr ((reg), (AST.functionId (-1L)));
LIR.FileReadBlob ((reg), (operand));
LIR.FileExists ((reg), (operand));
LIR.FileWriteBlob ((reg), (operand), (operand));
LIR.FileAppendText ((reg), (operand), (operand));
LIR.FileDelete ((reg), (operand));
LIR.FileCreateDirectory ((reg), (operand));
LIR.FileSetExecutable ((reg), (operand));
LIR.FileWriteFromPtr ((reg), (operand), (reg), (reg));
LIR.RawAlloc ((reg), (reg));
LIR.MappedAlloc ((reg), (reg));
LIR.RawFree ((reg));
LIR.MappedFree ((reg));
LIR.RawGet ((reg), (reg), (reg));
LIR.RawGetByte ((reg), (reg), (reg));
LIR.RawWriteWord ((reg), (reg), (reg));
LIR.RawWriteByte ((reg), (reg), (reg));
LIR.RawSlotInit ((reg), (reg), (reg), (typ));
LIR.RefCountIncString ((operand));
LIR.RefCountDecString ((operand));
LIR.RefCountIncBlob ((operand));
LIR.RefCountDecBlob ((operand));
LIR.RefCountIncInt ((operand));
LIR.RefCountDecInt ((operand));
LIR.RandomInt64 ((reg));
LIR.DateTimeNow ((reg));
LIR.Sleep ((3), (freg));
LIR.CliNative ((reg), LIR.Execute, [(operand); (operand)]);
LIR.FloatToString ((reg), (freg));
LIR.CoverageHit ((3))]
let instructionsWithOperand source operand = instructionsWithRegisters source (LIR.Virtual 3) (LIR.FVirtual (-1)) operand (AST.TRecord (source,[AST.TInt64;AST.TList AST.TString]))
let instructions source = instructionsWithOperand source (LIR.StringSymbol source)
