(* All MIR instruction constructors, parameterized by operand and type. *)
open Dark_compiler
let instructions source typ operand : MIR.instr list =
let fid n=AST.functionId (Int64.of_int n) in [
MIR.Mov (MIR.VReg 1, operand, Some typ);
MIR.BinOp (MIR.VReg 1, MIR.Div, operand, operand, typ);
MIR.UnaryOp (MIR.VReg 1, MIR.Not, operand);
MIR.Call (MIR.VReg 1, fid 200, [operand; MIR.Register (MIR.VReg 3)], [typ; typ], typ);
MIR.TailCall (fid 200, [operand; MIR.Register (MIR.VReg 3)], [typ; typ], typ);
MIR.IndirectCall (MIR.VReg 1, operand, [operand; MIR.Register (MIR.VReg 3)], [typ; typ], typ);
MIR.IndirectTailCall (operand, [operand; MIR.Register (MIR.VReg 3)], [typ; typ], typ);
MIR.ClosureAlloc (MIR.VReg 1, fid 200, [operand; MIR.Register (MIR.VReg 3)]);
MIR.ClosureCall (MIR.VReg 1, operand, [operand; MIR.Register (MIR.VReg 3)], [typ; typ], typ);
MIR.ClosureTailCall (operand, [operand; MIR.Register (MIR.VReg 3)], [typ; typ]);
MIR.HeapAlloc (MIR.VReg 1, 3);
MIR.HeapStore (MIR.VReg 1, 3, operand, Some typ);
MIR.HeapLoad (MIR.VReg 1, MIR.VReg 2, 3, Some typ);
MIR.StringConcat (MIR.VReg 1, operand, operand, [operand; MIR.Register (MIR.VReg 3)]);
MIR.CanonicalBufferEq (MIR.VReg 1, MemoryModel.Utf8String, operand, operand);
MIR.RefCountInc (MIR.VReg 1, 3, MIR.GenericHeap, None);
MIR.RefCountDec (MIR.VReg 1, 3, MIR.GenericHeap, None);
MIR.Print (operand, typ);
MIR.StdoutWrite (3, operand, true);
MIR.StdinReadLine (MIR.VReg 1);
MIR.RuntimeError (source);
MIR.RuntimeErrorString (operand);
MIR.FileReadBlob (MIR.VReg 1, operand);
MIR.FileExists (MIR.VReg 1, operand);
MIR.FileWriteBlob (MIR.VReg 1, operand, operand);
MIR.FileAppendText (MIR.VReg 1, operand, operand);
MIR.FileDelete (MIR.VReg 1, operand);
MIR.FileCreateDirectory (MIR.VReg 1, operand);
MIR.FileSetExecutable (MIR.VReg 1, operand);
MIR.FileWriteFromPtr (MIR.VReg 1, operand, operand, operand);
MIR.FloatSqrt (MIR.VReg 1, operand);
MIR.FloatAbs (MIR.VReg 1, operand);
MIR.FloatNeg (MIR.VReg 1, operand);
MIR.Int64ToFloat (MIR.VReg 1, operand);
MIR.FloatToInt64 (MIR.VReg 1, operand);
MIR.FloatToBits (MIR.VReg 1, operand);
MIR.RawAlloc (MIR.VReg 1, operand);
MIR.MappedAlloc (MIR.VReg 1, operand);
MIR.RawFree (operand);
MIR.MappedFree (operand);
MIR.RawGet (MIR.VReg 1, operand, operand, Some typ);
MIR.RawGetByte (MIR.VReg 1, operand, operand);
MIR.RawWriteWord (operand, operand, operand);
MIR.RawWriteByte (operand, operand, operand);
MIR.RawSlotInit (operand, operand, operand, typ);
MIR.StringToRawPtr (MIR.VReg 1, operand);
MIR.RawPtrToString (MIR.VReg 1, operand);
MIR.BlobToRawPtr (MIR.VReg 1, operand);
MIR.RawPtrToBlob (MIR.VReg 1, operand);
MIR.DictToRawPtr (MIR.VReg 1, operand);
MIR.RawPtrToDict (MIR.VReg 1, operand, operand);
MIR.ListToRawPtr (MIR.VReg 1, operand);
MIR.RawPtrToList (MIR.VReg 1, operand, operand);
MIR.RefCountIncString (operand);
MIR.RefCountDecString (operand);
MIR.RefCountIncBlob (operand);
MIR.RefCountDecBlob (operand);
MIR.RefCountIncInt (operand);
MIR.RefCountDecInt (operand);
MIR.RandomInt64 (MIR.VReg 1);
MIR.DateTimeNow (MIR.VReg 1);
MIR.Sleep (3, MIR.VReg 2, operand);
MIR.CliNative (MIR.VReg 1, MIR.HostOS, [operand; MIR.Register (MIR.VReg 3)]);
MIR.FloatToString (MIR.VReg 1, operand);
MIR.Phi (MIR.VReg 1, [operand, MIR.Label source; MIR.Register (MIR.VReg 3), MIR.Label "other"], Some typ);
MIR.CoverageHit (3) ]
