(* Complete typed symbolic LIR encoders. *)
[@@@warning "-4"]
open Dark_compiler
let scalar kind value = `Assoc ["kind", `String kind; "value", `String value]
let tuple values = `Assoc ["tuple", `List values]
let list encode values = `List (List.map encode values)
let option encode = function None -> SemanticJson.union "FSharpOption" "None" [] | Some value -> SemanticJson.union "FSharpOption" "Some" [encode value]
let boolean value = `Bool value
let int64 value = scalar "int64" (Int64.to_string value)
let float64 value = scalar "float64" (Printf.sprintf "%016Lx" (Int64.bits_of_float value))
let functionId value = SemanticJson.union "FunctionId" "FunctionId" [scalar "uint64" (Printf.sprintf "%Lu" (AST.functionIdValue value))]
let rec physReg (value : LIR.physReg) = match value with
 | LIR.X0 -> SemanticJson.union "PhysReg" "X0" []
 | LIR.X1 -> SemanticJson.union "PhysReg" "X1" []
 | LIR.X2 -> SemanticJson.union "PhysReg" "X2" []
 | LIR.X3 -> SemanticJson.union "PhysReg" "X3" []
 | LIR.X4 -> SemanticJson.union "PhysReg" "X4" []
 | LIR.X5 -> SemanticJson.union "PhysReg" "X5" []
 | LIR.X6 -> SemanticJson.union "PhysReg" "X6" []
 | LIR.X7 -> SemanticJson.union "PhysReg" "X7" []
 | LIR.X8 -> SemanticJson.union "PhysReg" "X8" []
 | LIR.X9 -> SemanticJson.union "PhysReg" "X9" []
 | LIR.X10 -> SemanticJson.union "PhysReg" "X10" []
 | LIR.X11 -> SemanticJson.union "PhysReg" "X11" []
 | LIR.X12 -> SemanticJson.union "PhysReg" "X12" []
 | LIR.X13 -> SemanticJson.union "PhysReg" "X13" []
 | LIR.X14 -> SemanticJson.union "PhysReg" "X14" []
 | LIR.X15 -> SemanticJson.union "PhysReg" "X15" []
 | LIR.X16 -> SemanticJson.union "PhysReg" "X16" []
 | LIR.X17 -> SemanticJson.union "PhysReg" "X17" []
 | LIR.X19 -> SemanticJson.union "PhysReg" "X19" []
 | LIR.X20 -> SemanticJson.union "PhysReg" "X20" []
 | LIR.X21 -> SemanticJson.union "PhysReg" "X21" []
 | LIR.X22 -> SemanticJson.union "PhysReg" "X22" []
 | LIR.X23 -> SemanticJson.union "PhysReg" "X23" []
 | LIR.X24 -> SemanticJson.union "PhysReg" "X24" []
 | LIR.X25 -> SemanticJson.union "PhysReg" "X25" []
 | LIR.X26 -> SemanticJson.union "PhysReg" "X26" []
 | LIR.X27 -> SemanticJson.union "PhysReg" "X27" []
 | LIR.X29 -> SemanticJson.union "PhysReg" "X29" []
 | LIR.X30 -> SemanticJson.union "PhysReg" "X30" []
 | LIR.SP -> SemanticJson.union "PhysReg" "SP" []
and physFPReg (value : LIR.physFPReg) = match value with
 | LIR.D0 -> SemanticJson.union "PhysFPReg" "D0" []
 | LIR.D1 -> SemanticJson.union "PhysFPReg" "D1" []
 | LIR.D2 -> SemanticJson.union "PhysFPReg" "D2" []
 | LIR.D3 -> SemanticJson.union "PhysFPReg" "D3" []
 | LIR.D4 -> SemanticJson.union "PhysFPReg" "D4" []
 | LIR.D5 -> SemanticJson.union "PhysFPReg" "D5" []
 | LIR.D6 -> SemanticJson.union "PhysFPReg" "D6" []
 | LIR.D7 -> SemanticJson.union "PhysFPReg" "D7" []
 | LIR.D8 -> SemanticJson.union "PhysFPReg" "D8" []
 | LIR.D9 -> SemanticJson.union "PhysFPReg" "D9" []
 | LIR.D10 -> SemanticJson.union "PhysFPReg" "D10" []
 | LIR.D11 -> SemanticJson.union "PhysFPReg" "D11" []
 | LIR.D12 -> SemanticJson.union "PhysFPReg" "D12" []
 | LIR.D13 -> SemanticJson.union "PhysFPReg" "D13" []
 | LIR.D14 -> SemanticJson.union "PhysFPReg" "D14" []
 | LIR.D15 -> SemanticJson.union "PhysFPReg" "D15" []
and reg (value : LIR.reg) = match value with
 | LIR.Physical (field0) -> SemanticJson.union "Reg" "Physical" [physReg field0]
 | LIR.Virtual (field0) -> SemanticJson.union "Reg" "Virtual" [SemanticJson.int32 field0]
and fReg (value : LIR.fReg) = match value with
 | LIR.FPhysical (field0) -> SemanticJson.union "FReg" "FPhysical" [physFPReg field0]
 | LIR.FVirtual (field0) -> SemanticJson.union "FReg" "FVirtual" [SemanticJson.int32 field0]
and typedLIRParam (value : LIR.typedLIRParam) = SemanticJson.record "TypedLIRParam" ["Reg", reg value.LIR.reg; "Type", SemanticAST.semanticType value.LIR.typ]
and operand (value : LIR.operand) = match value with
 | LIR.Imm (field0) -> SemanticJson.union "Operand" "Imm" [int64 field0]
 | LIR.FloatImm (field0) -> SemanticJson.union "Operand" "FloatImm" [float64 field0]
 | LIR.Reg (field0) -> SemanticJson.union "Operand" "Reg" [reg field0]
 | LIR.StackSlot (field0) -> SemanticJson.union "Operand" "StackSlot" [SemanticJson.int32 field0]
 | LIR.StringSymbol (field0) -> SemanticJson.union "Operand" "StringSymbol" [SemanticJson.string field0]
 | LIR.FloatSymbol (field0) -> SemanticJson.union "Operand" "FloatSymbol" [float64 field0]
 | LIR.FuncAddr (field0) -> SemanticJson.union "Operand" "FuncAddr" [functionId field0]
and condition (value : LIR.condition) = match value with
 | LIR.EQ -> SemanticJson.union "Condition" "EQ" []
 | LIR.NE -> SemanticJson.union "Condition" "NE" []
 | LIR.LT -> SemanticJson.union "Condition" "LT" []
 | LIR.GT -> SemanticJson.union "Condition" "GT" []
 | LIR.LE -> SemanticJson.union "Condition" "LE" []
 | LIR.GE -> SemanticJson.union "Condition" "GE" []
 | LIR.ULT -> SemanticJson.union "Condition" "ULT" []
 | LIR.UGT -> SemanticJson.union "Condition" "UGT" []
 | LIR.ULE -> SemanticJson.union "Condition" "ULE" []
 | LIR.UGE -> SemanticJson.union "Condition" "UGE" []
and rcKind (value : LIR.rcKind) = match value with
 | LIR.GenericHeap -> SemanticJson.union "RcKind" "GenericHeap" []
 | LIR.StreamHeap -> SemanticJson.union "RcKind" "StreamHeap" []
 | LIR.TaggedList -> SemanticJson.union "RcKind" "TaggedList" []
 | LIR.DictHeap -> SemanticJson.union "RcKind" "DictHeap" []
 | LIR.ClosureHeap -> SemanticJson.union "RcKind" "ClosureHeap" []
and cliOperation (value : LIR.cliOperation) = match value with
 | LIR.Execute -> SemanticJson.union "CliOperation" "Execute" []
 | LIR.RunProcess -> SemanticJson.union "CliOperation" "RunProcess" []
 | LIR.HostOS -> SemanticJson.union "CliOperation" "HostOS" []
 | LIR.HostArchitecture -> SemanticJson.union "CliOperation" "HostArchitecture" []
 | LIR.Hostname -> SemanticJson.union "CliOperation" "Hostname" []
 | LIR.GetEnv -> SemanticJson.union "CliOperation" "GetEnv" []
 | LIR.GetEnvironmentPacked -> SemanticJson.union "CliOperation" "GetEnvironmentPacked" []
 | LIR.SetEnv -> SemanticJson.union "CliOperation" "SetEnv" []
 | LIR.UnsetEnv -> SemanticJson.union "CliOperation" "UnsetEnv" []
 | LIR.DirectoryCurrent -> SemanticJson.union "CliOperation" "DirectoryCurrent" []
 | LIR.DirectoryListPacked -> SemanticJson.union "CliOperation" "DirectoryListPacked" []
 | LIR.FileIsDirectory -> SemanticJson.union "CliOperation" "FileIsDirectory" []
 | LIR.FileCreateExclusive -> SemanticJson.union "CliOperation" "FileCreateExclusive" []
 | LIR.GetArgv -> SemanticJson.union "CliOperation" "GetArgv" []
 | LIR.Kill -> SemanticJson.union "CliOperation" "Kill" []
 | LIR.GetPid -> SemanticJson.union "CliOperation" "GetPid" []
 | LIR.GetUid -> SemanticJson.union "CliOperation" "GetUid" []
 | LIR.CpuCount -> SemanticJson.union "CliOperation" "CpuCount" []
 | LIR.SpawnProcess -> SemanticJson.union "CliOperation" "SpawnProcess" []
 | LIR.ProcessIO -> SemanticJson.union "CliOperation" "ProcessIO" []
 | LIR.TerminateProcess -> SemanticJson.union "CliOperation" "TerminateProcess" []
 | LIR.SocketTcp4 -> SemanticJson.union "CliOperation" "SocketTcp4" []
 | LIR.SocketTcp6 -> SemanticJson.union "CliOperation" "SocketTcp6" []
 | LIR.SocketUdp4 -> SemanticJson.union "CliOperation" "SocketUdp4" []
 | LIR.SocketUdp6 -> SemanticJson.union "CliOperation" "SocketUdp6" []
 | LIR.SocketConnect4 -> SemanticJson.union "CliOperation" "SocketConnect4" []
 | LIR.SocketConnect6 -> SemanticJson.union "CliOperation" "SocketConnect6" []
 | LIR.SocketSend -> SemanticJson.union "CliOperation" "SocketSend" []
 | LIR.SocketReceive -> SemanticJson.union "CliOperation" "SocketReceive" []
 | LIR.SocketReceiveTimeout -> SemanticJson.union "CliOperation" "SocketReceiveTimeout" []
 | LIR.SocketSendTimeout -> SemanticJson.union "CliOperation" "SocketSendTimeout" []
 | LIR.SocketClose -> SemanticJson.union "CliOperation" "SocketClose" []
 | LIR.SecureRandomFill -> SemanticJson.union "CliOperation" "SecureRandomFill" []
and label (value : LIR.label) = match value with
 | LIR.Label (field0) -> SemanticJson.union "Label" "Label" [SemanticJson.string field0]
and instr (value : LIR.instr) = match value with
 | LIR.Mov (field0, field1) -> SemanticJson.union "Instr" "Mov" [reg field0; operand field1]
 | LIR.Phi (field0, field1, field2) -> SemanticJson.union "Instr" "Phi" [reg field0; list (fun item -> (let part0, part1 = item in tuple [operand part0; label part1])) field1; option (fun item -> SemanticAST.semanticType item) field2]
 | LIR.Store (field0, field1) -> SemanticJson.union "Instr" "Store" [SemanticJson.int32 field0; reg field1]
 | LIR.Add (field0, field1, field2) -> SemanticJson.union "Instr" "Add" [reg field0; reg field1; operand field2]
 | LIR.Sub (field0, field1, field2) -> SemanticJson.union "Instr" "Sub" [reg field0; reg field1; operand field2]
 | LIR.Mul (field0, field1, field2) -> SemanticJson.union "Instr" "Mul" [reg field0; reg field1; reg field2]
 | LIR.Sdiv (field0, field1, field2) -> SemanticJson.union "Instr" "Sdiv" [reg field0; reg field1; reg field2]
 | LIR.Udiv (field0, field1, field2) -> SemanticJson.union "Instr" "Udiv" [reg field0; reg field1; reg field2]
 | LIR.Msub (field0, field1, field2, field3) -> SemanticJson.union "Instr" "Msub" [reg field0; reg field1; reg field2; reg field3]
 | LIR.Madd (field0, field1, field2, field3) -> SemanticJson.union "Instr" "Madd" [reg field0; reg field1; reg field2; reg field3]
 | LIR.Cmp (field0, field1) -> SemanticJson.union "Instr" "Cmp" [reg field0; operand field1]
 | LIR.Cset (field0, field1) -> SemanticJson.union "Instr" "Cset" [reg field0; condition field1]
 | LIR.Select (field0, field1, field2, field3) -> SemanticJson.union "Instr" "Select" [reg field0; reg field1; reg field2; condition field3]
 | LIR.And (field0, field1, field2) -> SemanticJson.union "Instr" "And" [reg field0; reg field1; reg field2]
 | LIR.And_imm (field0, field1, field2) -> SemanticJson.union "Instr" "And_imm" [reg field0; reg field1; int64 field2]
 | LIR.Orr (field0, field1, field2) -> SemanticJson.union "Instr" "Orr" [reg field0; reg field1; reg field2]
 | LIR.Eor (field0, field1, field2) -> SemanticJson.union "Instr" "Eor" [reg field0; reg field1; reg field2]
 | LIR.Lsl (field0, field1, field2) -> SemanticJson.union "Instr" "Lsl" [reg field0; reg field1; reg field2]
 | LIR.Lsr (field0, field1, field2) -> SemanticJson.union "Instr" "Lsr" [reg field0; reg field1; reg field2]
 | LIR.Asr (field0, field1, field2) -> SemanticJson.union "Instr" "Asr" [reg field0; reg field1; reg field2]
 | LIR.Lsl_imm (field0, field1, field2) -> SemanticJson.union "Instr" "Lsl_imm" [reg field0; reg field1; SemanticJson.int32 field2]
 | LIR.Lsr_imm (field0, field1, field2) -> SemanticJson.union "Instr" "Lsr_imm" [reg field0; reg field1; SemanticJson.int32 field2]
 | LIR.Asr_imm (field0, field1, field2) -> SemanticJson.union "Instr" "Asr_imm" [reg field0; reg field1; SemanticJson.int32 field2]
 | LIR.Neg (field0, field1) -> SemanticJson.union "Instr" "Neg" [reg field0; reg field1]
 | LIR.Mvn (field0, field1) -> SemanticJson.union "Instr" "Mvn" [reg field0; reg field1]
 | LIR.Sxtb (field0, field1) -> SemanticJson.union "Instr" "Sxtb" [reg field0; reg field1]
 | LIR.Sxth (field0, field1) -> SemanticJson.union "Instr" "Sxth" [reg field0; reg field1]
 | LIR.Sxtw (field0, field1) -> SemanticJson.union "Instr" "Sxtw" [reg field0; reg field1]
 | LIR.Uxtb (field0, field1) -> SemanticJson.union "Instr" "Uxtb" [reg field0; reg field1]
 | LIR.Uxth (field0, field1) -> SemanticJson.union "Instr" "Uxth" [reg field0; reg field1]
 | LIR.Uxtw (field0, field1) -> SemanticJson.union "Instr" "Uxtw" [reg field0; reg field1]
 | LIR.Call (field0, field1, field2) -> SemanticJson.union "Instr" "Call" [reg field0; functionId field1; list (fun item -> operand item) field2]
 | LIR.TailCall (field0, field1) -> SemanticJson.union "Instr" "TailCall" [functionId field0; list (fun item -> operand item) field1]
 | LIR.IndirectCall (field0, field1, field2) -> SemanticJson.union "Instr" "IndirectCall" [reg field0; reg field1; list (fun item -> operand item) field2]
 | LIR.IndirectTailCall (field0, field1) -> SemanticJson.union "Instr" "IndirectTailCall" [reg field0; list (fun item -> operand item) field1]
 | LIR.ClosureAlloc (field0, field1, field2) -> SemanticJson.union "Instr" "ClosureAlloc" [reg field0; functionId field1; list (fun item -> operand item) field2]
 | LIR.ClosureCall (field0, field1, field2) -> SemanticJson.union "Instr" "ClosureCall" [reg field0; reg field1; list (fun item -> operand item) field2]
 | LIR.ClosureTailCall (field0, field1) -> SemanticJson.union "Instr" "ClosureTailCall" [reg field0; list (fun item -> operand item) field1]
 | LIR.SaveRegs (field0, field1) -> SemanticJson.union "Instr" "SaveRegs" [list (fun item -> physReg item) field0; list (fun item -> physFPReg item) field1]
 | LIR.RestoreRegs (field0, field1) -> SemanticJson.union "Instr" "RestoreRegs" [list (fun item -> physReg item) field0; list (fun item -> physFPReg item) field1]
 | LIR.ArgMoves (field0) -> SemanticJson.union "Instr" "ArgMoves" [list (fun item -> (let part0, part1 = item in tuple [physReg part0; operand part1])) field0]
 | LIR.TailArgMoves (field0) -> SemanticJson.union "Instr" "TailArgMoves" [list (fun item -> (let part0, part1 = item in tuple [physReg part0; operand part1])) field0]
 | LIR.FArgMoves (field0) -> SemanticJson.union "Instr" "FArgMoves" [list (fun item -> (let part0, part1 = item in tuple [physFPReg part0; fReg part1])) field0]
 | LIR.PrintInt64 (field0) -> SemanticJson.union "Instr" "PrintInt64" [reg field0]
 | LIR.PrintUInt64 (field0) -> SemanticJson.union "Instr" "PrintUInt64" [reg field0]
 | LIR.PrintBool (field0) -> SemanticJson.union "Instr" "PrintBool" [reg field0]
 | LIR.PrintInt64NoNewline (field0) -> SemanticJson.union "Instr" "PrintInt64NoNewline" [reg field0]
 | LIR.PrintUInt64NoNewline (field0) -> SemanticJson.union "Instr" "PrintUInt64NoNewline" [reg field0]
 | LIR.PrintBoolNoNewline (field0) -> SemanticJson.union "Instr" "PrintBoolNoNewline" [reg field0]
 | LIR.PrintFloat (field0) -> SemanticJson.union "Instr" "PrintFloat" [fReg field0]
 | LIR.PrintFloatNoNewline (field0) -> SemanticJson.union "Instr" "PrintFloatNoNewline" [fReg field0]
 | LIR.PrintString (field0) -> SemanticJson.union "Instr" "PrintString" [SemanticJson.string field0]
 | LIR.StdoutWrite (field0, field1, field2) -> SemanticJson.union "Instr" "StdoutWrite" [SemanticJson.int32 field0; operand field1; boolean field2]
 | LIR.StdinReadLine (field0, field1) -> SemanticJson.union "Instr" "StdinReadLine" [SemanticJson.int32 field0; reg field1]
 | LIR.RuntimeError (field0) -> SemanticJson.union "Instr" "RuntimeError" [SemanticJson.string field0]
 | LIR.RuntimeErrorString (field0) -> SemanticJson.union "Instr" "RuntimeErrorString" [reg field0]
 | LIR.PrintHeapStringNoNewline (field0) -> SemanticJson.union "Instr" "PrintHeapStringNoNewline" [reg field0]
 | LIR.PrintChars (field0) -> SemanticJson.union "Instr" "PrintChars" [list (fun value -> scalar "uint8" (string_of_int value)) field0]
 | LIR.PrintBlob (field0) -> SemanticJson.union "Instr" "PrintBlob" [reg field0]
 | LIR.PrintList (field0, field1) -> SemanticJson.union "Instr" "PrintList" [reg field0; SemanticAST.semanticType field1]
 | LIR.PrintSum (field0, field1, field2) -> SemanticJson.union "Instr" "PrintSum" [reg field0; list (fun item -> (let part0, part1, part2 = item in tuple [SemanticJson.string part0; SemanticJson.int32 part1; option (fun item -> SemanticAST.semanticType item) part2])) field1; boolean field2]
 | LIR.PrintRecord (field0, field1, field2) -> SemanticJson.union "Instr" "PrintRecord" [reg field0; SemanticJson.string field1; list (fun item -> (let part0, part1 = item in tuple [SemanticJson.string part0; SemanticAST.semanticType part1])) field2]
 | LIR.Exit -> SemanticJson.union "Instr" "Exit" []
 | LIR.FPhi (field0, field1) -> SemanticJson.union "Instr" "FPhi" [fReg field0; list (fun item -> (let part0, part1 = item in tuple [fReg part0; label part1])) field1]
 | LIR.FMov (field0, field1) -> SemanticJson.union "Instr" "FMov" [fReg field0; fReg field1]
 | LIR.FLoad (field0, field1) -> SemanticJson.union "Instr" "FLoad" [fReg field0; float64 field1]
 | LIR.FSpillLoad (field0, field1) -> SemanticJson.union "Instr" "FSpillLoad" [fReg field0; SemanticJson.int32 field1]
 | LIR.FSpillStore (field0, field1) -> SemanticJson.union "Instr" "FSpillStore" [SemanticJson.int32 field0; fReg field1]
 | LIR.FAdd (field0, field1, field2) -> SemanticJson.union "Instr" "FAdd" [fReg field0; fReg field1; fReg field2]
 | LIR.FSub (field0, field1, field2) -> SemanticJson.union "Instr" "FSub" [fReg field0; fReg field1; fReg field2]
 | LIR.FMul (field0, field1, field2) -> SemanticJson.union "Instr" "FMul" [fReg field0; fReg field1; fReg field2]
 | LIR.FMadd (field0, field1, field2, field3) -> SemanticJson.union "Instr" "FMadd" [fReg field0; fReg field1; fReg field2; fReg field3]
 | LIR.FDiv (field0, field1, field2) -> SemanticJson.union "Instr" "FDiv" [fReg field0; fReg field1; fReg field2]
 | LIR.FNeg (field0, field1) -> SemanticJson.union "Instr" "FNeg" [fReg field0; fReg field1]
 | LIR.FAbs (field0, field1) -> SemanticJson.union "Instr" "FAbs" [fReg field0; fReg field1]
 | LIR.FSqrt (field0, field1) -> SemanticJson.union "Instr" "FSqrt" [fReg field0; fReg field1]
 | LIR.FCmp (field0, field1) -> SemanticJson.union "Instr" "FCmp" [fReg field0; fReg field1]
 | LIR.Int64ToFloat (field0, field1) -> SemanticJson.union "Instr" "Int64ToFloat" [fReg field0; reg field1]
 | LIR.FloatToInt64 (field0, field1) -> SemanticJson.union "Instr" "FloatToInt64" [reg field0; fReg field1]
 | LIR.FloatToBits (field0, field1) -> SemanticJson.union "Instr" "FloatToBits" [reg field0; fReg field1]
 | LIR.GpToFp (field0, field1) -> SemanticJson.union "Instr" "GpToFp" [fReg field0; reg field1]
 | LIR.FpToGp (field0, field1) -> SemanticJson.union "Instr" "FpToGp" [reg field0; fReg field1]
 | LIR.HeapAlloc (field0, field1) -> SemanticJson.union "Instr" "HeapAlloc" [reg field0; SemanticJson.int32 field1]
 | LIR.HeapStore (field0, field1, field2, field3) -> SemanticJson.union "Instr" "HeapStore" [reg field0; SemanticJson.int32 field1; operand field2; option (fun item -> SemanticAST.semanticType item) field3]
 | LIR.HeapLoad (field0, field1, field2) -> SemanticJson.union "Instr" "HeapLoad" [reg field0; reg field1; SemanticJson.int32 field2]
 | LIR.RefCountInc (field0, field1, field2, field3) -> SemanticJson.union "Instr" "RefCountInc" [reg field0; SemanticJson.int32 field1; rcKind field2; option (fun item -> ProductionANF.memoryModel_rcMetadata item) field3]
 | LIR.RefCountDec (field0, field1, field2, field3) -> SemanticJson.union "Instr" "RefCountDec" [reg field0; SemanticJson.int32 field1; rcKind field2; option (fun item -> ProductionANF.memoryModel_rcMetadata item) field3]
 | LIR.StringConcat (field0, field1, field2, field3) -> SemanticJson.union "Instr" "StringConcat" [reg field0; operand field1; operand field2; list (fun item -> operand item) field3]
 | LIR.CanonicalBufferEq (field0, field1, field2, field3) -> SemanticJson.union "Instr" "CanonicalBufferEq" [reg field0; ProductionANF.memoryModel_canonicalBufferKind field1; operand field2; operand field3]
 | LIR.PrintHeapString (field0) -> SemanticJson.union "Instr" "PrintHeapString" [reg field0]
 | LIR.LoadFuncAddr (field0, field1) -> SemanticJson.union "Instr" "LoadFuncAddr" [reg field0; functionId field1]
 | LIR.FileReadBlob (field0, field1) -> SemanticJson.union "Instr" "FileReadBlob" [reg field0; operand field1]
 | LIR.FileExists (field0, field1) -> SemanticJson.union "Instr" "FileExists" [reg field0; operand field1]
 | LIR.FileWriteBlob (field0, field1, field2) -> SemanticJson.union "Instr" "FileWriteBlob" [reg field0; operand field1; operand field2]
 | LIR.FileAppendText (field0, field1, field2) -> SemanticJson.union "Instr" "FileAppendText" [reg field0; operand field1; operand field2]
 | LIR.FileDelete (field0, field1) -> SemanticJson.union "Instr" "FileDelete" [reg field0; operand field1]
 | LIR.FileCreateDirectory (field0, field1) -> SemanticJson.union "Instr" "FileCreateDirectory" [reg field0; operand field1]
 | LIR.FileSetExecutable (field0, field1) -> SemanticJson.union "Instr" "FileSetExecutable" [reg field0; operand field1]
 | LIR.FileWriteFromPtr (field0, field1, field2, field3) -> SemanticJson.union "Instr" "FileWriteFromPtr" [reg field0; operand field1; reg field2; reg field3]
 | LIR.RawAlloc (field0, field1) -> SemanticJson.union "Instr" "RawAlloc" [reg field0; reg field1]
 | LIR.MappedAlloc (field0, field1) -> SemanticJson.union "Instr" "MappedAlloc" [reg field0; reg field1]
 | LIR.RawFree (field0) -> SemanticJson.union "Instr" "RawFree" [reg field0]
 | LIR.MappedFree (field0) -> SemanticJson.union "Instr" "MappedFree" [reg field0]
 | LIR.RawGet (field0, field1, field2) -> SemanticJson.union "Instr" "RawGet" [reg field0; reg field1; reg field2]
 | LIR.RawGetByte (field0, field1, field2) -> SemanticJson.union "Instr" "RawGetByte" [reg field0; reg field1; reg field2]
 | LIR.RawWriteWord (field0, field1, field2) -> SemanticJson.union "Instr" "RawWriteWord" [reg field0; reg field1; reg field2]
 | LIR.RawWriteByte (field0, field1, field2) -> SemanticJson.union "Instr" "RawWriteByte" [reg field0; reg field1; reg field2]
 | LIR.RawSlotInit (field0, field1, field2, field3) -> SemanticJson.union "Instr" "RawSlotInit" [reg field0; reg field1; reg field2; SemanticAST.semanticType field3]
 | LIR.RefCountIncString (field0) -> SemanticJson.union "Instr" "RefCountIncString" [operand field0]
 | LIR.RefCountDecString (field0) -> SemanticJson.union "Instr" "RefCountDecString" [operand field0]
 | LIR.RefCountIncBlob (field0) -> SemanticJson.union "Instr" "RefCountIncBlob" [operand field0]
 | LIR.RefCountDecBlob (field0) -> SemanticJson.union "Instr" "RefCountDecBlob" [operand field0]
 | LIR.RefCountIncInt (field0) -> SemanticJson.union "Instr" "RefCountIncInt" [operand field0]
 | LIR.RefCountDecInt (field0) -> SemanticJson.union "Instr" "RefCountDecInt" [operand field0]
 | LIR.RandomInt64 (field0) -> SemanticJson.union "Instr" "RandomInt64" [reg field0]
 | LIR.DateTimeNow (field0) -> SemanticJson.union "Instr" "DateTimeNow" [reg field0]
 | LIR.Sleep (field0, field1) -> SemanticJson.union "Instr" "Sleep" [SemanticJson.int32 field0; fReg field1]
 | LIR.CliNative (field0, field1, field2) -> SemanticJson.union "Instr" "CliNative" [reg field0; cliOperation field1; list (fun item -> operand item) field2]
 | LIR.FloatToString (field0, field1) -> SemanticJson.union "Instr" "FloatToString" [reg field0; fReg field1]
 | LIR.CoverageHit (field0) -> SemanticJson.union "Instr" "CoverageHit" [SemanticJson.int32 field0]
and terminator (value : LIR.terminator) = match value with
 | LIR.Ret -> SemanticJson.union "Terminator" "Ret" []
 | LIR.Branch (field0, field1, field2) -> SemanticJson.union "Terminator" "Branch" [reg field0; label field1; label field2]
 | LIR.BranchZero (field0, field1, field2) -> SemanticJson.union "Terminator" "BranchZero" [reg field0; label field1; label field2]
 | LIR.BranchBitZero (field0, field1, field2, field3) -> SemanticJson.union "Terminator" "BranchBitZero" [reg field0; SemanticJson.int32 field1; label field2; label field3]
 | LIR.BranchBitNonZero (field0, field1, field2, field3) -> SemanticJson.union "Terminator" "BranchBitNonZero" [reg field0; SemanticJson.int32 field1; label field2; label field3]
 | LIR.CondBranch (field0, field1, field2) -> SemanticJson.union "Terminator" "CondBranch" [condition field0; label field1; label field2]
 | LIR.Jump (field0) -> SemanticJson.union "Terminator" "Jump" [label field0]
and basicBlock (value : LIR.basicBlock) = SemanticJson.record "BasicBlock" ["Label", label value.LIR.label; "Instrs", list (fun item -> instr item) value.LIR.instrs; "Terminator", terminator value.LIR.terminator]
and cfg (value : LIR.cfg) = SemanticJson.record "CFG" ["Entry", label value.LIR.entry; "Blocks", `Assoc ["map", list (fun (key, item) -> tuple [(label) key; basicBlock item]) (LIR.LabelMap.bindings value.LIR.blocks)]]
and rcReleasePlanMemoKey (value : LIR.rcReleasePlanMemoKey) = match value with
 | LIR.FingerprintedReleasePlan (field0) -> SemanticJson.union "RcReleasePlanMemoKey" "FingerprintedReleasePlan" [SemanticJson.string field0]
 | LIR.StructuralReleasePlan (field0) -> SemanticJson.union "RcReleasePlanMemoKey" "StructuralReleasePlan" [option (fun item -> ProductionANF.memoryModel_rcReleasePlan item) field0]
and arm64ReleasePlanSummary (value : LIR.arm64ReleasePlanSummary) = SemanticJson.record "Arm64ReleasePlanSummary" ["ListDecHelperLabels", `Assoc ["set", list SemanticJson.string (StringOrder.Set.elements value.LIR.listDecHelperLabels)]; "PlannedListDecHelpers", `Assoc ["map", list (fun (key, item) -> tuple [(SemanticJson.string) key; (let part0, part1 = item in tuple [SemanticJson.int32 part0; ProductionANF.memoryModel_rcReleasePlan part1])]) (StringOrder.Map.bindings value.LIR.plannedListDecHelpers)]; "ExpensiveGenericDecHelper", option (fun item -> (let part0, part1, part2 = item in tuple [SemanticJson.string part0; SemanticJson.int32 part1; ProductionANF.memoryModel_rcReleasePlan part2])) value.LIR.expensiveGenericDecHelper; "DictDecHelperLabels", `Assoc ["set", list SemanticJson.string (StringOrder.Set.elements value.LIR.dictDecHelperLabels)]; "PlannedDictDecHelpers", `Assoc ["map", list (fun (key, item) -> tuple [(SemanticJson.string) key; ProductionANF.memoryModel_rcReleasePlan item]) (StringOrder.Map.bindings value.LIR.plannedDictDecHelpers)]; "NeedsClosureRcDecHelper", boolean value.LIR.needsClosureRcDecHelper; "NeedsStreamRcDecHelper", boolean value.LIR.needsStreamRcDecHelper]
and arm64PlannedGenericDecHelper (value : LIR.arm64PlannedGenericDecHelper) = SemanticJson.record "Arm64PlannedGenericDecHelper" ["ReleasePlanMemoKeys", `Assoc ["set", list rcReleasePlanMemoKey (LIR.RcReleasePlanMemoKeySet.elements value.LIR.releasePlanMemoKeys)]; "PayloadSize", SemanticJson.int32 value.LIR.payloadSize; "ReleasePlan", ProductionANF.memoryModel_rcReleasePlan value.LIR.releasePlan; "OwnsSinglePayloadSum", boolean value.LIR.ownsSinglePayloadSum]
and arm64RcHelperRequirements (value : LIR.arm64RcHelperRequirements) = SemanticJson.record "Arm64RcHelperRequirements" ["ListDecHelperLabels", `Assoc ["set", list SemanticJson.string (StringOrder.Set.elements value.LIR.listDecHelperLabels)]; "PlannedListDecHelpers", `Assoc ["map", list (fun (key, item) -> tuple [(SemanticJson.string) key; (let part0, part1 = item in tuple [SemanticJson.int32 part0; ProductionANF.memoryModel_rcReleasePlan part1])]) (StringOrder.Map.bindings value.LIR.plannedListDecHelpers)]; "PlannedGenericDecHelpers", `Assoc ["map", list (fun (key, item) -> tuple [(SemanticJson.string) key; arm64PlannedGenericDecHelper item]) (StringOrder.Map.bindings value.LIR.plannedGenericDecHelpers)]; "PlannedDictDecHelpers", `Assoc ["map", list (fun (key, item) -> tuple [(SemanticJson.string) key; ProductionANF.memoryModel_rcReleasePlan item]) (StringOrder.Map.bindings value.LIR.plannedDictDecHelpers)]; "DictDecHelperLabels", `Assoc ["set", list SemanticJson.string (StringOrder.Set.elements value.LIR.dictDecHelperLabels)]; "NeedsListRcIncHelper", boolean value.LIR.needsListRcIncHelper; "NeedsDictRcIncHelper", boolean value.LIR.needsDictRcIncHelper; "NeedsClosureRcIncHelper", boolean value.LIR.needsClosureRcIncHelper; "NeedsClosureRcDecHelper", boolean value.LIR.needsClosureRcDecHelper; "NeedsStreamRcDecHelper", boolean value.LIR.needsStreamRcDecHelper; "ReleasePlanSummaries", `Assoc ["map", list (fun (key, item) -> tuple [((fun (flag, key) -> tuple [boolean flag; rcReleasePlanMemoKey key])) key; arm64ReleasePlanSummary item]) (LIR.ReleasePlanSummaryMap.bindings value.LIR.releasePlanSummaries)]]
and arm64SlotInitRootRetainTarget (value : LIR.arm64SlotInitRootRetainTarget) = match value with
 | LIR.SlotInitListRootRetain -> SemanticJson.union "Arm64SlotInitRootRetainTarget" "SlotInitListRootRetain" []
 | LIR.SlotInitDictRootRetain -> SemanticJson.union "Arm64SlotInitRootRetainTarget" "SlotInitDictRootRetain" []
 | LIR.SlotInitDynamicBufferRetain -> SemanticJson.union "Arm64SlotInitRootRetainTarget" "SlotInitDynamicBufferRetain" []
 | LIR.SlotInitClosureRootRetain -> SemanticJson.union "Arm64SlotInitRootRetainTarget" "SlotInitClosureRootRetain" []
 | LIR.SlotInitGenericRootRetain (field0) -> SemanticJson.union "Arm64SlotInitRootRetainTarget" "SlotInitGenericRootRetain" [SemanticJson.int32 field0]
and functionCodegenFacts (value : LIR.functionCodegenFacts) = SemanticJson.record "FunctionCodegenFacts" ["Arm64UsedCalleeSavedF", list (fun item -> physFPReg item) value.LIR.arm64UsedCalleeSavedF; "ClosurePayloadSizeFromParams", option (fun item -> SemanticJson.int32 item) value.LIR.closurePayloadSizeFromParams; "ClosureCaptureTypes", option (fun item -> list (fun item -> SemanticAST.semanticType item) item) value.LIR.closureCaptureTypes; "ClosurePayloadSizesFromAllocs", list (fun item -> (let part0, part1 = item in tuple [functionId part0; SemanticJson.int32 part1])) value.LIR.closurePayloadSizesFromAllocs; "RecursiveReleaseTypes", `Assoc ["set", list SemanticAST.semanticType (MemoryPlanning.SemanticTypeSet.elements value.LIR.recursiveReleaseTypes)]; "RefCountDecRequirements", `Assoc ["map", list (fun (key, item) -> tuple [((fun (kind, key) -> tuple [rcKind kind; rcReleasePlanMemoKey key])) key; option (fun item -> ProductionANF.memoryModel_rcMetadata item) item]) (LIR.RefCountDecRequirementMap.bindings value.LIR.refCountDecRequirements)]; "RefCountIncRequirements", `Assoc ["set", list rcKind (LIR.RcKindSet.elements value.LIR.refCountIncRequirements)]; "RawSlotInitTypes", `Assoc ["set", list SemanticAST.semanticType (MemoryPlanning.SemanticTypeSet.elements value.LIR.rawSlotInitTypes)]; "Arm64RawSlotInitRetainTargets", option (fun item -> `Assoc ["map", list (fun (key, item) -> tuple [(SemanticAST.semanticType) key; option (fun item -> arm64SlotInitRootRetainTarget item) item]) (LIR.SemanticTypeMap.bindings item)]) value.LIR.arm64RawSlotInitRetainTargets; "NeedsCliRuntimeState", boolean value.LIR.needsCliRuntimeState; "NeedsCliArgvHelper", boolean value.LIR.needsCliArgvHelper; "NeedsCliExecuteHelper", boolean value.LIR.needsCliExecuteHelper; "NeedsCliRunProcessHelper", boolean value.LIR.needsCliRunProcessHelper; "NeedsCliProcessLifecycleHelpers", boolean value.LIR.needsCliProcessLifecycleHelpers; "NeedsRuntimeErrorHelper", boolean value.LIR.needsRuntimeErrorHelper; "Arm64RcHelperRequirements", option (fun item -> arm64RcHelperRequirements item) value.LIR.arm64RcHelperRequirements; "Arm64GenericHelperIds", `Assoc ["map", list (fun (key, item) -> tuple [(SemanticJson.string) key; functionId item]) (StringOrder.Map.bindings value.LIR.arm64GenericHelperIds)]]
and functionDef (value : LIR.functionDef) = SemanticJson.record "Function" ["Id", functionId value.LIR.id; "Name", SemanticJson.string value.LIR.name; "TypedParams", list (fun item -> typedLIRParam item) value.LIR.typedParams; "CFG", cfg value.LIR.cfg; "StackSize", SemanticJson.int32 value.LIR.stackSize; "UsedCalleeSaved", list (fun item -> physReg item) value.LIR.usedCalleeSaved; "CodegenFacts", option (fun item -> functionCodegenFacts item) value.LIR.codegenFacts]
and recordRegistry (value : LIR.recordRegistry) = `Assoc ["map", list (fun (key, item) -> tuple [(SemanticJson.string) key; list (fun item -> (let part0, part1 = item in tuple [SemanticJson.string part0; SemanticAST.semanticType part1])) item]) (StringOrder.Map.bindings value)]
and variantInfo (value : LIR.variantInfo) = SemanticJson.record "VariantInfo" ["Name", SemanticJson.string value.LIR.name; "Tag", SemanticJson.int32 value.LIR.tag; "Payload", option (fun item -> SemanticAST.semanticType item) value.LIR.payload; "FieldCount", SemanticJson.int32 value.LIR.fieldCount]
and typeVariants (value : LIR.typeVariants) = SemanticJson.record "TypeVariants" ["TypeParams", list (fun item -> SemanticJson.string item) value.LIR.typeParams; "Variants", list (fun item -> variantInfo item) value.LIR.variants]
and variantRegistry (value : LIR.variantRegistry) = `Assoc ["map", list (fun (key, item) -> tuple [(SemanticJson.string) key; typeVariants item]) (StringOrder.Map.bindings value)]
and program (value : LIR.program) = match value with
 | LIR.Program (field0, field1, field2) -> SemanticJson.union "Program" "Program" [list (fun item -> functionDef item) field0; variantRegistry field1; recordRegistry field2]
