(* Exhaustive typed memory/ANF migration encoders. *)
open Dark_compiler
let scalar kind value = `Assoc ["kind", `String kind; "value", `String value]
let tuple values = `Assoc ["tuple", `List values]
let list encode values = `List (List.map encode values)
let option encode = function None -> SemanticJson.union "FSharpOption" "None" [] | Some value -> SemanticJson.union "FSharpOption" "Some" [encode value]
let int32 value = scalar "int32" (string_of_int value)
let boolean value = `Bool value
let float64 value = scalar "float64" (Printf.sprintf "%016Lx" (Int64.bits_of_float value))
let unsigned value = Z.to_string (if value < 0L then Z.add (Z.of_int64 value) (Z.shift_left Z.one 64) else Z.of_int64 value)
let functionId value = SemanticJson.union "FunctionId" "FunctionId" [scalar "uint64" (unsigned (AST.functionIdValue value))]
let integerSet values = `Assoc ["set", list int32 (MemoryModel.IntSet.elements values)]
let coverageMap values = `Assoc ["map", list (fun (key, value) -> tuple [int32 key; SemanticJson.string value]) (ANF.ExprIdMap.bindings values)]
let stringMap encode values = `Assoc ["map", list (fun (key, value) -> tuple [SemanticJson.string key; encode value]) (StringOrder.Map.bindings values)]
let rec memoryModel_canonicalBufferKind (value : MemoryModel.canonicalBufferKind) = match value with
 | MemoryModel.Utf8String -> SemanticJson.union "CanonicalBufferKind" "Utf8String" []
 | MemoryModel.NullableUtf8String -> SemanticJson.union "CanonicalBufferKind" "NullableUtf8String" []
 | MemoryModel.GraphemeCluster -> SemanticJson.union "CanonicalBufferKind" "GraphemeCluster" []
 | MemoryModel.NullableGraphemeCluster -> SemanticJson.union "CanonicalBufferKind" "NullableGraphemeCluster" []
and memoryModel_rcKind (value : MemoryModel.rcKind) = match value with
 | MemoryModel.GenericHeap -> SemanticJson.union "RcKind" "GenericHeap" []
 | MemoryModel.StreamHeap -> SemanticJson.union "RcKind" "StreamHeap" []
 | MemoryModel.TaggedList -> SemanticJson.union "RcKind" "TaggedList" []
 | MemoryModel.DictHeap -> SemanticJson.union "RcKind" "DictHeap" []
 | MemoryModel.ClosureHeap -> SemanticJson.union "RcKind" "ClosureHeap" []
and memoryModel_rcShape (value : MemoryModel.rcShape) = match value with
 | MemoryModel.Immediate -> SemanticJson.union "RcShape" "Immediate" []
 | MemoryModel.FixedBlock (field0, field1) -> SemanticJson.union "RcShape" "FixedBlock" [int32 field0; list (fun item -> memoryModel_rcShape item) field1]
 | MemoryModel.StreamRoot -> SemanticJson.union "RcShape" "StreamRoot" []
 | MemoryModel.BoxedSum (field0, field1, field2) -> SemanticJson.union "RcShape" "BoxedSum" [int32 field0; list (fun item -> (let part0, part1 = item in tuple [int32 part0; memoryModel_rcShape part1])) field1; list (fun item -> memoryModel_rcBoxedSumVariantShape item) field2]
 | MemoryModel.RecursiveNominalRef (field0) -> SemanticJson.union "RcShape" "RecursiveNominalRef" [SemanticAST.semanticType field0]
 | MemoryModel.TaggedListShape (field0) -> SemanticJson.union "RcShape" "TaggedListShape" [memoryModel_rcShape field0]
 | MemoryModel.DictRoot (field0, field1) -> SemanticJson.union "RcShape" "DictRoot" [memoryModel_rcShape field0; memoryModel_rcShape field1]
 | MemoryModel.DynamicString -> SemanticJson.union "RcShape" "DynamicString" []
 | MemoryModel.DynamicBlob -> SemanticJson.union "RcShape" "DynamicBlob" []
 | MemoryModel.DynamicInt -> SemanticJson.union "RcShape" "DynamicInt" []
 | MemoryModel.ClosureShape (field0) -> SemanticJson.union "RcShape" "ClosureShape" [list (fun item -> memoryModel_rcShape item) field0]
 | MemoryModel.StaticString -> SemanticJson.union "RcShape" "StaticString" []
 | MemoryModel.RawUnmanaged -> SemanticJson.union "RcShape" "RawUnmanaged" []
and memoryModel_rcBoxedSumVariantShape (value : MemoryModel.rcBoxedSumVariantShape) = SemanticJson.record "RcBoxedSumVariantShape" ["Tag", int32 value.MemoryModel.tag; "FieldShapes", list (fun item -> (let part0, part1 = item in tuple [int32 part0; memoryModel_rcShape part1])) value.MemoryModel.fieldShapes]
and memoryModel_rcSumShapeInfo (value : MemoryModel.rcSumShapeInfo) = SemanticJson.record "RcSumShapeInfo" ["TypeParams", list (fun item -> SemanticJson.string item) value.MemoryModel.typeParams; "Payloads", list (fun item -> (let part0, part1 = item in tuple [int32 part0; option (fun item -> SemanticAST.semanticType item) part1])) value.MemoryModel.payloads; "UnaryPayloadTags", integerSet value.MemoryModel.unaryPayloadTags]
and memoryModel_rcSumShapeRegistry (value : MemoryModel.rcSumShapeRegistry) = stringMap (fun item -> memoryModel_rcSumShapeInfo item) value
and memoryModel_rcOperation (value : MemoryModel.rcOperation) = match value with
 | MemoryModel.FixedSizeRoot (field0, field1) -> SemanticJson.union "RcOperation" "FixedSizeRoot" [int32 field0; memoryModel_rcKind field1]
 | MemoryModel.DynamicStringBuffer -> SemanticJson.union "RcOperation" "DynamicStringBuffer" []
 | MemoryModel.DynamicBlobBuffer -> SemanticJson.union "RcOperation" "DynamicBlobBuffer" []
 | MemoryModel.DynamicIntBuffer -> SemanticJson.union "RcOperation" "DynamicIntBuffer" []
and memoryModel_rcStorageClass (value : MemoryModel.rcStorageClass) = match value with
 | MemoryModel.UnmanagedStorage -> SemanticJson.union "RcStorageClass" "UnmanagedStorage" []
 | MemoryModel.ManagedDynamicBuffer (field0) -> SemanticJson.union "RcStorageClass" "ManagedDynamicBuffer" [memoryModel_rcOperation field0]
 | MemoryModel.ManagedRcRoot (field0, field1) -> SemanticJson.union "RcStorageClass" "ManagedRcRoot" [int32 field0; memoryModel_rcKind field1]
and memoryModel_rcReleasePlan (value : MemoryModel.rcReleasePlan) = match value with
 | MemoryModel.NoReleasePlan -> SemanticJson.union "RcReleasePlan" "NoReleasePlan" []
 | MemoryModel.DynamicBufferRelease (field0) -> SemanticJson.union "RcReleasePlan" "DynamicBufferRelease" [memoryModel_rcOperation field0]
 | MemoryModel.RecursiveRelease (field0) -> SemanticJson.union "RcReleasePlan" "RecursiveRelease" [SemanticAST.semanticType field0]
 | MemoryModel.RootRelease (field0, field1, field2) -> SemanticJson.union "RcReleasePlan" "RootRelease" [int32 field0; memoryModel_rcKind field1; memoryModel_rcPayloadReleasePlan field2]
and memoryModel_rcPayloadReleasePlan (value : MemoryModel.rcPayloadReleasePlan) = match value with
 | MemoryModel.NoPayloadRelease -> SemanticJson.union "RcPayloadReleasePlan" "NoPayloadRelease" []
 | MemoryModel.FixedBlockPayloadRelease (field0, field1) -> SemanticJson.union "RcPayloadReleasePlan" "FixedBlockPayloadRelease" [int32 field0; list (fun item -> memoryModel_rcFieldRelease item) field1]
 | MemoryModel.BoxedSumPayloadRelease (field0, field1, field2) -> SemanticJson.union "RcPayloadReleasePlan" "BoxedSumPayloadRelease" [int32 field0; list (fun item -> memoryModel_rcFieldRelease item) field1; list (fun item -> memoryModel_rcBoxedSumVariantRelease item) field2]
 | MemoryModel.TaggedListPayloadRelease (field0) -> SemanticJson.union "RcPayloadReleasePlan" "TaggedListPayloadRelease" [memoryModel_rcReleasePlan field0]
 | MemoryModel.DictPayloadRelease (field0, field1) -> SemanticJson.union "RcPayloadReleasePlan" "DictPayloadRelease" [memoryModel_rcReleasePlan field0; memoryModel_rcReleasePlan field1]
 | MemoryModel.ClosurePayloadRelease (field0) -> SemanticJson.union "RcPayloadReleasePlan" "ClosurePayloadRelease" [list (fun item -> memoryModel_rcFieldRelease item) field0]
and memoryModel_rcFieldRelease (value : MemoryModel.rcFieldRelease) = match value with
 | MemoryModel.FieldRelease (field0, field1) -> SemanticJson.union "RcFieldRelease" "FieldRelease" [int32 field0; memoryModel_rcReleasePlan field1]
and memoryModel_rcBoxedSumVariantRelease (value : MemoryModel.rcBoxedSumVariantRelease) = SemanticJson.record "RcBoxedSumVariantRelease" ["Tag", int32 value.MemoryModel.tag; "FieldReleases", list (fun item -> memoryModel_rcFieldRelease item) value.MemoryModel.fieldReleases]
and memoryModel_rcMetadata (value : MemoryModel.rcMetadata) = SemanticJson.record "RcMetadata" ["ReleasePlanCacheKey", option (fun item -> SemanticJson.string item) value.MemoryModel.releasePlanCacheKey; "ReleasePlan", option (fun item -> memoryModel_rcReleasePlan item) value.MemoryModel.releasePlan; "SourceType", option (fun item -> SemanticAST.semanticType item) value.MemoryModel.sourceType]
and aNF_tempId (value : ANF.tempId) = match value with
 | ANF.TempId (field0) -> SemanticJson.union "TempId" "TempId" [int32 field0]
and aNF_typedParam (value : ANF.typedParam) = SemanticJson.record "TypedParam" ["Id", aNF_tempId value.ANF.id; "Type", SemanticAST.semanticType value.ANF.typ]
and aNF_sizedInt (value : ANF.sizedInt) = match value with
 | ANF.Int8 (field0) -> SemanticJson.union "SizedInt" "Int8" [scalar "int8" (string_of_int field0)]
 | ANF.Int16 (field0) -> SemanticJson.union "SizedInt" "Int16" [scalar "int16" (string_of_int field0)]
 | ANF.Int32 (field0) -> SemanticJson.union "SizedInt" "Int32" [scalar "int32" (Int32.to_string field0)]
 | ANF.Int64 (field0) -> SemanticJson.union "SizedInt" "Int64" [scalar "int64" (Int64.to_string field0)]
 | ANF.UInt8 (field0) -> SemanticJson.union "SizedInt" "UInt8" [scalar "uint8" (string_of_int field0)]
 | ANF.UInt16 (field0) -> SemanticJson.union "SizedInt" "UInt16" [scalar "uint16" (string_of_int field0)]
 | ANF.UInt32 (field0) -> SemanticJson.union "SizedInt" "UInt32" [scalar "uint32" (Int64.to_string field0)]
 | ANF.UInt64 (field0) -> SemanticJson.union "SizedInt" "UInt64" [scalar "uint64" (unsigned field0)]
and aNF_atom (value : ANF.atom) = match value with
 | ANF.UnitLiteral -> SemanticJson.union "Atom" "UnitLiteral" []
 | ANF.IntLiteral (field0) -> SemanticJson.union "Atom" "IntLiteral" [aNF_sizedInt field0]
 | ANF.BoolLiteral (field0) -> SemanticJson.union "Atom" "BoolLiteral" [boolean field0]
 | ANF.StringLiteral (field0) -> SemanticJson.union "Atom" "StringLiteral" [SemanticJson.string field0]
 | ANF.FloatLiteral (field0) -> SemanticJson.union "Atom" "FloatLiteral" [float64 field0]
 | ANF.Var (field0) -> SemanticJson.union "Atom" "Var" [aNF_tempId field0]
 | ANF.FuncRef (field0) -> SemanticJson.union "Atom" "FuncRef" [functionId field0]
and aNF_binOp (value : ANF.binOp) = match value with
 | ANF.Add -> SemanticJson.union "BinOp" "Add" []
 | ANF.Sub -> SemanticJson.union "BinOp" "Sub" []
 | ANF.Mul -> SemanticJson.union "BinOp" "Mul" []
 | ANF.Div -> SemanticJson.union "BinOp" "Div" []
 | ANF.Mod -> SemanticJson.union "BinOp" "Mod" []
 | ANF.Shl -> SemanticJson.union "BinOp" "Shl" []
 | ANF.Shr -> SemanticJson.union "BinOp" "Shr" []
 | ANF.BitAnd -> SemanticJson.union "BinOp" "BitAnd" []
 | ANF.BitOr -> SemanticJson.union "BinOp" "BitOr" []
 | ANF.BitXor -> SemanticJson.union "BinOp" "BitXor" []
 | ANF.Eq -> SemanticJson.union "BinOp" "Eq" []
 | ANF.Neq -> SemanticJson.union "BinOp" "Neq" []
 | ANF.Lt -> SemanticJson.union "BinOp" "Lt" []
 | ANF.Gt -> SemanticJson.union "BinOp" "Gt" []
 | ANF.Lte -> SemanticJson.union "BinOp" "Lte" []
 | ANF.Gte -> SemanticJson.union "BinOp" "Gte" []
 | ANF.And -> SemanticJson.union "BinOp" "And" []
 | ANF.Or -> SemanticJson.union "BinOp" "Or" []
and aNF_unaryOp (value : ANF.unaryOp) = match value with
 | ANF.Neg -> SemanticJson.union "UnaryOp" "Neg" []
 | ANF.Not -> SemanticJson.union "UnaryOp" "Not" []
 | ANF.BitNot -> SemanticJson.union "UnaryOp" "BitNot" []
and aNF_returnOwnership (value : ANF.returnOwnership) = match value with
 | ANF.OwnedReturn -> SemanticJson.union "ReturnOwnership" "OwnedReturn" []
 | ANF.BorrowedReturn -> SemanticJson.union "ReturnOwnership" "BorrowedReturn" []
and aNF_cliOperation (value : ANF.cliOperation) = match value with
 | ANF.Execute -> SemanticJson.union "CliOperation" "Execute" []
 | ANF.RunProcess -> SemanticJson.union "CliOperation" "RunProcess" []
 | ANF.HostOS -> SemanticJson.union "CliOperation" "HostOS" []
 | ANF.HostArchitecture -> SemanticJson.union "CliOperation" "HostArchitecture" []
 | ANF.Hostname -> SemanticJson.union "CliOperation" "Hostname" []
 | ANF.GetEnv -> SemanticJson.union "CliOperation" "GetEnv" []
 | ANF.GetEnvironmentPacked -> SemanticJson.union "CliOperation" "GetEnvironmentPacked" []
 | ANF.SetEnv -> SemanticJson.union "CliOperation" "SetEnv" []
 | ANF.UnsetEnv -> SemanticJson.union "CliOperation" "UnsetEnv" []
 | ANF.DirectoryCurrent -> SemanticJson.union "CliOperation" "DirectoryCurrent" []
 | ANF.DirectoryListPacked -> SemanticJson.union "CliOperation" "DirectoryListPacked" []
 | ANF.FileIsDirectory -> SemanticJson.union "CliOperation" "FileIsDirectory" []
 | ANF.FileCreateExclusive -> SemanticJson.union "CliOperation" "FileCreateExclusive" []
 | ANF.GetArgv -> SemanticJson.union "CliOperation" "GetArgv" []
 | ANF.Kill -> SemanticJson.union "CliOperation" "Kill" []
 | ANF.GetPid -> SemanticJson.union "CliOperation" "GetPid" []
 | ANF.GetUid -> SemanticJson.union "CliOperation" "GetUid" []
 | ANF.CpuCount -> SemanticJson.union "CliOperation" "CpuCount" []
 | ANF.SpawnProcess -> SemanticJson.union "CliOperation" "SpawnProcess" []
 | ANF.ProcessIO -> SemanticJson.union "CliOperation" "ProcessIO" []
 | ANF.TerminateProcess -> SemanticJson.union "CliOperation" "TerminateProcess" []
 | ANF.SocketTcp4 -> SemanticJson.union "CliOperation" "SocketTcp4" []
 | ANF.SocketTcp6 -> SemanticJson.union "CliOperation" "SocketTcp6" []
 | ANF.SocketUdp4 -> SemanticJson.union "CliOperation" "SocketUdp4" []
 | ANF.SocketUdp6 -> SemanticJson.union "CliOperation" "SocketUdp6" []
 | ANF.SocketConnect4 -> SemanticJson.union "CliOperation" "SocketConnect4" []
 | ANF.SocketConnect6 -> SemanticJson.union "CliOperation" "SocketConnect6" []
 | ANF.SocketSend -> SemanticJson.union "CliOperation" "SocketSend" []
 | ANF.SocketReceive -> SemanticJson.union "CliOperation" "SocketReceive" []
 | ANF.SocketReceiveTimeout -> SemanticJson.union "CliOperation" "SocketReceiveTimeout" []
 | ANF.SocketSendTimeout -> SemanticJson.union "CliOperation" "SocketSendTimeout" []
 | ANF.SocketClose -> SemanticJson.union "CliOperation" "SocketClose" []
 | ANF.SocketBind4 -> SemanticJson.union "CliOperation" "SocketBind4" []
 | ANF.SocketListen -> SemanticJson.union "CliOperation" "SocketListen" []
 | ANF.SocketAccept -> SemanticJson.union "CliOperation" "SocketAccept" []
 | ANF.SocketCloexec -> SemanticJson.union "CliOperation" "SocketCloexec" []
 | ANF.SocketReuseAddress -> SemanticJson.union "CliOperation" "SocketReuseAddress" []
 | ANF.SocketPoll -> SemanticJson.union "CliOperation" "SocketPoll" []
 | ANF.SignalBlock -> SemanticJson.union "CliOperation" "SignalBlock" []
 | ANF.SignalRestore -> SemanticJson.union "CliOperation" "SignalRestore" []
 | ANF.SignalPending -> SemanticJson.union "CliOperation" "SignalPending" []
 | ANF.SignalWait -> SemanticJson.union "CliOperation" "SignalWait" []
 | ANF.MonotonicTime -> SemanticJson.union "CliOperation" "MonotonicTime" []
 | ANF.SecureRandomFill -> SemanticJson.union "CliOperation" "SecureRandomFill" []
and aNF_recordDescriptor (value : ANF.recordDescriptor) = SemanticJson.record "RecordDescriptor" ["SourceTypeName", SemanticJson.string value.ANF.sourceTypeName; "RuntimeTypeName", SemanticJson.string value.ANF.runtimeTypeName; "TypeArgs", list (fun item -> SemanticAST.semanticType item) value.ANF.typeArgs; "Fields", list (fun item -> (let part0, part1 = item in tuple [SemanticJson.string part0; SemanticAST.semanticType part1])) value.ANF.fields; "ValueType", SemanticAST.semanticType value.ANF.valueType]
and aNF_cExpr (value : ANF.cExpr) = match value with
 | ANF.Atom (field0) -> SemanticJson.union "CExpr" "Atom" [aNF_atom field0]
 | ANF.TypedAtom (field0, field1) -> SemanticJson.union "CExpr" "TypedAtom" [aNF_atom field0; SemanticAST.semanticType field1]
 | ANF.Prim (field0, field1, field2) -> SemanticJson.union "CExpr" "Prim" [aNF_binOp field0; aNF_atom field1; aNF_atom field2]
 | ANF.UnaryPrim (field0, field1) -> SemanticJson.union "CExpr" "UnaryPrim" [aNF_unaryOp field0; aNF_atom field1]
 | ANF.IfValue (field0, field1, field2) -> SemanticJson.union "CExpr" "IfValue" [aNF_atom field0; aNF_atom field1; aNF_atom field2]
 | ANF.Call (field0, field1) -> SemanticJson.union "CExpr" "Call" [functionId field0; list (fun item -> aNF_atom item) field1]
 | ANF.BorrowedCall (field0, field1) -> SemanticJson.union "CExpr" "BorrowedCall" [functionId field0; list (fun item -> aNF_atom item) field1]
 | ANF.TailCall (field0, field1) -> SemanticJson.union "CExpr" "TailCall" [functionId field0; list (fun item -> aNF_atom item) field1]
 | ANF.IndirectCall (field0, field1) -> SemanticJson.union "CExpr" "IndirectCall" [aNF_atom field0; list (fun item -> aNF_atom item) field1]
 | ANF.IndirectTailCall (field0, field1) -> SemanticJson.union "CExpr" "IndirectTailCall" [aNF_atom field0; list (fun item -> aNF_atom item) field1]
 | ANF.ClosureAlloc (field0, field1) -> SemanticJson.union "CExpr" "ClosureAlloc" [functionId field0; list (fun item -> aNF_atom item) field1]
 | ANF.ClosureCall (field0, field1) -> SemanticJson.union "CExpr" "ClosureCall" [aNF_atom field0; list (fun item -> aNF_atom item) field1]
 | ANF.ClosureTailCall (field0, field1) -> SemanticJson.union "CExpr" "ClosureTailCall" [aNF_atom field0; list (fun item -> aNF_atom item) field1]
 | ANF.TupleAlloc (field0) -> SemanticJson.union "CExpr" "TupleAlloc" [list (fun item -> aNF_atom item) field0]
 | ANF.TupleGet (field0, field1) -> SemanticJson.union "CExpr" "TupleGet" [aNF_atom field0; int32 field1]
 | ANF.RecordAlloc (field0, field1) -> SemanticJson.union "CExpr" "RecordAlloc" [aNF_recordDescriptor field0; list (fun item -> aNF_atom item) field1]
 | ANF.RecordGet (field0, field1, field2) -> SemanticJson.union "CExpr" "RecordGet" [aNF_recordDescriptor field0; aNF_atom field1; int32 field2]
 | ANF.RecordClone (field0, field1, field2) -> SemanticJson.union "CExpr" "RecordClone" [aNF_recordDescriptor field0; aNF_atom field1; list (fun item -> aNF_atom item) field2]
 | ANF.RecordReuse (field0, field1, field2, field3) -> SemanticJson.union "CExpr" "RecordReuse" [aNF_recordDescriptor field0; aNF_recordDescriptor field1; aNF_atom field2; list (fun item -> aNF_atom item) field3]
 | ANF.StringConcat (field0, field1, field2) -> SemanticJson.union "CExpr" "StringConcat" [aNF_atom field0; aNF_atom field1; list (fun item -> aNF_atom item) field2]
 | ANF.CanonicalBufferEq (field0, field1, field2) -> SemanticJson.union "CExpr" "CanonicalBufferEq" [memoryModel_canonicalBufferKind field0; aNF_atom field1; aNF_atom field2]
 | ANF.RefCountInc (field0, field1, field2, field3) -> SemanticJson.union "CExpr" "RefCountInc" [aNF_atom field0; int32 field1; memoryModel_rcKind field2; option (fun item -> memoryModel_rcMetadata item) field3]
 | ANF.RefCountDec (field0, field1, field2, field3) -> SemanticJson.union "CExpr" "RefCountDec" [aNF_atom field0; int32 field1; memoryModel_rcKind field2; option (fun item -> memoryModel_rcMetadata item) field3]
 | ANF.Print (field0, field1) -> SemanticJson.union "CExpr" "Print" [aNF_atom field0; SemanticAST.semanticType field1]
 | ANF.StdoutWrite (field0, field1) -> SemanticJson.union "CExpr" "StdoutWrite" [aNF_atom field0; boolean field1]
 | ANF.StdinReadLine -> SemanticJson.union "CExpr" "StdinReadLine" []
 | ANF.RuntimeError (field0) -> SemanticJson.union "CExpr" "RuntimeError" [SemanticJson.string field0]
 | ANF.RuntimeErrorString (field0) -> SemanticJson.union "CExpr" "RuntimeErrorString" [aNF_atom field0]
 | ANF.FileReadBlob (field0) -> SemanticJson.union "CExpr" "FileReadBlob" [aNF_atom field0]
 | ANF.FileExists (field0) -> SemanticJson.union "CExpr" "FileExists" [aNF_atom field0]
 | ANF.FileWriteBlob (field0, field1) -> SemanticJson.union "CExpr" "FileWriteBlob" [aNF_atom field0; aNF_atom field1]
 | ANF.FileAppendText (field0, field1) -> SemanticJson.union "CExpr" "FileAppendText" [aNF_atom field0; aNF_atom field1]
 | ANF.FileDelete (field0) -> SemanticJson.union "CExpr" "FileDelete" [aNF_atom field0]
 | ANF.FileCreateDirectory (field0) -> SemanticJson.union "CExpr" "FileCreateDirectory" [aNF_atom field0]
 | ANF.FileSetExecutable (field0) -> SemanticJson.union "CExpr" "FileSetExecutable" [aNF_atom field0]
 | ANF.FileWriteFromPtr (field0, field1, field2) -> SemanticJson.union "CExpr" "FileWriteFromPtr" [aNF_atom field0; aNF_atom field1; aNF_atom field2]
 | ANF.FloatSqrt (field0) -> SemanticJson.union "CExpr" "FloatSqrt" [aNF_atom field0]
 | ANF.FloatAbs (field0) -> SemanticJson.union "CExpr" "FloatAbs" [aNF_atom field0]
 | ANF.FloatNeg (field0) -> SemanticJson.union "CExpr" "FloatNeg" [aNF_atom field0]
 | ANF.Int64ToFloat (field0) -> SemanticJson.union "CExpr" "Int64ToFloat" [aNF_atom field0]
 | ANF.FloatToInt64 (field0) -> SemanticJson.union "CExpr" "FloatToInt64" [aNF_atom field0]
 | ANF.FloatToBits (field0) -> SemanticJson.union "CExpr" "FloatToBits" [aNF_atom field0]
 | ANF.RawAlloc (field0) -> SemanticJson.union "CExpr" "RawAlloc" [aNF_atom field0]
 | ANF.MappedAlloc (field0) -> SemanticJson.union "CExpr" "MappedAlloc" [aNF_atom field0]
 | ANF.RawFree (field0) -> SemanticJson.union "CExpr" "RawFree" [aNF_atom field0]
 | ANF.MappedFree (field0) -> SemanticJson.union "CExpr" "MappedFree" [aNF_atom field0]
 | ANF.RawGet (field0, field1, field2) -> SemanticJson.union "CExpr" "RawGet" [aNF_atom field0; aNF_atom field1; option (fun item -> SemanticAST.semanticType item) field2]
 | ANF.RawTake (field0, field1, field2) -> SemanticJson.union "CExpr" "RawTake" [aNF_atom field0; aNF_atom field1; option (fun item -> SemanticAST.semanticType item) field2]
 | ANF.RawGetByte (field0, field1) -> SemanticJson.union "CExpr" "RawGetByte" [aNF_atom field0; aNF_atom field1]
 | ANF.RawWriteWord (field0, field1, field2) -> SemanticJson.union "CExpr" "RawWriteWord" [aNF_atom field0; aNF_atom field1; aNF_atom field2]
 | ANF.RawWriteByte (field0, field1, field2) -> SemanticJson.union "CExpr" "RawWriteByte" [aNF_atom field0; aNF_atom field1; aNF_atom field2]
 | ANF.RawSlotInit (field0, field1, field2, field3) -> SemanticJson.union "CExpr" "RawSlotInit" [aNF_atom field0; aNF_atom field1; aNF_atom field2; SemanticAST.semanticType field3]
 | ANF.StringToRawPtr (field0) -> SemanticJson.union "CExpr" "StringToRawPtr" [aNF_atom field0]
 | ANF.RawPtrToString (field0) -> SemanticJson.union "CExpr" "RawPtrToString" [aNF_atom field0]
 | ANF.BlobToRawPtr (field0) -> SemanticJson.union "CExpr" "BlobToRawPtr" [aNF_atom field0]
 | ANF.RawPtrToBlob (field0) -> SemanticJson.union "CExpr" "RawPtrToBlob" [aNF_atom field0]
 | ANF.RawPtrToInt128 (field0) -> SemanticJson.union "CExpr" "RawPtrToInt128" [aNF_atom field0]
 | ANF.RawPtrToUInt128 (field0) -> SemanticJson.union "CExpr" "RawPtrToUInt128" [aNF_atom field0]
 | ANF.DictToRawPtr (field0) -> SemanticJson.union "CExpr" "DictToRawPtr" [aNF_atom field0]
 | ANF.RawPtrToDict (field0, field1, field2) -> SemanticJson.union "CExpr" "RawPtrToDict" [aNF_atom field0; aNF_atom field1; SemanticAST.semanticType field2]
 | ANF.ListToRawPtr (field0) -> SemanticJson.union "CExpr" "ListToRawPtr" [aNF_atom field0]
 | ANF.FixedBlockToRawPtr (field0) -> SemanticJson.union "CExpr" "FixedBlockToRawPtr" [aNF_atom field0]
 | ANF.RawPtrToList (field0, field1, field2) -> SemanticJson.union "CExpr" "RawPtrToList" [aNF_atom field0; aNF_atom field1; SemanticAST.semanticType field2]
 | ANF.RefCountIncString (field0) -> SemanticJson.union "CExpr" "RefCountIncString" [aNF_atom field0]
 | ANF.RefCountDecString (field0) -> SemanticJson.union "CExpr" "RefCountDecString" [aNF_atom field0]
 | ANF.RefCountIncBlob (field0) -> SemanticJson.union "CExpr" "RefCountIncBlob" [aNF_atom field0]
 | ANF.RefCountDecBlob (field0) -> SemanticJson.union "CExpr" "RefCountDecBlob" [aNF_atom field0]
 | ANF.RefCountIncInt (field0) -> SemanticJson.union "CExpr" "RefCountIncInt" [aNF_atom field0]
 | ANF.RefCountDecInt (field0) -> SemanticJson.union "CExpr" "RefCountDecInt" [aNF_atom field0]
 | ANF.RandomInt64 -> SemanticJson.union "CExpr" "RandomInt64" []
 | ANF.DateTimeNow -> SemanticJson.union "CExpr" "DateTimeNow" []
 | ANF.Sleep (field0) -> SemanticJson.union "CExpr" "Sleep" [aNF_atom field0]
 | ANF.CliNative (field0, field1) -> SemanticJson.union "CExpr" "CliNative" [aNF_cliOperation field0; list (fun item -> aNF_atom item) field1]
 | ANF.FloatToString (field0) -> SemanticJson.union "CExpr" "FloatToString" [aNF_atom field0]
and aNF_aExpr (value : ANF.aExpr) = match value with
 | ANF.Let (field0, field1, field2) -> SemanticJson.union "AExpr" "Let" [aNF_tempId field0; aNF_cExpr field1; aNF_aExpr field2]
 | ANF.Return (field0) -> SemanticJson.union "AExpr" "Return" [aNF_atom field0]
 | ANF.If (field0, field1, field2) -> SemanticJson.union "AExpr" "If" [aNF_atom field0; aNF_aExpr field1; aNF_aExpr field2]
 | ANF.Join (field0, field1, field2) -> SemanticJson.union "AExpr" "Join" [aNF_typedParam field0; aNF_aExpr field1; aNF_aExpr field2]
 | ANF.Jump (field0, field1) -> SemanticJson.union "AExpr" "Jump" [aNF_tempId field0; aNF_atom field1]
and aNF_functionDef (value : ANF.functionDef) = SemanticJson.record "Function" ["Id", functionId value.ANF.id; "Name", SemanticJson.string value.ANF.name; "TypedParams", list (fun item -> aNF_typedParam item) value.ANF.typedParams; "ReturnType", SemanticAST.semanticType value.ANF.returnType; "ReturnOwnership", aNF_returnOwnership value.ANF.returnOwnership; "Body", aNF_aExpr value.ANF.body]
and aNF_program (value : ANF.program) = match value with
 | ANF.Program (field0, field1) -> SemanticJson.union "Program" "Program" [list (fun item -> aNF_functionDef item) field0; aNF_aExpr field1]
and aNF_varGen (value : ANF.varGen) = match value with
 | ANF.VarGen (field0) -> SemanticJson.union "VarGen" "VarGen" [int32 field0]
and aNF_exprId (value : ANF.exprId) = int32 value
and aNF_exprIdGen (value : ANF.exprIdGen) = match value with
 | ANF.ExprIdGen (field0) -> SemanticJson.union "ExprIdGen" "ExprIdGen" [int32 field0]
and aNF_coverageMapping (value : ANF.coverageMapping) = SemanticJson.record "CoverageMapping" ["Descriptions", coverageMap value.ANF.descriptions; "TotalExpressions", int32 value.ANF.totalExpressions]
