(* Exhaustive typed MIR encoders for migration observations. *)
[@@@warning "-4"]
open Dark_compiler
let scalar kind value = `Assoc ["kind", `String kind; "value", `String value]
let tuple values = `Assoc ["tuple", `List values]
let list encode values = `List (List.map encode values)
let option encode = function None -> SemanticJson.union "FSharpOption" "None" [] | Some value -> SemanticJson.union "FSharpOption" "Some" [encode value]
let int32 value = SemanticJson.int32 value
let int64 value = scalar "int64" (Int64.to_string value)
let float64 value = scalar "float64" (Printf.sprintf "%016Lx" (Int64.bits_of_float value))
let functionId value = SemanticJson.union "FunctionId" "FunctionId" [scalar "uint64" (Z.to_string (let value = Z.of_int64 (AST.functionIdValue value) in if Z.sign value < 0 then Z.add value (Z.shift_left Z.one 64) else value))]
let rec vReg (value : MIR.vReg) = match value with
 | MIR.VReg (field0) -> SemanticJson.union "VReg" "VReg" [int32 field0]
and typedMIRParam (value : MIR.typedMIRParam) = SemanticJson.record "TypedMIRParam" ["Reg", vReg value.MIR.reg; "Type", SemanticAST.semanticType value.MIR.typ]
and operand (value : MIR.operand) = match value with
 | MIR.Int64Const (field0) -> SemanticJson.union "Operand" "Int64Const" [int64 field0]
 | MIR.BoolConst (field0) -> SemanticJson.union "Operand" "BoolConst" [(fun value -> `Bool value) field0]
 | MIR.FloatSymbol (field0) -> SemanticJson.union "Operand" "FloatSymbol" [float64 field0]
 | MIR.StringSymbol (field0) -> SemanticJson.union "Operand" "StringSymbol" [SemanticJson.string field0]
 | MIR.Register (field0) -> SemanticJson.union "Operand" "Register" [vReg field0]
 | MIR.FuncAddr (field0) -> SemanticJson.union "Operand" "FuncAddr" [functionId field0]
and binOp (value : MIR.binOp) = match value with
 | MIR.Add -> SemanticJson.union "BinOp" "Add" []
 | MIR.Sub -> SemanticJson.union "BinOp" "Sub" []
 | MIR.Mul -> SemanticJson.union "BinOp" "Mul" []
 | MIR.Div -> SemanticJson.union "BinOp" "Div" []
 | MIR.Mod -> SemanticJson.union "BinOp" "Mod" []
 | MIR.Shl -> SemanticJson.union "BinOp" "Shl" []
 | MIR.Shr -> SemanticJson.union "BinOp" "Shr" []
 | MIR.BitAnd -> SemanticJson.union "BinOp" "BitAnd" []
 | MIR.BitOr -> SemanticJson.union "BinOp" "BitOr" []
 | MIR.BitXor -> SemanticJson.union "BinOp" "BitXor" []
 | MIR.Eq -> SemanticJson.union "BinOp" "Eq" []
 | MIR.Neq -> SemanticJson.union "BinOp" "Neq" []
 | MIR.Lt -> SemanticJson.union "BinOp" "Lt" []
 | MIR.Gt -> SemanticJson.union "BinOp" "Gt" []
 | MIR.Lte -> SemanticJson.union "BinOp" "Lte" []
 | MIR.Gte -> SemanticJson.union "BinOp" "Gte" []
 | MIR.And -> SemanticJson.union "BinOp" "And" []
 | MIR.Or -> SemanticJson.union "BinOp" "Or" []
and unaryOp (value : MIR.unaryOp) = match value with
 | MIR.Neg -> SemanticJson.union "UnaryOp" "Neg" []
 | MIR.Not -> SemanticJson.union "UnaryOp" "Not" []
 | MIR.BitNot -> SemanticJson.union "UnaryOp" "BitNot" []
and rcKind (value : MIR.rcKind) = match value with
 | MIR.GenericHeap -> SemanticJson.union "RcKind" "GenericHeap" []
 | MIR.StreamHeap -> SemanticJson.union "RcKind" "StreamHeap" []
 | MIR.TaggedList -> SemanticJson.union "RcKind" "TaggedList" []
 | MIR.DictHeap -> SemanticJson.union "RcKind" "DictHeap" []
 | MIR.ClosureHeap -> SemanticJson.union "RcKind" "ClosureHeap" []
and cliOperation (value : MIR.cliOperation) = match value with
 | MIR.Execute -> SemanticJson.union "CliOperation" "Execute" []
 | MIR.RunProcess -> SemanticJson.union "CliOperation" "RunProcess" []
 | MIR.HostOS -> SemanticJson.union "CliOperation" "HostOS" []
 | MIR.HostArchitecture -> SemanticJson.union "CliOperation" "HostArchitecture" []
 | MIR.Hostname -> SemanticJson.union "CliOperation" "Hostname" []
 | MIR.GetEnv -> SemanticJson.union "CliOperation" "GetEnv" []
 | MIR.GetEnvironmentPacked -> SemanticJson.union "CliOperation" "GetEnvironmentPacked" []
 | MIR.SetEnv -> SemanticJson.union "CliOperation" "SetEnv" []
 | MIR.UnsetEnv -> SemanticJson.union "CliOperation" "UnsetEnv" []
 | MIR.DirectoryCurrent -> SemanticJson.union "CliOperation" "DirectoryCurrent" []
 | MIR.DirectoryListPacked -> SemanticJson.union "CliOperation" "DirectoryListPacked" []
 | MIR.FileIsDirectory -> SemanticJson.union "CliOperation" "FileIsDirectory" []
 | MIR.FileCreateExclusive -> SemanticJson.union "CliOperation" "FileCreateExclusive" []
 | MIR.GetArgv -> SemanticJson.union "CliOperation" "GetArgv" []
 | MIR.Kill -> SemanticJson.union "CliOperation" "Kill" []
 | MIR.GetPid -> SemanticJson.union "CliOperation" "GetPid" []
 | MIR.GetUid -> SemanticJson.union "CliOperation" "GetUid" []
 | MIR.CpuCount -> SemanticJson.union "CliOperation" "CpuCount" []
 | MIR.SpawnProcess -> SemanticJson.union "CliOperation" "SpawnProcess" []
 | MIR.ProcessIO -> SemanticJson.union "CliOperation" "ProcessIO" []
 | MIR.TerminateProcess -> SemanticJson.union "CliOperation" "TerminateProcess" []
 | MIR.SocketTcp4 -> SemanticJson.union "CliOperation" "SocketTcp4" []
 | MIR.SocketTcp6 -> SemanticJson.union "CliOperation" "SocketTcp6" []
 | MIR.SocketUdp4 -> SemanticJson.union "CliOperation" "SocketUdp4" []
 | MIR.SocketUdp6 -> SemanticJson.union "CliOperation" "SocketUdp6" []
 | MIR.SocketConnect4 -> SemanticJson.union "CliOperation" "SocketConnect4" []
 | MIR.SocketConnect6 -> SemanticJson.union "CliOperation" "SocketConnect6" []
 | MIR.SocketSend -> SemanticJson.union "CliOperation" "SocketSend" []
 | MIR.SocketReceive -> SemanticJson.union "CliOperation" "SocketReceive" []
 | MIR.SocketReceiveTimeout -> SemanticJson.union "CliOperation" "SocketReceiveTimeout" []
 | MIR.SocketSendTimeout -> SemanticJson.union "CliOperation" "SocketSendTimeout" []
 | MIR.SocketClose -> SemanticJson.union "CliOperation" "SocketClose" []
 | MIR.SocketBind4 -> SemanticJson.union "CliOperation" "SocketBind4" []
 | MIR.SocketListen -> SemanticJson.union "CliOperation" "SocketListen" []
 | MIR.SocketAccept -> SemanticJson.union "CliOperation" "SocketAccept" []
 | MIR.SocketCloexec -> SemanticJson.union "CliOperation" "SocketCloexec" []
 | MIR.SocketReuseAddress -> SemanticJson.union "CliOperation" "SocketReuseAddress" []
 | MIR.SocketPoll -> SemanticJson.union "CliOperation" "SocketPoll" []
 | MIR.SignalBlock -> SemanticJson.union "CliOperation" "SignalBlock" []
 | MIR.SignalRestore -> SemanticJson.union "CliOperation" "SignalRestore" []
 | MIR.SignalPending -> SemanticJson.union "CliOperation" "SignalPending" []
 | MIR.SignalWait -> SemanticJson.union "CliOperation" "SignalWait" []
 | MIR.MonotonicTime -> SemanticJson.union "CliOperation" "MonotonicTime" []
 | MIR.SecureRandomFill -> SemanticJson.union "CliOperation" "SecureRandomFill" []
and label (value : MIR.label) = match value with
 | MIR.Label (field0) -> SemanticJson.union "Label" "Label" [SemanticJson.string field0]
and instr (value : MIR.instr) = match value with
 | MIR.Mov (field0, field1, field2) -> SemanticJson.union "Instr" "Mov" [vReg field0; operand field1; option (fun value -> SemanticAST.semanticType value) field2]
 | MIR.BinOp (field0, field1, field2, field3, field4) -> SemanticJson.union "Instr" "BinOp" [vReg field0; binOp field1; operand field2; operand field3; SemanticAST.semanticType field4]
 | MIR.UnaryOp (field0, field1, field2) -> SemanticJson.union "Instr" "UnaryOp" [vReg field0; unaryOp field1; operand field2]
 | MIR.Call (field0, field1, field2, field3, field4) -> SemanticJson.union "Instr" "Call" [vReg field0; functionId field1; list (fun value -> operand value) field2; list (fun value -> SemanticAST.semanticType value) field3; SemanticAST.semanticType field4]
 | MIR.TailCall (field0, field1, field2, field3) -> SemanticJson.union "Instr" "TailCall" [functionId field0; list (fun value -> operand value) field1; list (fun value -> SemanticAST.semanticType value) field2; SemanticAST.semanticType field3]
 | MIR.IndirectCall (field0, field1, field2, field3, field4) -> SemanticJson.union "Instr" "IndirectCall" [vReg field0; operand field1; list (fun value -> operand value) field2; list (fun value -> SemanticAST.semanticType value) field3; SemanticAST.semanticType field4]
 | MIR.IndirectTailCall (field0, field1, field2, field3) -> SemanticJson.union "Instr" "IndirectTailCall" [operand field0; list (fun value -> operand value) field1; list (fun value -> SemanticAST.semanticType value) field2; SemanticAST.semanticType field3]
 | MIR.ClosureAlloc (field0, field1, field2) -> SemanticJson.union "Instr" "ClosureAlloc" [vReg field0; functionId field1; list (fun value -> operand value) field2]
 | MIR.ClosureCall (field0, field1, field2, field3, field4) -> SemanticJson.union "Instr" "ClosureCall" [vReg field0; operand field1; list (fun value -> operand value) field2; list (fun value -> SemanticAST.semanticType value) field3; SemanticAST.semanticType field4]
 | MIR.ClosureTailCall (field0, field1, field2) -> SemanticJson.union "Instr" "ClosureTailCall" [operand field0; list (fun value -> operand value) field1; list (fun value -> SemanticAST.semanticType value) field2]
 | MIR.HeapAlloc (field0, field1) -> SemanticJson.union "Instr" "HeapAlloc" [vReg field0; int32 field1]
 | MIR.HeapStore (field0, field1, field2, field3) -> SemanticJson.union "Instr" "HeapStore" [vReg field0; int32 field1; operand field2; option (fun value -> SemanticAST.semanticType value) field3]
 | MIR.HeapLoad (field0, field1, field2, field3) -> SemanticJson.union "Instr" "HeapLoad" [vReg field0; vReg field1; int32 field2; option (fun value -> SemanticAST.semanticType value) field3]
 | MIR.StringConcat (field0, field1, field2, field3) -> SemanticJson.union "Instr" "StringConcat" [vReg field0; operand field1; operand field2; list (fun value -> operand value) field3]
 | MIR.CanonicalBufferEq (field0, field1, field2, field3) -> SemanticJson.union "Instr" "CanonicalBufferEq" [vReg field0; ProductionANF.memoryModel_canonicalBufferKind field1; operand field2; operand field3]
 | MIR.RefCountInc (field0, field1, field2, field3) -> SemanticJson.union "Instr" "RefCountInc" [vReg field0; int32 field1; rcKind field2; option (fun value -> ProductionANF.memoryModel_rcMetadata value) field3]
 | MIR.RefCountDec (field0, field1, field2, field3) -> SemanticJson.union "Instr" "RefCountDec" [vReg field0; int32 field1; rcKind field2; option (fun value -> ProductionANF.memoryModel_rcMetadata value) field3]
 | MIR.Print (field0, field1) -> SemanticJson.union "Instr" "Print" [operand field0; SemanticAST.semanticType field1]
 | MIR.StdoutWrite (field0, field1, field2) -> SemanticJson.union "Instr" "StdoutWrite" [int32 field0; operand field1; (fun value -> `Bool value) field2]
 | MIR.StdinReadLine (field0) -> SemanticJson.union "Instr" "StdinReadLine" [vReg field0]
 | MIR.RuntimeError (field0) -> SemanticJson.union "Instr" "RuntimeError" [SemanticJson.string field0]
 | MIR.RuntimeErrorString (field0) -> SemanticJson.union "Instr" "RuntimeErrorString" [operand field0]
 | MIR.FileReadBlob (field0, field1) -> SemanticJson.union "Instr" "FileReadBlob" [vReg field0; operand field1]
 | MIR.FileExists (field0, field1) -> SemanticJson.union "Instr" "FileExists" [vReg field0; operand field1]
 | MIR.FileWriteBlob (field0, field1, field2) -> SemanticJson.union "Instr" "FileWriteBlob" [vReg field0; operand field1; operand field2]
 | MIR.FileAppendText (field0, field1, field2) -> SemanticJson.union "Instr" "FileAppendText" [vReg field0; operand field1; operand field2]
 | MIR.FileDelete (field0, field1) -> SemanticJson.union "Instr" "FileDelete" [vReg field0; operand field1]
 | MIR.FileCreateDirectory (field0, field1) -> SemanticJson.union "Instr" "FileCreateDirectory" [vReg field0; operand field1]
 | MIR.FileSetExecutable (field0, field1) -> SemanticJson.union "Instr" "FileSetExecutable" [vReg field0; operand field1]
 | MIR.FileWriteFromPtr (field0, field1, field2, field3) -> SemanticJson.union "Instr" "FileWriteFromPtr" [vReg field0; operand field1; operand field2; operand field3]
 | MIR.FloatSqrt (field0, field1) -> SemanticJson.union "Instr" "FloatSqrt" [vReg field0; operand field1]
 | MIR.FloatAbs (field0, field1) -> SemanticJson.union "Instr" "FloatAbs" [vReg field0; operand field1]
 | MIR.FloatNeg (field0, field1) -> SemanticJson.union "Instr" "FloatNeg" [vReg field0; operand field1]
 | MIR.Int64ToFloat (field0, field1) -> SemanticJson.union "Instr" "Int64ToFloat" [vReg field0; operand field1]
 | MIR.FloatToInt64 (field0, field1) -> SemanticJson.union "Instr" "FloatToInt64" [vReg field0; operand field1]
 | MIR.FloatToBits (field0, field1) -> SemanticJson.union "Instr" "FloatToBits" [vReg field0; operand field1]
 | MIR.RawAlloc (field0, field1) -> SemanticJson.union "Instr" "RawAlloc" [vReg field0; operand field1]
 | MIR.MappedAlloc (field0, field1) -> SemanticJson.union "Instr" "MappedAlloc" [vReg field0; operand field1]
 | MIR.RawFree (field0) -> SemanticJson.union "Instr" "RawFree" [operand field0]
 | MIR.MappedFree (field0) -> SemanticJson.union "Instr" "MappedFree" [operand field0]
 | MIR.RawGet (field0, field1, field2, field3) -> SemanticJson.union "Instr" "RawGet" [vReg field0; operand field1; operand field2; option (fun value -> SemanticAST.semanticType value) field3]
 | MIR.RawGetByte (field0, field1, field2) -> SemanticJson.union "Instr" "RawGetByte" [vReg field0; operand field1; operand field2]
 | MIR.RawWriteWord (field0, field1, field2) -> SemanticJson.union "Instr" "RawWriteWord" [operand field0; operand field1; operand field2]
 | MIR.RawWriteByte (field0, field1, field2) -> SemanticJson.union "Instr" "RawWriteByte" [operand field0; operand field1; operand field2]
 | MIR.RawSlotInit (field0, field1, field2, field3) -> SemanticJson.union "Instr" "RawSlotInit" [operand field0; operand field1; operand field2; SemanticAST.semanticType field3]
 | MIR.StringToRawPtr (field0, field1) -> SemanticJson.union "Instr" "StringToRawPtr" [vReg field0; operand field1]
 | MIR.RawPtrToString (field0, field1) -> SemanticJson.union "Instr" "RawPtrToString" [vReg field0; operand field1]
 | MIR.BlobToRawPtr (field0, field1) -> SemanticJson.union "Instr" "BlobToRawPtr" [vReg field0; operand field1]
 | MIR.RawPtrToBlob (field0, field1) -> SemanticJson.union "Instr" "RawPtrToBlob" [vReg field0; operand field1]
 | MIR.DictToRawPtr (field0, field1) -> SemanticJson.union "Instr" "DictToRawPtr" [vReg field0; operand field1]
 | MIR.RawPtrToDict (field0, field1, field2) -> SemanticJson.union "Instr" "RawPtrToDict" [vReg field0; operand field1; operand field2]
 | MIR.ListToRawPtr (field0, field1) -> SemanticJson.union "Instr" "ListToRawPtr" [vReg field0; operand field1]
 | MIR.RawPtrToList (field0, field1, field2) -> SemanticJson.union "Instr" "RawPtrToList" [vReg field0; operand field1; operand field2]
 | MIR.RefCountIncString (field0) -> SemanticJson.union "Instr" "RefCountIncString" [operand field0]
 | MIR.RefCountDecString (field0) -> SemanticJson.union "Instr" "RefCountDecString" [operand field0]
 | MIR.RefCountIncBlob (field0) -> SemanticJson.union "Instr" "RefCountIncBlob" [operand field0]
 | MIR.RefCountDecBlob (field0) -> SemanticJson.union "Instr" "RefCountDecBlob" [operand field0]
 | MIR.RefCountIncInt (field0) -> SemanticJson.union "Instr" "RefCountIncInt" [operand field0]
 | MIR.RefCountDecInt (field0) -> SemanticJson.union "Instr" "RefCountDecInt" [operand field0]
 | MIR.RandomInt64 (field0) -> SemanticJson.union "Instr" "RandomInt64" [vReg field0]
 | MIR.DateTimeNow (field0) -> SemanticJson.union "Instr" "DateTimeNow" [vReg field0]
 | MIR.Sleep (field0, field1, field2) -> SemanticJson.union "Instr" "Sleep" [int32 field0; vReg field1; operand field2]
 | MIR.CliNative (field0, field1, field2) -> SemanticJson.union "Instr" "CliNative" [vReg field0; cliOperation field1; list (fun value -> operand value) field2]
 | MIR.FloatToString (field0, field1) -> SemanticJson.union "Instr" "FloatToString" [vReg field0; operand field1]
 | MIR.Phi (field0, field1, field2) -> SemanticJson.union "Instr" "Phi" [vReg field0; list (fun value -> (let part0, part1 = value in tuple [operand part0; label part1])) field1; option (fun value -> SemanticAST.semanticType value) field2]
 | MIR.CoverageHit (field0) -> SemanticJson.union "Instr" "CoverageHit" [int32 field0]
and terminator (value : MIR.terminator) = match value with
 | MIR.Ret (field0) -> SemanticJson.union "Terminator" "Ret" [operand field0]
 | MIR.Branch (field0, field1, field2) -> SemanticJson.union "Terminator" "Branch" [operand field0; label field1; label field2]
 | MIR.Jump (field0) -> SemanticJson.union "Terminator" "Jump" [label field0]
and basicBlock (value : MIR.basicBlock) = SemanticJson.record "BasicBlock" ["Label", label value.MIR.label; "Instrs", list (fun value -> instr value) value.MIR.instrs; "Terminator", terminator value.MIR.terminator]
and cfg (value : MIR.cfg) = SemanticJson.record "CFG" ["Entry", label value.MIR.entry; "Blocks", `Assoc ["map", list (fun (key, value) -> tuple [label key; basicBlock value]) (MIR.LabelMap.bindings value.MIR.blocks)]]
and functionDef (value : MIR.functionDef) = SemanticJson.record "Function" ["Id", functionId value.MIR.id; "Name", SemanticJson.string value.MIR.name; "TypedParams", list (fun value -> typedMIRParam value) value.MIR.typedParams; "ReturnType", SemanticAST.semanticType value.MIR.returnType; "CFG", cfg value.MIR.cfg; "FloatRegs", `Assoc ["set", list int32 (MIR.IntSet.elements value.MIR.floatRegs)]]
and variantInfo (value : MIR.variantInfo) = SemanticJson.record "VariantInfo" ["Name", SemanticJson.string value.MIR.name; "Tag", int32 value.MIR.tag; "Payload", option (fun value -> SemanticAST.semanticType value) value.MIR.payload; "FieldCount", int32 value.MIR.fieldCount]
and typeVariants (value : MIR.typeVariants) = SemanticJson.record "TypeVariants" ["TypeParams", list (fun value -> SemanticJson.string value) value.MIR.typeParams; "Variants", list (fun value -> variantInfo value) value.MIR.variants]
and recordField (value : MIR.recordField) = SemanticJson.record "RecordField" ["Name", SemanticJson.string value.MIR.name; "Type", SemanticAST.semanticType value.MIR.typ]
and variantRegistry (value : MIR.variantRegistry) = `Assoc ["map", list (fun (key, value) -> tuple [SemanticJson.string key; typeVariants value]) (StringOrder.Map.bindings value)]
and recordRegistry (value : MIR.recordRegistry) = `Assoc ["map", list (fun (key, value) -> tuple [SemanticJson.string key; list recordField value]) (StringOrder.Map.bindings value)]
and program (value : MIR.program) = match value with
 | MIR.Program (field0, field1, field2) -> SemanticJson.union "Program" "Program" [list (fun value -> functionDef value) field0; variantRegistry field1; recordRegistry field2]
and regGen (value : MIR.regGen) = match value with
 | MIR.RegGen (field0) -> SemanticJson.union "RegGen" "RegGen" [int32 field0]
and labelGen (value : MIR.labelGen) = match value with
 | MIR.LabelGen (field0) -> SemanticJson.union "LabelGen" "LabelGen" [int32 field0]
