(* SemanticJson.ml - Encode every semantic field with the frozen source names. *)
open Dark_compiler
open Tokenizer
let scalar kind value = `Assoc ["kind", `String kind; "value", `String value]
let union typ case fields = `Assoc ["type", `String typ; "case", `String case; "fields", `List fields]
let record name fields = `Assoc ["record", `String name; "fields", `List (List.map (fun (name, value) -> `List [`String name; value]) fields)]
let tuple values = `Assoc ["tuple", `List values]
let string value =
  let units = HostText.utf16Units value in
  let rec unpaired index =
    if index >= Array.length units then false
    else if units.(index) >= 0xd800 && units.(index) <= 0xdbff then
      if index + 1 < Array.length units && units.(index + 1) >= 0xdc00 && units.(index + 1) <= 0xdfff then unpaired (index + 2) else true
    else if units.(index) >= 0xdc00 && units.(index) <= 0xdfff then true
    else unpaired (index + 1) in
  if unpaired 0 then `Assoc ["utf16String", `List (Array.to_list (Array.map (fun unit -> `String (Printf.sprintf "%04x" unit)) units))]
  else `String value
let option encode = function None -> union "FSharpOption" "None" [] | Some value -> union "FSharpOption" "Some" [encode value]
let int32 value = scalar "int32" (string_of_int value)
let unsigned64 value = if value < 0L then Z.add (Z.of_int64 value) (Z.shift_left Z.one 64) |> Z.to_string else Int64.to_string value
let token value =
  match value with
  | TInt value -> union "Token" "TInt" [scalar "bigint" (Z.to_string value)]
  | TInt64 value -> union "Token" "TInt64" [scalar "int64" (Int64.to_string value)]
  | TInt128 value -> union "Token" "TInt128" [scalar "int128" (Z.to_string value)]
  | TInt8 value -> union "Token" "TInt8" [scalar "int8" (string_of_int value)]
  | TInt16 value -> union "Token" "TInt16" [scalar "int16" (string_of_int value)]
  | TInt32 value -> union "Token" "TInt32" [scalar "int32" (Int32.to_string value)]
  | TUInt8 value -> union "Token" "TUInt8" [scalar "uint8" (string_of_int value)]
  | TUInt16 value -> union "Token" "TUInt16" [scalar "uint16" (string_of_int value)]
  | TUInt32 value -> union "Token" "TUInt32" [scalar "uint32" (Int64.to_string value)]
  | TUInt64 value -> union "Token" "TUInt64" [scalar "uint64" (unsigned64 value)]
  | TUInt128 value -> union "Token" "TUInt128" [scalar "uint128" (Z.to_string value)]
  | TFloat value -> union "Token" "TFloat" [scalar "float64" (Printf.sprintf "%016Lx" (Int64.bits_of_float value))]
  | TStringLit value -> union "Token" "TStringLit" [string value]
  | TCharLit value -> union "Token" "TCharLit" [string value]
  | TInterpString -> union "Token" "TInterpString" []
  | TTrue -> union "Token" "TTrue" []
  | TFalse -> union "Token" "TFalse" []
  | TPlus -> union "Token" "TPlus" []
  | TPlusPlus -> union "Token" "TPlusPlus" []
  | TMinus -> union "Token" "TMinus" []
  | TStar -> union "Token" "TStar" []
  | TStarStar -> union "Token" "TStarStar" []
  | TSlash -> union "Token" "TSlash" []
  | TLParen -> union "Token" "TLParen" []
  | TRParen -> union "Token" "TRParen" []
  | TLet -> union "Token" "TLet" []
  | TVal -> union "Token" "TVal" []
  | TIn -> union "Token" "TIn" []
  | TIf -> union "Token" "TIf" []
  | TElif -> union "Token" "TElif" []
  | TThen -> union "Token" "TThen" []
  | TElse -> union "Token" "TElse" []
  | TType -> union "Token" "TType" []
  | TCons -> union "Token" "TCons" []
  | TColon -> union "Token" "TColon" []
  | TComma -> union "Token" "TComma" []
  | TSemicolon -> union "Token" "TSemicolon" []
  | TDot -> union "Token" "TDot" []
  | TLBrace -> union "Token" "TLBrace" []
  | TRBrace -> union "Token" "TRBrace" []
  | TBar -> union "Token" "TBar" []
  | TOf -> union "Token" "TOf" []
  | TMatch -> union "Token" "TMatch" []
  | TWith -> union "Token" "TWith" []
  | TFun -> union "Token" "TFun" []
  | TArrow -> union "Token" "TArrow" []
  | TUnderscore -> union "Token" "TUnderscore" []
  | TWhen -> union "Token" "TWhen" []
  | TLBracket -> union "Token" "TLBracket" []
  | TRBracket -> union "Token" "TRBracket" []
  | TEquals -> union "Token" "TEquals" []
  | TEqEq -> union "Token" "TEqEq" []
  | TNeq -> union "Token" "TNeq" []
  | TLt -> union "Token" "TLt" []
  | TGt -> union "Token" "TGt" []
  | TLte -> union "Token" "TLte" []
  | TGte -> union "Token" "TGte" []
  | TAnd -> union "Token" "TAnd" []
  | TOr -> union "Token" "TOr" []
  | TNot -> union "Token" "TNot" []
  | TPipe -> union "Token" "TPipe" []
  | TDotDotDot -> union "Token" "TDotDotDot" []
  | TPercent -> union "Token" "TPercent" []
  | TShl -> union "Token" "TShl" []
  | TShr -> union "Token" "TShr" []
  | TBitAnd -> union "Token" "TBitAnd" []
  | TBitXor -> union "Token" "TBitXor" []
  | TBitNot -> union "Token" "TBitNot" []
  | TAt -> union "Token" "TAt" []
  | TIdent value -> union "Token" "TIdent" [string value]
  | TEOF -> union "Token" "TEOF" []
let pos (value : Tokenizer.pos) = record "Pos" ["row", int32 value.row; "column", int32 value.column]
let range (value : Tokenizer.tokenRange) = record "TokenRange" ["start", pos value.start; "end_", pos value.end_]
let triviaKind = function Lexer.LineComment -> union "TriviaKind" "LineComment" [] | Lexer.DocComment -> union "TriviaKind" "DocComment" [] | Lexer.BlockComment -> union "TriviaKind" "BlockComment" []
let trivia (value : Lexer.trivia) = record "Trivia" ["kind", triviaKind value.Lexer.kind; "text", string value.Lexer.text; "range", range value.Lexer.range]
let spanned (value : Lexer.spannedToken) = record "SpannedToken" ["token", token value.Lexer.token; "text", string value.Lexer.text; "range", range value.Lexer.range; "docComment", option string value.Lexer.docComment; "leadingTrivia", `List (List.map trivia value.Lexer.leadingTrivia)]
let tokens = function
  | Error error -> union "FSharpResult" "Error" [string error]
  | Ok (tokens, diagnostics) -> union "FSharpResult" "Ok" [tuple [`List (List.map spanned tokens); `List (List.map (fun (location, message) -> tuple [range location; string message]) diagnostics)]]
