(* Exhaustive typed memory/ANF migration encoders. *)
open Dark_compiler
let scalar kind value = `Assoc ["kind", `String kind; "value", `String value]
let tuple values = `Assoc ["tuple", `List values]
let list encode values = `List (List.map encode values)
let array encode values = `List (Array.to_list (Array.map encode values))
let option encode = function None -> SemanticJson.union "FSharpOption" "None" [] | Some value -> SemanticJson.union "FSharpOption" "Some" [encode value]
let int32 value = scalar "int32" (string_of_int value)
let boolean value = `Bool value
let float64 value = scalar "float64" (Printf.sprintf "%016Lx" (Int64.bits_of_float value))
let unsigned value = Z.to_string (if value < 0L then Z.add (Z.of_int64 value) (Z.shift_left Z.one 64) else Z.of_int64 value)
let functionId value = SemanticJson.union "FunctionId" "FunctionId" [scalar "uint64" (unsigned (AST.functionIdValue value))]
let integerSet values = `Assoc ["set", list int32 (MemoryModel.IntSet.elements values)]
let coverageMap values = `Assoc ["map", list (fun (key, value) -> tuple [int32 key; SemanticJson.string value]) (InstrumentedANF.ExprIdMap.bindings values)]
let stringMap encode values = `Assoc ["map", list (fun (key, value) -> tuple [SemanticJson.string key; encode value]) (StringOrder.Map.bindings values)]
let rec memoryModel_canonicalBufferKind (value : MemoryModel.canonicalBufferKind) = match value with
 | MemoryModel.Utf8String -> SemanticJson.union "CanonicalBufferKind" "Utf8String" []
 | MemoryModel.NullableUtf8String -> SemanticJson.union "CanonicalBufferKind" "NullableUtf8String" []
 | MemoryModel.GraphemeCluster -> SemanticJson.union "CanonicalBufferKind" "GraphemeCluster" []
 | MemoryModel.NullableGraphemeCluster -> SemanticJson.union "CanonicalBufferKind" "NullableGraphemeCluster" []
and memoryModel_rcKind (value : MemoryModel.rcKind) = match value with
 | MemoryModel.GenericHeap -> SemanticJson.union "RcKind" "GenericHeap" []
 | MemoryModel.StreamHeap -> SemanticJson.union "RcKind" "StreamHeap" []
 | MemoryModel.TaggedList -> SemanticJson.union "RcKind" "TaggedList" []
 | MemoryModel.DictHeap -> SemanticJson.union "RcKind" "DictHeap" []
 | MemoryModel.ClosureHeap -> SemanticJson.union "RcKind" "ClosureHeap" []
and memoryModel_rcShape (value : MemoryModel.rcShape) = match value with
 | MemoryModel.Immediate -> SemanticJson.union "RcShape" "Immediate" []
 | MemoryModel.FixedBlock (field0, field1) -> SemanticJson.union "RcShape" "FixedBlock" [int32 field0; list (fun item -> memoryModel_rcShape item) field1]
 | MemoryModel.StreamRoot -> SemanticJson.union "RcShape" "StreamRoot" []
 | MemoryModel.BoxedSum (field0, field1, field2) -> SemanticJson.union "RcShape" "BoxedSum" [int32 field0; list (fun item -> (let part0, part1 = item in tuple [int32 part0; memoryModel_rcShape part1])) field1; list (fun item -> memoryModel_rcBoxedSumVariantShape item) field2]
 | MemoryModel.RecursiveNominalRef (field0) -> SemanticJson.union "RcShape" "RecursiveNominalRef" [SemanticAST.semanticType field0]
 | MemoryModel.TaggedListShape (field0) -> SemanticJson.union "RcShape" "TaggedListShape" [memoryModel_rcShape field0]
 | MemoryModel.DictRoot (field0, field1) -> SemanticJson.union "RcShape" "DictRoot" [memoryModel_rcShape field0; memoryModel_rcShape field1]
 | MemoryModel.DynamicString -> SemanticJson.union "RcShape" "DynamicString" []
 | MemoryModel.DynamicBlob -> SemanticJson.union "RcShape" "DynamicBlob" []
 | MemoryModel.DynamicInt -> SemanticJson.union "RcShape" "DynamicInt" []
 | MemoryModel.ClosureShape (field0) -> SemanticJson.union "RcShape" "ClosureShape" [list (fun item -> memoryModel_rcShape item) field0]
 | MemoryModel.StaticString -> SemanticJson.union "RcShape" "StaticString" []
 | MemoryModel.RawUnmanaged -> SemanticJson.union "RcShape" "RawUnmanaged" []
and memoryModel_rcBoxedSumVariantShape (value : MemoryModel.rcBoxedSumVariantShape) = SemanticJson.record "RcBoxedSumVariantShape" ["Tag", int32 value.MemoryModel.tag; "FieldShapes", list (fun item -> (let part0, part1 = item in tuple [int32 part0; memoryModel_rcShape part1])) value.MemoryModel.fieldShapes]
and memoryModel_rcSumShapeInfo (value : MemoryModel.rcSumShapeInfo) = SemanticJson.record "RcSumShapeInfo" ["TypeParams", list (fun item -> SemanticJson.string item) value.MemoryModel.typeParams; "Payloads", list (fun item -> (let part0, part1 = item in tuple [int32 part0; option (fun item -> SemanticAST.semanticType item) part1])) value.MemoryModel.payloads; "UnaryPayloadTags", integerSet value.MemoryModel.unaryPayloadTags]
and memoryModel_rcSumShapeRegistry (value : MemoryModel.rcSumShapeRegistry) = stringMap (fun item -> memoryModel_rcSumShapeInfo item) value
and memoryModel_rcOperation (value : MemoryModel.rcOperation) = match value with
 | MemoryModel.FixedSizeRoot (field0, field1) -> SemanticJson.union "RcOperation" "FixedSizeRoot" [int32 field0; memoryModel_rcKind field1]
 | MemoryModel.DynamicStringBuffer -> SemanticJson.union "RcOperation" "DynamicStringBuffer" []
 | MemoryModel.DynamicBlobBuffer -> SemanticJson.union "RcOperation" "DynamicBlobBuffer" []
 | MemoryModel.DynamicIntBuffer -> SemanticJson.union "RcOperation" "DynamicIntBuffer" []
and memoryModel_rcStorageClass (value : MemoryModel.rcStorageClass) = match value with
 | MemoryModel.UnmanagedStorage -> SemanticJson.union "RcStorageClass" "UnmanagedStorage" []
 | MemoryModel.ManagedDynamicBuffer (field0) -> SemanticJson.union "RcStorageClass" "ManagedDynamicBuffer" [memoryModel_rcOperation field0]
 | MemoryModel.ManagedRcRoot (field0, field1) -> SemanticJson.union "RcStorageClass" "ManagedRcRoot" [int32 field0; memoryModel_rcKind field1]
and memoryModel_rcReleasePlan (value : MemoryModel.rcReleasePlan) = match value with
 | MemoryModel.NoReleasePlan -> SemanticJson.union "RcReleasePlan" "NoReleasePlan" []
 | MemoryModel.DynamicBufferRelease (field0) -> SemanticJson.union "RcReleasePlan" "DynamicBufferRelease" [memoryModel_rcOperation field0]
 | MemoryModel.RecursiveRelease (field0) -> SemanticJson.union "RcReleasePlan" "RecursiveRelease" [SemanticAST.semanticType field0]
 | MemoryModel.RootRelease (field0, field1, field2) -> SemanticJson.union "RcReleasePlan" "RootRelease" [int32 field0; memoryModel_rcKind field1; memoryModel_rcPayloadReleasePlan field2]
and memoryModel_rcPayloadReleasePlan (value : MemoryModel.rcPayloadReleasePlan) = match value with
 | MemoryModel.NoPayloadRelease -> SemanticJson.union "RcPayloadReleasePlan" "NoPayloadRelease" []
 | MemoryModel.FixedBlockPayloadRelease (field0, field1) -> SemanticJson.union "RcPayloadReleasePlan" "FixedBlockPayloadRelease" [int32 field0; list (fun item -> memoryModel_rcFieldRelease item) field1]
 | MemoryModel.BoxedSumPayloadRelease (field0, field1, field2) -> SemanticJson.union "RcPayloadReleasePlan" "BoxedSumPayloadRelease" [int32 field0; list (fun item -> memoryModel_rcFieldRelease item) field1; list (fun item -> memoryModel_rcBoxedSumVariantRelease item) field2]
 | MemoryModel.TaggedListPayloadRelease (field0) -> SemanticJson.union "RcPayloadReleasePlan" "TaggedListPayloadRelease" [memoryModel_rcReleasePlan field0]
 | MemoryModel.DictPayloadRelease (field0, field1) -> SemanticJson.union "RcPayloadReleasePlan" "DictPayloadRelease" [memoryModel_rcReleasePlan field0; memoryModel_rcReleasePlan field1]
 | MemoryModel.ClosurePayloadRelease (field0) -> SemanticJson.union "RcPayloadReleasePlan" "ClosurePayloadRelease" [list (fun item -> memoryModel_rcFieldRelease item) field0]
and memoryModel_rcFieldRelease (value : MemoryModel.rcFieldRelease) = match value with
 | MemoryModel.FieldRelease (field0, field1) -> SemanticJson.union "RcFieldRelease" "FieldRelease" [int32 field0; memoryModel_rcReleasePlan field1]
and memoryModel_rcBoxedSumVariantRelease (value : MemoryModel.rcBoxedSumVariantRelease) = SemanticJson.record "RcBoxedSumVariantRelease" ["Tag", int32 value.MemoryModel.tag; "FieldReleases", list (fun item -> memoryModel_rcFieldRelease item) value.MemoryModel.fieldReleases]
and memoryModel_rcMetadata (value : MemoryModel.rcMetadata) = SemanticJson.record "RcMetadata" ["ReleasePlanCacheKey", option (fun item -> SemanticJson.string item) value.MemoryModel.releasePlanCacheKey; "ReleasePlan", option (fun item -> memoryModel_rcReleasePlan item) value.MemoryModel.releasePlan; "SourceType", option (fun item -> SemanticAST.semanticType item) value.MemoryModel.sourceType]
and aNF_tempId (value : InstrumentedANF.tempId) = match value with
 | InstrumentedANF.TempId (field0) -> SemanticJson.union "TempId" "TempId" [int32 field0]
and aNF_typedParam (value : InstrumentedANF.typedParam) = SemanticJson.record "TypedParam" ["Id", aNF_tempId value.InstrumentedANF.id; "Type", SemanticAST.semanticType value.InstrumentedANF.typ]
and aNF_sizedInt (value : InstrumentedANF.sizedInt) = match value with
 | InstrumentedANF.Int8 (field0) -> SemanticJson.union "SizedInt" "Int8" [scalar "int8" (string_of_int field0)]
 | InstrumentedANF.Int16 (field0) -> SemanticJson.union "SizedInt" "Int16" [scalar "int16" (string_of_int field0)]
 | InstrumentedANF.Int32 (field0) -> SemanticJson.union "SizedInt" "Int32" [scalar "int32" (Int32.to_string field0)]
 | InstrumentedANF.Int64 (field0) -> SemanticJson.union "SizedInt" "Int64" [scalar "int64" (Int64.to_string field0)]
 | InstrumentedANF.UInt8 (field0) -> SemanticJson.union "SizedInt" "UInt8" [scalar "uint8" (string_of_int field0)]
 | InstrumentedANF.UInt16 (field0) -> SemanticJson.union "SizedInt" "UInt16" [scalar "uint16" (string_of_int field0)]
 | InstrumentedANF.UInt32 (field0) -> SemanticJson.union "SizedInt" "UInt32" [scalar "uint32" (Int64.to_string field0)]
 | InstrumentedANF.UInt64 (field0) -> SemanticJson.union "SizedInt" "UInt64" [scalar "uint64" (unsigned field0)]
and aNF_atom (value : InstrumentedANF.atom) = match value with
 | InstrumentedANF.UnitLiteral -> SemanticJson.union "Atom" "UnitLiteral" []
 | InstrumentedANF.IntLiteral (field0) -> SemanticJson.union "Atom" "IntLiteral" [aNF_sizedInt field0]
 | InstrumentedANF.BoolLiteral (field0) -> SemanticJson.union "Atom" "BoolLiteral" [boolean field0]
 | InstrumentedANF.StringLiteral (field0) -> SemanticJson.union "Atom" "StringLiteral" [SemanticJson.string field0]
 | InstrumentedANF.FloatLiteral (field0) -> SemanticJson.union "Atom" "FloatLiteral" [float64 field0]
 | InstrumentedANF.Var (field0) -> SemanticJson.union "Atom" "Var" [aNF_tempId field0]
 | InstrumentedANF.FuncRef (field0) -> SemanticJson.union "Atom" "FuncRef" [functionId field0]
and aNF_binOp (value : InstrumentedANF.binOp) = match value with
 | InstrumentedANF.Add -> SemanticJson.union "BinOp" "Add" []
 | InstrumentedANF.Sub -> SemanticJson.union "BinOp" "Sub" []
 | InstrumentedANF.Mul -> SemanticJson.union "BinOp" "Mul" []
 | InstrumentedANF.Div -> SemanticJson.union "BinOp" "Div" []
 | InstrumentedANF.Mod -> SemanticJson.union "BinOp" "Mod" []
 | InstrumentedANF.Shl -> SemanticJson.union "BinOp" "Shl" []
 | InstrumentedANF.Shr -> SemanticJson.union "BinOp" "Shr" []
 | InstrumentedANF.BitAnd -> SemanticJson.union "BinOp" "BitAnd" []
 | InstrumentedANF.BitOr -> SemanticJson.union "BinOp" "BitOr" []
 | InstrumentedANF.BitXor -> SemanticJson.union "BinOp" "BitXor" []
 | InstrumentedANF.Eq -> SemanticJson.union "BinOp" "Eq" []
 | InstrumentedANF.Neq -> SemanticJson.union "BinOp" "Neq" []
 | InstrumentedANF.Lt -> SemanticJson.union "BinOp" "Lt" []
 | InstrumentedANF.Gt -> SemanticJson.union "BinOp" "Gt" []
 | InstrumentedANF.Lte -> SemanticJson.union "BinOp" "Lte" []
 | InstrumentedANF.Gte -> SemanticJson.union "BinOp" "Gte" []
 | InstrumentedANF.And -> SemanticJson.union "BinOp" "And" []
 | InstrumentedANF.Or -> SemanticJson.union "BinOp" "Or" []
and aNF_unaryOp (value : InstrumentedANF.unaryOp) = match value with
 | InstrumentedANF.Neg -> SemanticJson.union "UnaryOp" "Neg" []
 | InstrumentedANF.Not -> SemanticJson.union "UnaryOp" "Not" []
 | InstrumentedANF.BitNot -> SemanticJson.union "UnaryOp" "BitNot" []
and aNF_returnOwnership (value : InstrumentedANF.returnOwnership) = match value with
 | InstrumentedANF.OwnedReturn -> SemanticJson.union "ReturnOwnership" "OwnedReturn" []
 | InstrumentedANF.BorrowedReturn -> SemanticJson.union "ReturnOwnership" "BorrowedReturn" []
and aNF_cliOperation (value : InstrumentedANF.cliOperation) = match value with
 | InstrumentedANF.Execute -> SemanticJson.union "CliOperation" "Execute" []
 | InstrumentedANF.RunProcess -> SemanticJson.union "CliOperation" "RunProcess" []
 | InstrumentedANF.HostOS -> SemanticJson.union "CliOperation" "HostOS" []
 | InstrumentedANF.HostArchitecture -> SemanticJson.union "CliOperation" "HostArchitecture" []
 | InstrumentedANF.Hostname -> SemanticJson.union "CliOperation" "Hostname" []
 | InstrumentedANF.GetEnv -> SemanticJson.union "CliOperation" "GetEnv" []
 | InstrumentedANF.GetEnvironmentPacked -> SemanticJson.union "CliOperation" "GetEnvironmentPacked" []
 | InstrumentedANF.SetEnv -> SemanticJson.union "CliOperation" "SetEnv" []
 | InstrumentedANF.UnsetEnv -> SemanticJson.union "CliOperation" "UnsetEnv" []
 | InstrumentedANF.DirectoryCurrent -> SemanticJson.union "CliOperation" "DirectoryCurrent" []
 | InstrumentedANF.DirectoryListPacked -> SemanticJson.union "CliOperation" "DirectoryListPacked" []
 | InstrumentedANF.FileIsDirectory -> SemanticJson.union "CliOperation" "FileIsDirectory" []
 | InstrumentedANF.FileCreateExclusive -> SemanticJson.union "CliOperation" "FileCreateExclusive" []
 | InstrumentedANF.GetArgv -> SemanticJson.union "CliOperation" "GetArgv" []
 | InstrumentedANF.Kill -> SemanticJson.union "CliOperation" "Kill" []
 | InstrumentedANF.GetPid -> SemanticJson.union "CliOperation" "GetPid" []
 | InstrumentedANF.GetUid -> SemanticJson.union "CliOperation" "GetUid" []
 | InstrumentedANF.CpuCount -> SemanticJson.union "CliOperation" "CpuCount" []
 | InstrumentedANF.SpawnProcess -> SemanticJson.union "CliOperation" "SpawnProcess" []
 | InstrumentedANF.ProcessIO -> SemanticJson.union "CliOperation" "ProcessIO" []
 | InstrumentedANF.TerminateProcess -> SemanticJson.union "CliOperation" "TerminateProcess" []
 | InstrumentedANF.SocketTcp4 -> SemanticJson.union "CliOperation" "SocketTcp4" []
 | InstrumentedANF.SocketTcp6 -> SemanticJson.union "CliOperation" "SocketTcp6" []
 | InstrumentedANF.SocketUdp4 -> SemanticJson.union "CliOperation" "SocketUdp4" []
 | InstrumentedANF.SocketUdp6 -> SemanticJson.union "CliOperation" "SocketUdp6" []
 | InstrumentedANF.SocketConnect4 -> SemanticJson.union "CliOperation" "SocketConnect4" []
 | InstrumentedANF.SocketConnect6 -> SemanticJson.union "CliOperation" "SocketConnect6" []
 | InstrumentedANF.SocketSend -> SemanticJson.union "CliOperation" "SocketSend" []
 | InstrumentedANF.SocketReceive -> SemanticJson.union "CliOperation" "SocketReceive" []
 | InstrumentedANF.SocketReceiveTimeout -> SemanticJson.union "CliOperation" "SocketReceiveTimeout" []
 | InstrumentedANF.SocketSendTimeout -> SemanticJson.union "CliOperation" "SocketSendTimeout" []
 | InstrumentedANF.SocketClose -> SemanticJson.union "CliOperation" "SocketClose" []
 | InstrumentedANF.SocketBind4 -> SemanticJson.union "CliOperation" "SocketBind4" []
 | InstrumentedANF.SocketListen -> SemanticJson.union "CliOperation" "SocketListen" []
 | InstrumentedANF.SocketAccept -> SemanticJson.union "CliOperation" "SocketAccept" []
 | InstrumentedANF.SocketCloexec -> SemanticJson.union "CliOperation" "SocketCloexec" []
 | InstrumentedANF.SocketReuseAddress -> SemanticJson.union "CliOperation" "SocketReuseAddress" []
 | InstrumentedANF.SocketPoll -> SemanticJson.union "CliOperation" "SocketPoll" []
 | InstrumentedANF.SignalBlock -> SemanticJson.union "CliOperation" "SignalBlock" []
 | InstrumentedANF.SignalRestore -> SemanticJson.union "CliOperation" "SignalRestore" []
 | InstrumentedANF.SignalPending -> SemanticJson.union "CliOperation" "SignalPending" []
 | InstrumentedANF.SignalWait -> SemanticJson.union "CliOperation" "SignalWait" []
 | InstrumentedANF.MonotonicTime -> SemanticJson.union "CliOperation" "MonotonicTime" []
 | InstrumentedANF.SecureRandomFill -> SemanticJson.union "CliOperation" "SecureRandomFill" []
and aNF_recordDescriptor (value : InstrumentedANF.recordDescriptor) = SemanticJson.record "RecordDescriptor" ["SourceTypeName", SemanticJson.string value.InstrumentedANF.sourceTypeName; "RuntimeTypeName", SemanticJson.string value.InstrumentedANF.runtimeTypeName; "TypeArgs", list (fun item -> SemanticAST.semanticType item) value.InstrumentedANF.typeArgs; "Fields", list (fun item -> (let part0, part1 = item in tuple [SemanticJson.string part0; SemanticAST.semanticType part1])) value.InstrumentedANF.fields; "ValueType", SemanticAST.semanticType value.InstrumentedANF.valueType]
and aNF_cExpr (value : InstrumentedANF.cExpr) = match value with
 | InstrumentedANF.Atom (field0) -> SemanticJson.union "CExpr" "Atom" [aNF_atom field0]
 | InstrumentedANF.TypedAtom (field0, field1) -> SemanticJson.union "CExpr" "TypedAtom" [aNF_atom field0; SemanticAST.semanticType field1]
 | InstrumentedANF.Prim (field0, field1, field2) -> SemanticJson.union "CExpr" "Prim" [aNF_binOp field0; aNF_atom field1; aNF_atom field2]
 | InstrumentedANF.UnaryPrim (field0, field1) -> SemanticJson.union "CExpr" "UnaryPrim" [aNF_unaryOp field0; aNF_atom field1]
 | InstrumentedANF.IfValue (field0, field1, field2) -> SemanticJson.union "CExpr" "IfValue" [aNF_atom field0; aNF_atom field1; aNF_atom field2]
 | InstrumentedANF.Call (field0, field1) -> SemanticJson.union "CExpr" "Call" [functionId field0; list (fun item -> aNF_atom item) field1]
 | InstrumentedANF.BorrowedCall (field0, field1) -> SemanticJson.union "CExpr" "BorrowedCall" [functionId field0; list (fun item -> aNF_atom item) field1]
 | InstrumentedANF.TailCall (field0, field1) -> SemanticJson.union "CExpr" "TailCall" [functionId field0; list (fun item -> aNF_atom item) field1]
 | InstrumentedANF.IndirectCall (field0, field1) -> SemanticJson.union "CExpr" "IndirectCall" [aNF_atom field0; list (fun item -> aNF_atom item) field1]
 | InstrumentedANF.IndirectTailCall (field0, field1) -> SemanticJson.union "CExpr" "IndirectTailCall" [aNF_atom field0; list (fun item -> aNF_atom item) field1]
 | InstrumentedANF.ClosureAlloc (field0, field1) -> SemanticJson.union "CExpr" "ClosureAlloc" [functionId field0; list (fun item -> aNF_atom item) field1]
 | InstrumentedANF.ClosureCall (field0, field1) -> SemanticJson.union "CExpr" "ClosureCall" [aNF_atom field0; list (fun item -> aNF_atom item) field1]
 | InstrumentedANF.ClosureTailCall (field0, field1) -> SemanticJson.union "CExpr" "ClosureTailCall" [aNF_atom field0; list (fun item -> aNF_atom item) field1]
 | InstrumentedANF.TupleAlloc (field0) -> SemanticJson.union "CExpr" "TupleAlloc" [list (fun item -> aNF_atom item) field0]
 | InstrumentedANF.TupleGet (field0, field1) -> SemanticJson.union "CExpr" "TupleGet" [aNF_atom field0; int32 field1]
 | InstrumentedANF.RecordAlloc (field0, field1) -> SemanticJson.union "CExpr" "RecordAlloc" [aNF_recordDescriptor field0; list (fun item -> aNF_atom item) field1]
 | InstrumentedANF.RecordGet (field0, field1, field2) -> SemanticJson.union "CExpr" "RecordGet" [aNF_recordDescriptor field0; aNF_atom field1; int32 field2]
 | InstrumentedANF.RecordClone (field0, field1, field2) -> SemanticJson.union "CExpr" "RecordClone" [aNF_recordDescriptor field0; aNF_atom field1; list (fun item -> aNF_atom item) field2]
 | InstrumentedANF.RecordReuse (field0, field1, field2, field3) -> SemanticJson.union "CExpr" "RecordReuse" [aNF_recordDescriptor field0; aNF_recordDescriptor field1; aNF_atom field2; list (fun item -> aNF_atom item) field3]
 | InstrumentedANF.StringConcat (field0, field1, field2) -> SemanticJson.union "CExpr" "StringConcat" [aNF_atom field0; aNF_atom field1; list (fun item -> aNF_atom item) field2]
 | InstrumentedANF.CanonicalBufferEq (field0, field1, field2) -> SemanticJson.union "CExpr" "CanonicalBufferEq" [memoryModel_canonicalBufferKind field0; aNF_atom field1; aNF_atom field2]
 | InstrumentedANF.RefCountInc (field0, field1, field2, field3) -> SemanticJson.union "CExpr" "RefCountInc" [aNF_atom field0; int32 field1; memoryModel_rcKind field2; option (fun item -> memoryModel_rcMetadata item) field3]
 | InstrumentedANF.RefCountDec (field0, field1, field2, field3) -> SemanticJson.union "CExpr" "RefCountDec" [aNF_atom field0; int32 field1; memoryModel_rcKind field2; option (fun item -> memoryModel_rcMetadata item) field3]
 | InstrumentedANF.Print (field0, field1) -> SemanticJson.union "CExpr" "Print" [aNF_atom field0; SemanticAST.semanticType field1]
 | InstrumentedANF.StdoutWrite (field0, field1) -> SemanticJson.union "CExpr" "StdoutWrite" [aNF_atom field0; boolean field1]
 | InstrumentedANF.StdinReadLine -> SemanticJson.union "CExpr" "StdinReadLine" []
 | InstrumentedANF.RuntimeError (field0) -> SemanticJson.union "CExpr" "RuntimeError" [SemanticJson.string field0]
 | InstrumentedANF.RuntimeErrorString (field0) -> SemanticJson.union "CExpr" "RuntimeErrorString" [aNF_atom field0]
 | InstrumentedANF.FileReadBlob (field0) -> SemanticJson.union "CExpr" "FileReadBlob" [aNF_atom field0]
 | InstrumentedANF.FileExists (field0) -> SemanticJson.union "CExpr" "FileExists" [aNF_atom field0]
 | InstrumentedANF.FileWriteBlob (field0, field1) -> SemanticJson.union "CExpr" "FileWriteBlob" [aNF_atom field0; aNF_atom field1]
 | InstrumentedANF.FileAppendText (field0, field1) -> SemanticJson.union "CExpr" "FileAppendText" [aNF_atom field0; aNF_atom field1]
 | InstrumentedANF.FileDelete (field0) -> SemanticJson.union "CExpr" "FileDelete" [aNF_atom field0]
 | InstrumentedANF.FileCreateDirectory (field0) -> SemanticJson.union "CExpr" "FileCreateDirectory" [aNF_atom field0]
 | InstrumentedANF.FileSetExecutable (field0) -> SemanticJson.union "CExpr" "FileSetExecutable" [aNF_atom field0]
 | InstrumentedANF.FileWriteFromPtr (field0, field1, field2) -> SemanticJson.union "CExpr" "FileWriteFromPtr" [aNF_atom field0; aNF_atom field1; aNF_atom field2]
 | InstrumentedANF.FloatSqrt (field0) -> SemanticJson.union "CExpr" "FloatSqrt" [aNF_atom field0]
 | InstrumentedANF.FloatAbs (field0) -> SemanticJson.union "CExpr" "FloatAbs" [aNF_atom field0]
 | InstrumentedANF.FloatNeg (field0) -> SemanticJson.union "CExpr" "FloatNeg" [aNF_atom field0]
 | InstrumentedANF.Int64ToFloat (field0) -> SemanticJson.union "CExpr" "Int64ToFloat" [aNF_atom field0]
 | InstrumentedANF.FloatToInt64 (field0) -> SemanticJson.union "CExpr" "FloatToInt64" [aNF_atom field0]
 | InstrumentedANF.FloatToBits (field0) -> SemanticJson.union "CExpr" "FloatToBits" [aNF_atom field0]
 | InstrumentedANF.RawAlloc (field0) -> SemanticJson.union "CExpr" "RawAlloc" [aNF_atom field0]
 | InstrumentedANF.MappedAlloc (field0) -> SemanticJson.union "CExpr" "MappedAlloc" [aNF_atom field0]
 | InstrumentedANF.RawFree (field0) -> SemanticJson.union "CExpr" "RawFree" [aNF_atom field0]
 | InstrumentedANF.MappedFree (field0) -> SemanticJson.union "CExpr" "MappedFree" [aNF_atom field0]
 | InstrumentedANF.RawGet (field0, field1, field2) -> SemanticJson.union "CExpr" "RawGet" [aNF_atom field0; aNF_atom field1; option (fun item -> SemanticAST.semanticType item) field2]
 | InstrumentedANF.RawTake (field0, field1, field2) -> SemanticJson.union "CExpr" "RawTake" [aNF_atom field0; aNF_atom field1; option (fun item -> SemanticAST.semanticType item) field2]
 | InstrumentedANF.RawGetByte (field0, field1) -> SemanticJson.union "CExpr" "RawGetByte" [aNF_atom field0; aNF_atom field1]
 | InstrumentedANF.RawWriteWord (field0, field1, field2) -> SemanticJson.union "CExpr" "RawWriteWord" [aNF_atom field0; aNF_atom field1; aNF_atom field2]
 | InstrumentedANF.RawWriteByte (field0, field1, field2) -> SemanticJson.union "CExpr" "RawWriteByte" [aNF_atom field0; aNF_atom field1; aNF_atom field2]
 | InstrumentedANF.RawSlotInit (field0, field1, field2, field3) -> SemanticJson.union "CExpr" "RawSlotInit" [aNF_atom field0; aNF_atom field1; aNF_atom field2; SemanticAST.semanticType field3]
 | InstrumentedANF.StringToRawPtr (field0) -> SemanticJson.union "CExpr" "StringToRawPtr" [aNF_atom field0]
 | InstrumentedANF.RawPtrToString (field0) -> SemanticJson.union "CExpr" "RawPtrToString" [aNF_atom field0]
 | InstrumentedANF.BlobToRawPtr (field0) -> SemanticJson.union "CExpr" "BlobToRawPtr" [aNF_atom field0]
 | InstrumentedANF.RawPtrToBlob (field0) -> SemanticJson.union "CExpr" "RawPtrToBlob" [aNF_atom field0]
 | InstrumentedANF.RawPtrToInt128 (field0) -> SemanticJson.union "CExpr" "RawPtrToInt128" [aNF_atom field0]
 | InstrumentedANF.RawPtrToUInt128 (field0) -> SemanticJson.union "CExpr" "RawPtrToUInt128" [aNF_atom field0]
 | InstrumentedANF.DictToRawPtr (field0) -> SemanticJson.union "CExpr" "DictToRawPtr" [aNF_atom field0]
 | InstrumentedANF.RawPtrToDict (field0, field1, field2) -> SemanticJson.union "CExpr" "RawPtrToDict" [aNF_atom field0; aNF_atom field1; SemanticAST.semanticType field2]
 | InstrumentedANF.ListToRawPtr (field0) -> SemanticJson.union "CExpr" "ListToRawPtr" [aNF_atom field0]
 | InstrumentedANF.FixedBlockToRawPtr (field0) -> SemanticJson.union "CExpr" "FixedBlockToRawPtr" [aNF_atom field0]
 | InstrumentedANF.RawPtrToList (field0, field1, field2) -> SemanticJson.union "CExpr" "RawPtrToList" [aNF_atom field0; aNF_atom field1; SemanticAST.semanticType field2]
 | InstrumentedANF.RefCountIncString (field0) -> SemanticJson.union "CExpr" "RefCountIncString" [aNF_atom field0]
 | InstrumentedANF.RefCountDecString (field0) -> SemanticJson.union "CExpr" "RefCountDecString" [aNF_atom field0]
 | InstrumentedANF.RefCountIncBlob (field0) -> SemanticJson.union "CExpr" "RefCountIncBlob" [aNF_atom field0]
 | InstrumentedANF.RefCountDecBlob (field0) -> SemanticJson.union "CExpr" "RefCountDecBlob" [aNF_atom field0]
 | InstrumentedANF.RefCountIncInt (field0) -> SemanticJson.union "CExpr" "RefCountIncInt" [aNF_atom field0]
 | InstrumentedANF.RefCountDecInt (field0) -> SemanticJson.union "CExpr" "RefCountDecInt" [aNF_atom field0]
 | InstrumentedANF.RandomInt64 -> SemanticJson.union "CExpr" "RandomInt64" []
 | InstrumentedANF.DateTimeNow -> SemanticJson.union "CExpr" "DateTimeNow" []
 | InstrumentedANF.Sleep (field0) -> SemanticJson.union "CExpr" "Sleep" [aNF_atom field0]
 | InstrumentedANF.CliNative (field0, field1) -> SemanticJson.union "CExpr" "CliNative" [aNF_cliOperation field0; list (fun item -> aNF_atom item) field1]
 | InstrumentedANF.FloatToString (field0) -> SemanticJson.union "CExpr" "FloatToString" [aNF_atom field0]
and aNF_aExpr (value : InstrumentedANF.aExpr) = match value with
 | InstrumentedANF.Let (field0, field1, field2) -> SemanticJson.union "AExpr" "Let" [aNF_tempId field0; aNF_cExpr field1; aNF_aExpr field2]
 | InstrumentedANF.Return (field0) -> SemanticJson.union "AExpr" "Return" [aNF_atom field0]
 | InstrumentedANF.If (field0, field1, field2) -> SemanticJson.union "AExpr" "If" [aNF_atom field0; aNF_aExpr field1; aNF_aExpr field2]
 | InstrumentedANF.Join (field0, field1, field2) -> SemanticJson.union "AExpr" "Join" [aNF_typedParam field0; aNF_aExpr field1; aNF_aExpr field2]
 | InstrumentedANF.Jump (field0, field1) -> SemanticJson.union "AExpr" "Jump" [aNF_tempId field0; aNF_atom field1]
and aNF_functionDef (value : InstrumentedANF.functionDef) = SemanticJson.record "Function" ["Id", functionId value.InstrumentedANF.id; "Name", SemanticJson.string value.InstrumentedANF.name; "TypedParams", list (fun item -> aNF_typedParam item) value.InstrumentedANF.typedParams; "ReturnType", SemanticAST.semanticType value.InstrumentedANF.returnType; "ReturnOwnership", aNF_returnOwnership value.InstrumentedANF.returnOwnership; "Body", aNF_aExpr value.InstrumentedANF.body]
and aNF_program (value : InstrumentedANF.program) = match value with
 | InstrumentedANF.Program (field0, field1) -> SemanticJson.union "Program" "Program" [list (fun item -> aNF_functionDef item) field0; aNF_aExpr field1]
and aNF_varGen (value : InstrumentedANF.varGen) = match value with
 | InstrumentedANF.VarGen (field0) -> SemanticJson.union "VarGen" "VarGen" [int32 field0]
and aNF_typeMap (value : InstrumentedANF.typeMap) = (let first, types = InstrumentedANF.observationParts value in SemanticJson.record "TypeMap" ["FirstId", int32 first; "Types", array (option SemanticAST.semanticType) types])
and aNF_typedProgram (value : InstrumentedANF.typedProgram) = SemanticJson.record "TypedProgram" ["Program", aNF_program value.InstrumentedANF.program; "TypeMap", aNF_typeMap value.InstrumentedANF.typeMap]
and aNF_exprId (value : InstrumentedANF.exprId) = int32 value
and aNF_exprIdGen (value : InstrumentedANF.exprIdGen) = match value with
 | InstrumentedANF.ExprIdGen (field0) -> SemanticJson.union "ExprIdGen" "ExprIdGen" [int32 field0]
and aNF_coverageMapping (value : InstrumentedANF.coverageMapping) = SemanticJson.record "CoverageMapping" ["Descriptions", coverageMap value.InstrumentedANF.descriptions; "TotalExpressions", int32 value.InstrumentedANF.totalExpressions]
