(* Full integer, comparison, shift, presentation and parallel-move emission. *)
open Dark_compiler
module E=X64EmitInteger
let tuple xs=`Assoc ["tuple",`List xs]
let list f xs=`List (List.map f xs)
let call f=try tuple [`Bool false;(match f () with Ok xs->SemanticJson.union "FSharpResult" "Ok" [`List (List.map MachineISAObservation.x64Instr xs)] | Error e->SemanticJson.union "FSharpResult" "Error" [SemanticJson.string e])] with Failure e | Invalid_argument e->tuple [`Bool true;SemanticJson.string e]
let observe source=
 let physical=[LIR.X0;LIR.X1;LIR.X2;LIR.X3;LIR.X4;LIR.X5;LIR.X6;LIR.X7;LIR.X8;LIR.X9;LIR.X10;LIR.X11;LIR.X12;LIR.X13;LIR.X14;LIR.X15;LIR.X16;LIR.X17;LIR.X19;LIR.X20;LIR.X21;LIR.X22;LIR.X23;LIR.X24;LIR.X25;LIR.X26;LIR.X27;LIR.X29;LIR.X30;LIR.SP] in
 let gps=List.map (fun p->LIR.Physical p) physical@[LIR.Virtual (-1);LIR.Virtual 0;LIR.Virtual 2147483647] in
 let selected=List.map (fun p->LIR.Physical p) [LIR.X0;LIR.X3;LIR.X7;LIR.X8;LIR.X19]@[LIR.Virtual (-1)] in
 let sizes=[-2147483648;-32769;-1;0;8;32768;2147483647] in
 let imms=[Int64.min_int;-2147483649L;-2147483648L;-1L;0L;1L;2147483647L;2147483648L;Int64.max_int] in
 let operands=List.map (fun reg->LIR.Reg reg) gps@List.map (fun n->LIR.StackSlot n) sizes@List.map (fun n->LIR.Imm n) imms@[LIR.FloatImm (-0.);LIR.FloatImm (Int64.float_of_bits 0xfff8000000000000L);LIR.FloatSymbol 0.1;LIR.FloatSymbol (Int64.float_of_bits 0x7ff8000000000001L);LIR.FloatSymbol (Int64.float_of_bits 0x7ff0000000000001L);LIR.StringSymbol source;LIR.StringSymbol "hé😀";LIR.StringSymbol (HostText.ofScalars [|0xfffd;0x61;0xfffd|]);LIR.FuncAddr (AST.functionId 0L);LIR.FuncAddr (AST.functionId 2L);LIR.FuncAddr (AST.functionId (-1L))] in
 let ctx enabled={X64CodeGenTypes.functionName=source;stackSize=32;usedCalleeSaved=[LIR.X19;LIR.X20];enableLeakCheck=enabled;recordRegistry=StringOrder.Map.empty;sumShapeRegistry=StringOrder.Map.empty;functionNames=FunctionIdMap.ofList [AST.functionId 0L,source;AST.functionId (-1L),"largest"]} in
 let c=ctx false in
 let contexts=[None;Some X64InstructionContext.IntegerComparison;Some X64InstructionContext.FloatComparison] in
 let conditions=[LIR.EQ;LIR.NE;LIR.LT;LIR.GT;LIR.LE;LIR.GE;LIR.ULT;LIR.UGT;LIR.ULE;LIR.UGE] in
 let movs=list (fun dest->list (fun operand->call (fun ()->E.emitMov c dest operand)) operands) gps in
 let stores=list (fun offset->list (fun reg->call (fun ()->E.emitStore c offset reg)) gps) sizes in
 let arithmetic=list (fun dest->list (fun left->list (fun right->let adds=list (fun comparison->call (fun ()->E.emitAdd c comparison dest left right)) contexts in let sub=call (fun ()->E.emitSub c dest left right) in let cmp=call (fun ()->E.emitCmp c left right) in tuple [adds;sub;cmp]) operands) selected) gps in
 let binaries=list (fun dest->list (fun left->list (fun right->let operations=list call [(fun ()->E.emitMul c dest left right);(fun ()->E.emitSdiv c dest left right);(fun ()->E.emitUdiv c dest left right);(fun ()->E.emitAnd c dest left right);(fun ()->E.emitOrr c dest left right);(fun ()->E.emitEor c dest left right);(fun ()->E.emitLsl c dest left right);(fun ()->E.emitLsr c dest left right);(fun ()->E.emitAsr c dest left right)] in let fused=list (fun acc->list call [(fun ()->E.emitMsub c dest left right acc);(fun ()->E.emitMadd c dest left right acc)]) [dest;left;LIR.Physical LIR.X3] in tuple [operations;fused]) [dest;left;LIR.Physical LIR.X3;LIR.Physical LIR.X8;LIR.Virtual (-1)]) selected) gps in
 let compares=list (fun comparison->list (fun dest->list (fun condition->let cset=call (fun ()->E.emitCset c comparison dest condition) in let selects=list (fun left->list (fun right->call (fun ()->E.emitSelect c comparison dest left right condition)) [left;dest;LIR.Physical LIR.X8]) selected in tuple [cset;selects]) conditions) gps) contexts in
 let unary=list (fun dest->list (fun src->let operations=list call [(fun ()->E.emitNeg c dest src);(fun ()->E.emitMvn c dest src);(fun ()->E.emitSxtb c dest src);(fun ()->E.emitSxth c dest src);(fun ()->E.emitSxtw c dest src);(fun ()->E.emitUxtb c dest src);(fun ()->E.emitUxth c dest src);(fun ()->E.emitUxtw c dest src)] in let masks=list (fun imm->call (fun ()->E.emitAnd_imm c dest src imm)) imms in let shifts=list (fun shift->list call [(fun ()->E.emitLsl_imm c dest src shift);(fun ()->E.emitLsr_imm c dest src shift);(fun ()->E.emitAsr_imm c dest src shift)]) [-2147483648;-1;0;1;31;32;63;64;255;256;2147483647] in tuple [operations;masks;shifts]) [dest;LIR.Physical LIR.X3;LIR.Physical LIR.X8;LIR.Virtual (-1)]) gps in
 let floats=List.map (fun p->LIR.FPhysical p) [LIR.D0;LIR.D1;LIR.D2;LIR.D3;LIR.D4;LIR.D5;LIR.D6;LIR.D7;LIR.D8;LIR.D9;LIR.D10;LIR.D11;LIR.D12;LIR.D13;LIR.D14;LIR.D15]@[LIR.FVirtual (-1);LIR.FVirtual 0;LIR.FVirtual 2147483647] in
 let conversions=list (fun dest->list (fun src->list call [(fun ()->E.emitInt64ToFloat c dest src);(fun ()->E.emitGpToFp c dest src)]) gps) floats in
 let io=list (fun enabled->let c=ctx enabled in let stdout=list (fun operand->list (fun newline->call (fun ()->E.emitStdoutWrite c operand newline)) [false;true]) operands in let stdin=list (fun reg->let input=call (fun ()->E.emitStdinReadLine c reg) in let error=call (fun ()->E.emitRuntimeErrorString c reg) in let phi=call (fun ()->E.emitPhi c reg) in tuple [input;error;phi]) gps in let errors=list (fun text->call (fun ()->E.emitRuntimeError c text)) [source;"hé😀";"a\000b"] in let exit=call (fun ()->E.emitExit c) in tuple [stdout;stdin;errors;exit]) [false;true] in
 let moves=list (fun dest->list (fun operand->list (fun items->let args=call (fun ()->E.emitArgMoves c items) in let tails=call (fun ()->E.emitTailArgMoves c items) in tuple [args;tails]) [[dest,operand];[dest,operand;LIR.X3,LIR.Reg (LIR.Physical dest);dest,LIR.Reg (LIR.Physical LIR.X3)]]) operands) physical in
 let cycles=list (fun items->let args=call (fun ()->E.emitArgMoves c items) in let tails=call (fun ()->E.emitTailArgMoves c items) in tuple [args;tails]) [[];List.map (fun p->p,LIR.Reg (LIR.Physical p)) physical;List.map2 (fun d s->d,LIR.Reg (LIR.Physical s)) physical (List.rev physical)] in
 let closures=list (fun enabled->let c=ctx enabled in list (fun dest->list (fun id->list (fun captures->call (fun ()->E.emitClosureAlloc c dest id captures)) ([]::List.map (fun operand->[operand]) operands@[[LIR.Imm 1L;LIR.Reg dest;LIR.StackSlot (-1)];List.init 40 (fun index->LIR.Imm (Int64.of_int index))])) [AST.functionId 0L;AST.functionId 2L;AST.functionId (-1L)]) gps) [false;true] in
 tuple [movs;stores;arithmetic;binaries;compares;unary;conversions;io;moves;cycles;closures]
