(* Full x64 helper selection, metadata and ordered field release emission. *)
open Dark_compiler
module E=InstrumentedX64ReleaseSelection
open! MemoryModel
let tuple xs=`Assoc ["tuple",`List xs]
let list f xs=`List (List.map f xs)
let call encode f=try tuple [`Bool false;encode (f ())] with Failure _ | Invalid_argument _ -> tuple [`Bool true]
let boolean value=`Bool value
let option encode=function None->SemanticJson.union "FSharpOption" "None" [] | Some value->SemanticJson.union "FSharpOption" "Some" [encode value]
let plan=SemanticANF.memoryModel_rcReleasePlan
let code=list MachineISAObservation.x64Instr
let target=function E.SlotInitListRootRetain->SemanticJson.union "SlotInitRootRetainTarget" "SlotInitListRootRetain" [] | E.SlotInitDictRootRetain->SemanticJson.union "SlotInitRootRetainTarget" "SlotInitDictRootRetain" [] | E.SlotInitDynamicBufferRetain->SemanticJson.union "SlotInitRootRetainTarget" "SlotInitDynamicBufferRetain" [] | E.SlotInitClosureRootRetain->SemanticJson.union "SlotInitRootRetainTarget" "SlotInitClosureRootRetain" [] | E.SlotInitGenericRootRetain size->SemanticJson.union "SlotInitRootRetainTarget" "SlotInitGenericRootRetain" [SemanticJson.int32 size]
let observe source=
 let kinds=[GenericHeap;StreamHeap;TaggedList;DictHeap;ClosureHeap] in
 let operations=[DynamicStringBuffer;DynamicBlobBuffer;DynamicIntBuffer]@List.concat_map (fun kind -> List.map (fun size -> FixedSizeRoot (size,kind)) [-2147483648;-1;0;8;2147483647]) kinds in
 let simple=[NoReleasePlan;RecursiveRelease (AST.TRecord (source,[]))]@List.map (fun operation -> DynamicBufferRelease operation) operations@List.concat_map (fun kind -> [RootRelease (8,kind,NoPayloadRelease);RootRelease (8,kind,FixedBlockPayloadRelease (8,[]));RootRelease (8,kind,BoxedSumPayloadRelease (8,[],[]));RootRelease (8,kind,ClosurePayloadRelease [])]) kinds in
 let listPlans=List.map (fun plan -> RootRelease (8,TaggedList,TaggedListPayloadRelease plan)) simple in
 let dictPlans=List.concat_map (fun value -> [RootRelease (16,DictHeap,DictPayloadRelease (NoReleasePlan,value));RootRelease (16,DictHeap,DictPayloadRelease (DynamicBufferRelease DynamicStringBuffer,value));RootRelease (16,DictHeap,DictPayloadRelease (value,NoReleasePlan))]) (simple@listPlans) in
 let fields=[FieldRelease (0,DynamicBufferRelease DynamicStringBuffer);FieldRelease (8,RootRelease (8,TaggedList,TaggedListPayloadRelease NoReleasePlan));FieldRelease (16,RootRelease (16,DictHeap,DictPayloadRelease (NoReleasePlan,NoReleasePlan)))] in
 let rich=List.concat_map (fun size -> List.concat_map (fun fields -> [RootRelease (size,GenericHeap,FixedBlockPayloadRelease (size,fields));RootRelease (size,GenericHeap,BoxedSumPayloadRelease (size,fields,[{tag=1;fieldReleases=fields}]))]) [fields;List.rev fields;[FieldRelease (8,NoReleasePlan)]@fields;fields@[FieldRelease (8,NoReleasePlan)];[FieldRelease (8,DynamicBufferRelease DynamicStringBuffer)];[]]) [8;16;24;256] in
 let plans=simple@listPlans@dictPlans@rich in
 let records=StringOrder.Map.of_list ["R",["a",AST.TString;"b",AST.TList AST.TBlob;"c",AST.TDict (AST.TInt64,AST.TInt64)];"Rec",["next",AST.TRecord ("Rec",[])];"Child",["x",AST.TTuple [AST.TString;AST.TList AST.TString]];"Large",List.init 35 (fun index -> string_of_int index,AST.TString)] in
 let info payloads unary={MemoryModel.typeParams=[];MemoryModel.payloads=payloads;MemoryModel.unaryPayloadTags=MemoryModel.IntSet.of_list unary} in
 let sums=StringOrder.Map.of_list ["None",info [] [];"Nullable",info [0,None;1,Some AST.TString] [1];"S",info [0,None;1,Some (AST.TTuple [AST.TString;AST.TList AST.TString]);65536,Some (AST.TRecord ("Child",[]))] [];"RecSum",info [0,None;1,Some (AST.TTuple [AST.TString;AST.TSum ("RecSum",[])] )] []] in
 let primitives=[AST.TInt8;AST.TInt16;AST.TInt32;AST.TInt64;AST.TInt128;AST.TInt;AST.TUInt8;AST.TUInt16;AST.TUInt32;AST.TUInt64;AST.TUInt128;AST.TBool;AST.TFloat64;AST.TString;AST.TBlob;AST.TChar;AST.TDateTime;AST.TUnit;AST.TNever;AST.TInternalRawPtr;AST.TVar source;AST.TInferenceVar (source,source);AST.TFunction ([AST.TString],AST.TBool);AST.TRecord ("missing",[]);AST.TRecord ("R",[]);AST.TRecord ("Rec",[]);AST.TRecord ("Child",[]);AST.TRecord ("Large",[]);AST.TSum ("missing",[]);AST.TSum ("None",[]);AST.TSum ("Nullable",[]);AST.TSum ("S",[]);AST.TSum ("RecSum",[]);AST.TTuple [];AST.TTuple [AST.TString;AST.TList AST.TString]] in
 let types=primitives@List.concat_map (fun typ -> [AST.TList typ;AST.TList (AST.TList typ);AST.TStream typ;AST.TDict (AST.TInt64,typ);AST.TDict (AST.TString,typ);AST.TTuple [typ;AST.TString];AST.TTuple [AST.TTuple [typ;AST.TBlob];AST.TTuple [AST.TList typ;AST.TDict (AST.TString,typ)]]]) primitives in

 let plans=plans@[RootRelease (16,GenericHeap,BoxedSumPayloadRelease (16,[],[{tag=1;fieldReleases=[FieldRelease (8,DynamicBufferRelease DynamicStringBuffer)]}]))] in
 let predicates=[(fun _->false);(fun _->true);E.releasePlanIsDynamicBufferRelease;E.releasePlanIsDictWithListValue]@List.map E.releasePlanIsRootKind kinds in
 let selected=list (fun p -> tuple [call SemanticJson.string (fun ()->E.listDecHelperForReleasePlan p);call SemanticJson.string (fun ()->E.dictDecHelperForReleasePlan p);call SemanticJson.string (fun ()->E.plannedListDecHelperLabelForReleasePlan p);call SemanticJson.string (fun ()->E.plannedDictDecHelperLabelForReleasePlan p);list (fun pred->tuple [call boolean (fun ()->E.rcReleasePlanContains pred p);call boolean (fun ()->E.releasePlanIsTaggedListWithElementRelease pred p)]) predicates;list (fun kind->call boolean (fun ()->E.releasePlanIsRootKind kind p)) kinds;call boolean (fun ()->E.releasePlanIsDictWithListValue p);call boolean (fun ()->E.releasePlanIsDynamicBufferRelease p)]) plans in
 let paired=list (fun key->list (fun value->call boolean (fun ()->E.dictPayloadReleaseNeedsPlannedHelper key value)) plans) plans in
 let fieldPlans=List.concat_map (fun offset->List.map (fun p->[FieldRelease (offset,p)]) simple) [-2147483648;-1;0;8;16;2147483647]@[fields;List.rev fields;[FieldRelease (8,NoReleasePlan)]@fields;fields@[FieldRelease (8,NoReleasePlan)];[]] in
 let fieldSelections=list (fun fs->list (fun offset->tuple [call (option plan) (fun ()->E.releasePlanFieldReleaseAt offset fs);call boolean (fun ()->E.releasePlanIsDynamicBufferAt offset fs);list (fun kind->call boolean (fun ()->E.releasePlanIsRootKindAt offset kind fs)) kinds;list (fun pred->call boolean (fun ()->E.releasePlanIsDictWithValueAt offset pred fs)) predicates]) [-2147483648;-1;0;8;16;2147483647]) fieldPlans in
 let typed=list (fun typ->tuple [call (option plan) (fun ()->E.tryRcReleasePlanOfType records sums typ);call (option target) (fun ()->E.slotInitRootRetainTarget records sums typ);call SemanticJson.string (fun ()->E.listDecHelperForType records sums typ);call SemanticJson.string (fun ()->E.recursiveNominalRefCountDecHelperLabel typ);list (fun pred->call boolean (fun ()->E.typeReleasePlanContains pred records sums typ)) predicates]) types in
 let metadata=[None;Some {releasePlanCacheKey=None;releasePlan=None;sourceType=None}]@List.map (fun p->Some {releasePlanCacheKey=Some source;releasePlan=Some p;sourceType=None}) plans in
 let metadataCases=list (fun meta->tuple [call (option plan) (fun ()->E.rcMetadataReleasePlan meta);call plan (fun ()->E.requiredRcMetadataReleasePlan source meta)]) metadata in
 let offsets=[-2147483648;-1;0;8;16;2147483647] in
 let emission=list (fun enabled->let ctx={X64CodeGenTypes.functionName=source;stackSize=0;usedCalleeSaved=[];enableLeakCheck=enabled;recordRegistry=records;sumShapeRegistry=sums;functionNames=FunctionIdMap.empty} in list (fun offset->let dynamic=list (fun tagged->call code (fun ()->E.genDynamicBufferFieldRelease ctx tagged offset)) [false;true] in let closure=call code (fun ()->E.genClosureFieldRelease offset) in let children=list (fun p->list (fun f->call code f) [(fun ()->E.genDictFieldRelease offset p);(fun ()->E.genListFieldRelease offset p)]) plans in tuple [dynamic;closure;children]) offsets) [false;true] in
 tuple [selected;paired;fieldSelections;typed;metadataCases;emission;list plan [E.dictTupleStringListValueReleasePlan;E.dictTupleStringListDictValueReleasePlan;E.dictSumStringValueReleasePlan]]
